(define (problem BW-7-10-46)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 - block)
    (:init
        (handempty)
        (on b1 b4)
        (on b2 b6)
        (on-table b3)
        (on b4 b3)
        (on b5 b1)
        (on b6 b5)
        (on b7 b2)
        (clear b7)
    )
    (:goal
        (and
            (on b1 b5)
            (on b2 b1)
            (on-table b3)
            (on b4 b6)
            (on b5 b7)
            (on-table b6)
            (on-table b7)
        )
    )
)