(define (problem BW-10-10-44)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b6)
        (on b3 b10)
        (on b4 b2)
        (on b5 b3)
        (on b6 b5)
        (on b7 b4)
        (on b8 b9)
        (on-table b9)
        (on-table b10)
        (clear b1)
        (clear b7)
        (clear b8)
    )
    (:goal
        (and
            (on-table b1)
            (on b2 b5)
            (on b3 b9)
            (on-table b4)
            (on-table b5)
            (on b6 b3)
            (on b7 b2)
            (on b8 b1)
            (on b9 b10)
            (on-table b10)
        )
    )
)