(define (problem BW-13-10-43)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 - block)
    (:init
        (handempty)
        (on b1 b3)
        (on-table b2)
        (on b3 b10)
        (on-table b4)
        (on b5 b1)
        (on-table b6)
        (on b7 b4)
        (on b8 b12)
        (on-table b9)
        (on b10 b13)
        (on-table b11)
        (on b12 b11)
        (on b13 b8)
        (clear b2)
        (clear b5)
        (clear b6)
        (clear b7)
        (clear b9)
    )
    (:goal
        (and
            (on-table b1)
            (on-table b2)
            (on b3 b4)
            (on b4 b2)
            (on b5 b8)
            (on b6 b11)
            (on b7 b1)
            (on b8 b10)
            (on b9 b6)
            (on-table b10)
            (on-table b11)
            (on b12 b13)
            (on b13 b3)
        )
    )
)