(define (problem BW-10-10-30)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
    (:init
        (handempty)
        (on b1 b7)
        (on-table b2)
        (on b3 b8)
        (on b4 b10)
        (on b5 b4)
        (on b6 b2)
        (on b7 b3)
        (on-table b8)
        (on b9 b5)
        (on b10 b6)
        (clear b1)
        (clear b9)
    )
    (:goal
        (and
            (on-table b1)
            (on-table b2)
            (on b3 b8)
            (on b4 b10)
            (on b5 b9)
            (on b6 b7)
            (on-table b7)
            (on b8 b2)
            (on-table b9)
            (on b10 b1)
        )
    )
)