(define (problem roverprob1) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 - Waypoint
	camera0 camera1 camera2 camera3 camera4 - Camera
	objective0 objective1 objective2 - Objective
	)
(:init
	(visible waypoint0 waypoint6)
	(visible waypoint6 waypoint0)
	(visible waypoint0 waypoint20)
	(visible waypoint20 waypoint0)
	(visible waypoint0 waypoint24)
	(visible waypoint24 waypoint0)
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint1)
	(visible waypoint1 waypoint4)
	(visible waypoint4 waypoint1)
	(visible waypoint1 waypoint5)
	(visible waypoint5 waypoint1)
	(visible waypoint1 waypoint25)
	(visible waypoint25 waypoint1)
	(visible waypoint2 waypoint17)
	(visible waypoint17 waypoint2)
	(visible waypoint2 waypoint25)
	(visible waypoint25 waypoint2)
	(visible waypoint3 waypoint2)
	(visible waypoint2 waypoint3)
	(visible waypoint3 waypoint16)
	(visible waypoint16 waypoint3)
	(visible waypoint3 waypoint21)
	(visible waypoint21 waypoint3)
	(visible waypoint3 waypoint23)
	(visible waypoint23 waypoint3)
	(visible waypoint4 waypoint6)
	(visible waypoint6 waypoint4)
	(visible waypoint4 waypoint10)
	(visible waypoint10 waypoint4)
	(visible waypoint4 waypoint19)
	(visible waypoint19 waypoint4)
	(visible waypoint4 waypoint20)
	(visible waypoint20 waypoint4)
	(visible waypoint4 waypoint22)
	(visible waypoint22 waypoint4)
	(visible waypoint4 waypoint24)
	(visible waypoint24 waypoint4)
	(visible waypoint5 waypoint7)
	(visible waypoint7 waypoint5)
	(visible waypoint5 waypoint17)
	(visible waypoint17 waypoint5)
	(visible waypoint6 waypoint24)
	(visible waypoint24 waypoint6)
	(visible waypoint6 waypoint26)
	(visible waypoint26 waypoint6)
	(visible waypoint7 waypoint6)
	(visible waypoint6 waypoint7)
	(visible waypoint7 waypoint9)
	(visible waypoint9 waypoint7)
	(visible waypoint7 waypoint14)
	(visible waypoint14 waypoint7)
	(visible waypoint7 waypoint19)
	(visible waypoint19 waypoint7)
	(visible waypoint7 waypoint20)
	(visible waypoint20 waypoint7)
	(visible waypoint7 waypoint23)
	(visible waypoint23 waypoint7)
	(visible waypoint8 waypoint6)
	(visible waypoint6 waypoint8)
	(visible waypoint8 waypoint26)
	(visible waypoint26 waypoint8)
	(visible waypoint9 waypoint4)
	(visible waypoint4 waypoint9)
	(visible waypoint9 waypoint13)
	(visible waypoint13 waypoint9)
	(visible waypoint9 waypoint14)
	(visible waypoint14 waypoint9)
	(visible waypoint9 waypoint16)
	(visible waypoint16 waypoint9)
	(visible waypoint9 waypoint18)
	(visible waypoint18 waypoint9)
	(visible waypoint9 waypoint20)
	(visible waypoint20 waypoint9)
	(visible waypoint9 waypoint22)
	(visible waypoint22 waypoint9)
	(visible waypoint10 waypoint20)
	(visible waypoint20 waypoint10)
	(visible waypoint10 waypoint21)
	(visible waypoint21 waypoint10)
	(visible waypoint10 waypoint24)
	(visible waypoint24 waypoint10)
	(visible waypoint11 waypoint0)
	(visible waypoint0 waypoint11)
	(visible waypoint11 waypoint18)
	(visible waypoint18 waypoint11)
	(visible waypoint11 waypoint23)
	(visible waypoint23 waypoint11)
	(visible waypoint11 waypoint24)
	(visible waypoint24 waypoint11)
	(visible waypoint11 waypoint25)
	(visible waypoint25 waypoint11)
	(visible waypoint12 waypoint1)
	(visible waypoint1 waypoint12)
	(visible waypoint12 waypoint6)
	(visible waypoint6 waypoint12)
	(visible waypoint12 waypoint16)
	(visible waypoint16 waypoint12)
	(visible waypoint12 waypoint22)
	(visible waypoint22 waypoint12)
	(visible waypoint13 waypoint5)
	(visible waypoint5 waypoint13)
	(visible waypoint13 waypoint8)
	(visible waypoint8 waypoint13)
	(visible waypoint13 waypoint18)
	(visible waypoint18 waypoint13)
	(visible waypoint13 waypoint20)
	(visible waypoint20 waypoint13)
	(visible waypoint13 waypoint22)
	(visible waypoint22 waypoint13)
	(visible waypoint13 waypoint26)
	(visible waypoint26 waypoint13)
	(visible waypoint14 waypoint1)
	(visible waypoint1 waypoint14)
	(visible waypoint14 waypoint2)
	(visible waypoint2 waypoint14)
	(visible waypoint14 waypoint20)
	(visible waypoint20 waypoint14)
	(visible waypoint15 waypoint6)
	(visible waypoint6 waypoint15)
	(visible waypoint15 waypoint11)
	(visible waypoint11 waypoint15)
	(visible waypoint15 waypoint12)
	(visible waypoint12 waypoint15)
	(visible waypoint15 waypoint20)
	(visible waypoint20 waypoint15)
	(visible waypoint15 waypoint23)
	(visible waypoint23 waypoint15)
	(visible waypoint16 waypoint1)
	(visible waypoint1 waypoint16)
	(visible waypoint16 waypoint4)
	(visible waypoint4 waypoint16)
	(visible waypoint16 waypoint6)
	(visible waypoint6 waypoint16)
	(visible waypoint16 waypoint7)
	(visible waypoint7 waypoint16)
	(visible waypoint17 waypoint6)
	(visible waypoint6 waypoint17)
	(visible waypoint17 waypoint9)
	(visible waypoint9 waypoint17)
	(visible waypoint17 waypoint11)
	(visible waypoint11 waypoint17)
	(visible waypoint17 waypoint14)
	(visible waypoint14 waypoint17)
	(visible waypoint17 waypoint19)
	(visible waypoint19 waypoint17)
	(visible waypoint17 waypoint20)
	(visible waypoint20 waypoint17)
	(visible waypoint17 waypoint23)
	(visible waypoint23 waypoint17)
	(visible waypoint17 waypoint26)
	(visible waypoint26 waypoint17)
	(visible waypoint18 waypoint2)
	(visible waypoint2 waypoint18)
	(visible waypoint18 waypoint4)
	(visible waypoint4 waypoint18)
	(visible waypoint18 waypoint8)
	(visible waypoint8 waypoint18)
	(visible waypoint18 waypoint10)
	(visible waypoint10 waypoint18)
	(visible waypoint18 waypoint17)
	(visible waypoint17 waypoint18)
	(visible waypoint18 waypoint24)
	(visible waypoint24 waypoint18)
	(visible waypoint19 waypoint3)
	(visible waypoint3 waypoint19)
	(visible waypoint19 waypoint5)
	(visible waypoint5 waypoint19)
	(visible waypoint19 waypoint8)
	(visible waypoint8 waypoint19)
	(visible waypoint20 waypoint16)
	(visible waypoint16 waypoint20)
	(visible waypoint21 waypoint8)
	(visible waypoint8 waypoint21)
	(visible waypoint21 waypoint19)
	(visible waypoint19 waypoint21)
	(visible waypoint21 waypoint24)
	(visible waypoint24 waypoint21)
	(visible waypoint22 waypoint6)
	(visible waypoint6 waypoint22)
	(visible waypoint22 waypoint8)
	(visible waypoint8 waypoint22)
	(visible waypoint22 waypoint10)
	(visible waypoint10 waypoint22)
	(visible waypoint23 waypoint1)
	(visible waypoint1 waypoint23)
	(visible waypoint23 waypoint22)
	(visible waypoint22 waypoint23)
	(visible waypoint24 waypoint2)
	(visible waypoint2 waypoint24)
	(visible waypoint24 waypoint3)
	(visible waypoint3 waypoint24)
	(visible waypoint24 waypoint5)
	(visible waypoint5 waypoint24)
	(visible waypoint24 waypoint9)
	(visible waypoint9 waypoint24)
	(visible waypoint24 waypoint22)
	(visible waypoint22 waypoint24)
	(visible waypoint24 waypoint26)
	(visible waypoint26 waypoint24)
	(visible waypoint25 waypoint12)
	(visible waypoint12 waypoint25)
	(visible waypoint25 waypoint15)
	(visible waypoint15 waypoint25)
	(visible waypoint25 waypoint19)
	(visible waypoint19 waypoint25)
	(visible waypoint25 waypoint24)
	(visible waypoint24 waypoint25)
	(visible waypoint26 waypoint1)
	(visible waypoint1 waypoint26)
	(visible waypoint26 waypoint5)
	(visible waypoint5 waypoint26)
	(visible waypoint26 waypoint20)
	(visible waypoint20 waypoint26)
	(visible waypoint26 waypoint25)
	(visible waypoint25 waypoint26)
	(at_soil_sample waypoint0)
	(at_soil_sample waypoint1)
	(at_rock_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_rock_sample waypoint3)
	(at_soil_sample waypoint4)
	(at_rock_sample waypoint4)
	(at_rock_sample waypoint5)
	(at_soil_sample waypoint6)
	(at_rock_sample waypoint6)
	(at_soil_sample waypoint7)
	(at_rock_sample waypoint7)
	(at_soil_sample waypoint8)
	(at_rock_sample waypoint8)
	(at_soil_sample waypoint9)
	(at_soil_sample waypoint10)
	(at_rock_sample waypoint11)
	(at_soil_sample waypoint13)
	(at_rock_sample waypoint13)
	(at_soil_sample waypoint15)
	(at_soil_sample waypoint16)
	(at_rock_sample waypoint16)
	(at_soil_sample waypoint18)
	(at_rock_sample waypoint19)
	(at_soil_sample waypoint21)
	(at_rock_sample waypoint21)
	(at_rock_sample waypoint23)
	(at_soil_sample waypoint24)
	(at_rock_sample waypoint24)
	(at_soil_sample waypoint25)
	(at_soil_sample waypoint26)
	(at_lander general waypoint9)
	(channel_free general)
	(at rover0 waypoint15)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_rock_analysis rover0)
	(can_traverse rover0 waypoint15 waypoint6)
	(can_traverse rover0 waypoint6 waypoint15)
	(can_traverse rover0 waypoint15 waypoint12)
	(can_traverse rover0 waypoint12 waypoint15)
	(can_traverse rover0 waypoint15 waypoint23)
	(can_traverse rover0 waypoint23 waypoint15)
	(can_traverse rover0 waypoint6 waypoint0)
	(can_traverse rover0 waypoint0 waypoint6)
	(can_traverse rover0 waypoint6 waypoint4)
	(can_traverse rover0 waypoint4 waypoint6)
	(can_traverse rover0 waypoint6 waypoint8)
	(can_traverse rover0 waypoint8 waypoint6)
	(can_traverse rover0 waypoint6 waypoint16)
	(can_traverse rover0 waypoint16 waypoint6)
	(can_traverse rover0 waypoint6 waypoint17)
	(can_traverse rover0 waypoint17 waypoint6)
	(can_traverse rover0 waypoint6 waypoint22)
	(can_traverse rover0 waypoint22 waypoint6)
	(can_traverse rover0 waypoint6 waypoint24)
	(can_traverse rover0 waypoint24 waypoint6)
	(can_traverse rover0 waypoint12 waypoint1)
	(can_traverse rover0 waypoint1 waypoint12)
	(can_traverse rover0 waypoint12 waypoint25)
	(can_traverse rover0 waypoint25 waypoint12)
	(can_traverse rover0 waypoint23 waypoint3)
	(can_traverse rover0 waypoint3 waypoint23)
	(can_traverse rover0 waypoint23 waypoint7)
	(can_traverse rover0 waypoint7 waypoint23)
	(can_traverse rover0 waypoint23 waypoint11)
	(can_traverse rover0 waypoint11 waypoint23)
	(can_traverse rover0 waypoint0 waypoint20)
	(can_traverse rover0 waypoint20 waypoint0)
	(can_traverse rover0 waypoint4 waypoint10)
	(can_traverse rover0 waypoint10 waypoint4)
	(can_traverse rover0 waypoint4 waypoint18)
	(can_traverse rover0 waypoint18 waypoint4)
	(can_traverse rover0 waypoint8 waypoint13)
	(can_traverse rover0 waypoint13 waypoint8)
	(can_traverse rover0 waypoint8 waypoint19)
	(can_traverse rover0 waypoint19 waypoint8)
	(can_traverse rover0 waypoint8 waypoint21)
	(can_traverse rover0 waypoint21 waypoint8)
	(can_traverse rover0 waypoint8 waypoint26)
	(can_traverse rover0 waypoint26 waypoint8)
	(can_traverse rover0 waypoint16 waypoint9)
	(can_traverse rover0 waypoint9 waypoint16)
	(can_traverse rover0 waypoint17 waypoint14)
	(can_traverse rover0 waypoint14 waypoint17)
	(can_traverse rover0 waypoint24 waypoint2)
	(can_traverse rover0 waypoint2 waypoint24)
	(can_traverse rover0 waypoint24 waypoint5)
	(can_traverse rover0 waypoint5 waypoint24)
	(at rover1 waypoint22)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint22 waypoint4)
	(can_traverse rover1 waypoint4 waypoint22)
	(can_traverse rover1 waypoint22 waypoint6)
	(can_traverse rover1 waypoint6 waypoint22)
	(can_traverse rover1 waypoint22 waypoint9)
	(can_traverse rover1 waypoint9 waypoint22)
	(can_traverse rover1 waypoint22 waypoint10)
	(can_traverse rover1 waypoint10 waypoint22)
	(can_traverse rover1 waypoint22 waypoint12)
	(can_traverse rover1 waypoint12 waypoint22)
	(can_traverse rover1 waypoint22 waypoint13)
	(can_traverse rover1 waypoint13 waypoint22)
	(can_traverse rover1 waypoint4 waypoint1)
	(can_traverse rover1 waypoint1 waypoint4)
	(can_traverse rover1 waypoint4 waypoint19)
	(can_traverse rover1 waypoint19 waypoint4)
	(can_traverse rover1 waypoint4 waypoint20)
	(can_traverse rover1 waypoint20 waypoint4)
	(can_traverse rover1 waypoint4 waypoint24)
	(can_traverse rover1 waypoint24 waypoint4)
	(can_traverse rover1 waypoint6 waypoint0)
	(can_traverse rover1 waypoint0 waypoint6)
	(can_traverse rover1 waypoint6 waypoint7)
	(can_traverse rover1 waypoint7 waypoint6)
	(can_traverse rover1 waypoint6 waypoint8)
	(can_traverse rover1 waypoint8 waypoint6)
	(can_traverse rover1 waypoint6 waypoint15)
	(can_traverse rover1 waypoint15 waypoint6)
	(can_traverse rover1 waypoint6 waypoint16)
	(can_traverse rover1 waypoint16 waypoint6)
	(can_traverse rover1 waypoint6 waypoint17)
	(can_traverse rover1 waypoint17 waypoint6)
	(can_traverse rover1 waypoint6 waypoint26)
	(can_traverse rover1 waypoint26 waypoint6)
	(can_traverse rover1 waypoint9 waypoint14)
	(can_traverse rover1 waypoint14 waypoint9)
	(can_traverse rover1 waypoint9 waypoint18)
	(can_traverse rover1 waypoint18 waypoint9)
	(can_traverse rover1 waypoint1 waypoint23)
	(can_traverse rover1 waypoint23 waypoint1)
	(can_traverse rover1 waypoint1 waypoint25)
	(can_traverse rover1 waypoint25 waypoint1)
	(can_traverse rover1 waypoint19 waypoint5)
	(can_traverse rover1 waypoint5 waypoint19)
	(can_traverse rover1 waypoint24 waypoint2)
	(can_traverse rover1 waypoint2 waypoint24)
	(can_traverse rover1 waypoint24 waypoint3)
	(can_traverse rover1 waypoint3 waypoint24)
	(can_traverse rover1 waypoint24 waypoint11)
	(can_traverse rover1 waypoint11 waypoint24)
	(at rover2 waypoint17)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint17 waypoint2)
	(can_traverse rover2 waypoint2 waypoint17)
	(can_traverse rover2 waypoint17 waypoint5)
	(can_traverse rover2 waypoint5 waypoint17)
	(can_traverse rover2 waypoint17 waypoint6)
	(can_traverse rover2 waypoint6 waypoint17)
	(can_traverse rover2 waypoint17 waypoint11)
	(can_traverse rover2 waypoint11 waypoint17)
	(can_traverse rover2 waypoint17 waypoint14)
	(can_traverse rover2 waypoint14 waypoint17)
	(can_traverse rover2 waypoint17 waypoint18)
	(can_traverse rover2 waypoint18 waypoint17)
	(can_traverse rover2 waypoint17 waypoint19)
	(can_traverse rover2 waypoint19 waypoint17)
	(can_traverse rover2 waypoint17 waypoint23)
	(can_traverse rover2 waypoint23 waypoint17)
	(can_traverse rover2 waypoint17 waypoint26)
	(can_traverse rover2 waypoint26 waypoint17)
	(can_traverse rover2 waypoint2 waypoint3)
	(can_traverse rover2 waypoint3 waypoint2)
	(can_traverse rover2 waypoint2 waypoint24)
	(can_traverse rover2 waypoint24 waypoint2)
	(can_traverse rover2 waypoint2 waypoint25)
	(can_traverse rover2 waypoint25 waypoint2)
	(can_traverse rover2 waypoint5 waypoint1)
	(can_traverse rover2 waypoint1 waypoint5)
	(can_traverse rover2 waypoint5 waypoint13)
	(can_traverse rover2 waypoint13 waypoint5)
	(can_traverse rover2 waypoint6 waypoint4)
	(can_traverse rover2 waypoint4 waypoint6)
	(can_traverse rover2 waypoint6 waypoint7)
	(can_traverse rover2 waypoint7 waypoint6)
	(can_traverse rover2 waypoint6 waypoint15)
	(can_traverse rover2 waypoint15 waypoint6)
	(can_traverse rover2 waypoint6 waypoint16)
	(can_traverse rover2 waypoint16 waypoint6)
	(can_traverse rover2 waypoint11 waypoint0)
	(can_traverse rover2 waypoint0 waypoint11)
	(can_traverse rover2 waypoint14 waypoint9)
	(can_traverse rover2 waypoint9 waypoint14)
	(can_traverse rover2 waypoint14 waypoint20)
	(can_traverse rover2 waypoint20 waypoint14)
	(can_traverse rover2 waypoint18 waypoint10)
	(can_traverse rover2 waypoint10 waypoint18)
	(can_traverse rover2 waypoint19 waypoint8)
	(can_traverse rover2 waypoint8 waypoint19)
	(can_traverse rover2 waypoint3 waypoint21)
	(can_traverse rover2 waypoint21 waypoint3)
	(can_traverse rover2 waypoint24 waypoint22)
	(can_traverse rover2 waypoint22 waypoint24)
	(can_traverse rover2 waypoint25 waypoint12)
	(can_traverse rover2 waypoint12 waypoint25)
	(at rover3 waypoint21)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(can_traverse rover3 waypoint21 waypoint3)
	(can_traverse rover3 waypoint3 waypoint21)
	(can_traverse rover3 waypoint21 waypoint8)
	(can_traverse rover3 waypoint8 waypoint21)
	(can_traverse rover3 waypoint21 waypoint10)
	(can_traverse rover3 waypoint10 waypoint21)
	(can_traverse rover3 waypoint21 waypoint19)
	(can_traverse rover3 waypoint19 waypoint21)
	(can_traverse rover3 waypoint3 waypoint2)
	(can_traverse rover3 waypoint2 waypoint3)
	(can_traverse rover3 waypoint3 waypoint16)
	(can_traverse rover3 waypoint16 waypoint3)
	(can_traverse rover3 waypoint3 waypoint23)
	(can_traverse rover3 waypoint23 waypoint3)
	(can_traverse rover3 waypoint3 waypoint24)
	(can_traverse rover3 waypoint24 waypoint3)
	(can_traverse rover3 waypoint8 waypoint6)
	(can_traverse rover3 waypoint6 waypoint8)
	(can_traverse rover3 waypoint8 waypoint13)
	(can_traverse rover3 waypoint13 waypoint8)
	(can_traverse rover3 waypoint8 waypoint18)
	(can_traverse rover3 waypoint18 waypoint8)
	(can_traverse rover3 waypoint8 waypoint22)
	(can_traverse rover3 waypoint22 waypoint8)
	(can_traverse rover3 waypoint10 waypoint4)
	(can_traverse rover3 waypoint4 waypoint10)
	(can_traverse rover3 waypoint10 waypoint20)
	(can_traverse rover3 waypoint20 waypoint10)
	(can_traverse rover3 waypoint19 waypoint5)
	(can_traverse rover3 waypoint5 waypoint19)
	(can_traverse rover3 waypoint19 waypoint7)
	(can_traverse rover3 waypoint7 waypoint19)
	(can_traverse rover3 waypoint19 waypoint25)
	(can_traverse rover3 waypoint25 waypoint19)
	(can_traverse rover3 waypoint16 waypoint1)
	(can_traverse rover3 waypoint1 waypoint16)
	(can_traverse rover3 waypoint16 waypoint12)
	(can_traverse rover3 waypoint12 waypoint16)
	(can_traverse rover3 waypoint23 waypoint15)
	(can_traverse rover3 waypoint15 waypoint23)
	(can_traverse rover3 waypoint24 waypoint0)
	(can_traverse rover3 waypoint0 waypoint24)
	(can_traverse rover3 waypoint24 waypoint9)
	(can_traverse rover3 waypoint9 waypoint24)
	(can_traverse rover3 waypoint24 waypoint11)
	(can_traverse rover3 waypoint11 waypoint24)
	(can_traverse rover3 waypoint24 waypoint26)
	(can_traverse rover3 waypoint26 waypoint24)
	(can_traverse rover3 waypoint6 waypoint17)
	(can_traverse rover3 waypoint17 waypoint6)
	(at rover4 waypoint0)
	(available rover4)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_rock_analysis rover4)
	(can_traverse rover4 waypoint0 waypoint1)
	(can_traverse rover4 waypoint1 waypoint0)
	(can_traverse rover4 waypoint0 waypoint6)
	(can_traverse rover4 waypoint6 waypoint0)
	(can_traverse rover4 waypoint0 waypoint24)
	(can_traverse rover4 waypoint24 waypoint0)
	(can_traverse rover4 waypoint1 waypoint5)
	(can_traverse rover4 waypoint5 waypoint1)
	(can_traverse rover4 waypoint1 waypoint12)
	(can_traverse rover4 waypoint12 waypoint1)
	(can_traverse rover4 waypoint1 waypoint14)
	(can_traverse rover4 waypoint14 waypoint1)
	(can_traverse rover4 waypoint1 waypoint23)
	(can_traverse rover4 waypoint23 waypoint1)
	(can_traverse rover4 waypoint1 waypoint25)
	(can_traverse rover4 waypoint25 waypoint1)
	(can_traverse rover4 waypoint1 waypoint26)
	(can_traverse rover4 waypoint26 waypoint1)
	(can_traverse rover4 waypoint6 waypoint7)
	(can_traverse rover4 waypoint7 waypoint6)
	(can_traverse rover4 waypoint6 waypoint8)
	(can_traverse rover4 waypoint8 waypoint6)
	(can_traverse rover4 waypoint6 waypoint16)
	(can_traverse rover4 waypoint16 waypoint6)
	(can_traverse rover4 waypoint6 waypoint22)
	(can_traverse rover4 waypoint22 waypoint6)
	(can_traverse rover4 waypoint24 waypoint2)
	(can_traverse rover4 waypoint2 waypoint24)
	(can_traverse rover4 waypoint24 waypoint3)
	(can_traverse rover4 waypoint3 waypoint24)
	(can_traverse rover4 waypoint24 waypoint4)
	(can_traverse rover4 waypoint4 waypoint24)
	(can_traverse rover4 waypoint24 waypoint10)
	(can_traverse rover4 waypoint10 waypoint24)
	(can_traverse rover4 waypoint24 waypoint11)
	(can_traverse rover4 waypoint11 waypoint24)
	(can_traverse rover4 waypoint24 waypoint18)
	(can_traverse rover4 waypoint18 waypoint24)
	(can_traverse rover4 waypoint24 waypoint21)
	(can_traverse rover4 waypoint21 waypoint24)
	(can_traverse rover4 waypoint5 waypoint13)
	(can_traverse rover4 waypoint13 waypoint5)
	(can_traverse rover4 waypoint5 waypoint17)
	(can_traverse rover4 waypoint17 waypoint5)
	(can_traverse rover4 waypoint5 waypoint19)
	(can_traverse rover4 waypoint19 waypoint5)
	(can_traverse rover4 waypoint12 waypoint15)
	(can_traverse rover4 waypoint15 waypoint12)
	(can_traverse rover4 waypoint14 waypoint20)
	(can_traverse rover4 waypoint20 waypoint14)
	(can_traverse rover4 waypoint7 waypoint9)
	(can_traverse rover4 waypoint9 waypoint7)
	(at rover5 waypoint16)
	(available rover5)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_imaging rover5)
	(can_traverse rover5 waypoint16 waypoint1)
	(can_traverse rover5 waypoint1 waypoint16)
	(can_traverse rover5 waypoint16 waypoint3)
	(can_traverse rover5 waypoint3 waypoint16)
	(can_traverse rover5 waypoint16 waypoint4)
	(can_traverse rover5 waypoint4 waypoint16)
	(can_traverse rover5 waypoint16 waypoint6)
	(can_traverse rover5 waypoint6 waypoint16)
	(can_traverse rover5 waypoint16 waypoint20)
	(can_traverse rover5 waypoint20 waypoint16)
	(can_traverse rover5 waypoint1 waypoint5)
	(can_traverse rover5 waypoint5 waypoint1)
	(can_traverse rover5 waypoint1 waypoint12)
	(can_traverse rover5 waypoint12 waypoint1)
	(can_traverse rover5 waypoint1 waypoint14)
	(can_traverse rover5 waypoint14 waypoint1)
	(can_traverse rover5 waypoint1 waypoint26)
	(can_traverse rover5 waypoint26 waypoint1)
	(can_traverse rover5 waypoint3 waypoint19)
	(can_traverse rover5 waypoint19 waypoint3)
	(can_traverse rover5 waypoint3 waypoint21)
	(can_traverse rover5 waypoint21 waypoint3)
	(can_traverse rover5 waypoint3 waypoint24)
	(can_traverse rover5 waypoint24 waypoint3)
	(can_traverse rover5 waypoint4 waypoint9)
	(can_traverse rover5 waypoint9 waypoint4)
	(can_traverse rover5 waypoint4 waypoint10)
	(can_traverse rover5 waypoint10 waypoint4)
	(can_traverse rover5 waypoint4 waypoint18)
	(can_traverse rover5 waypoint18 waypoint4)
	(can_traverse rover5 waypoint4 waypoint22)
	(can_traverse rover5 waypoint22 waypoint4)
	(can_traverse rover5 waypoint6 waypoint0)
	(can_traverse rover5 waypoint0 waypoint6)
	(can_traverse rover5 waypoint6 waypoint15)
	(can_traverse rover5 waypoint15 waypoint6)
	(can_traverse rover5 waypoint6 waypoint17)
	(can_traverse rover5 waypoint17 waypoint6)
	(can_traverse rover5 waypoint20 waypoint7)
	(can_traverse rover5 waypoint7 waypoint20)
	(can_traverse rover5 waypoint20 waypoint13)
	(can_traverse rover5 waypoint13 waypoint20)
	(can_traverse rover5 waypoint14 waypoint2)
	(can_traverse rover5 waypoint2 waypoint14)
	(can_traverse rover5 waypoint26 waypoint8)
	(can_traverse rover5 waypoint8 waypoint26)
	(can_traverse rover5 waypoint26 waypoint25)
	(can_traverse rover5 waypoint25 waypoint26)
	(can_traverse rover5 waypoint24 waypoint11)
	(can_traverse rover5 waypoint11 waypoint24)
	(can_traverse rover5 waypoint22 waypoint23)
	(can_traverse rover5 waypoint23 waypoint22)
	(on_board camera0 rover1)
	(calibration_target camera0 objective2)
	(supports camera0 colour)
	(on_board camera1 rover5)
	(calibration_target camera1 objective1)
	(supports camera1 low_res)
	(on_board camera2 rover5)
	(calibration_target camera2 objective1)
	(supports camera2 high_res)
	(on_board camera3 rover2)
	(calibration_target camera3 objective2)
	(supports camera3 colour)
	(supports camera3 high_res)
	(on_board camera4 rover3)
	(calibration_target camera4 objective1)
	(supports camera4 colour)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint4)
	(visible_from objective0 waypoint7)
	(visible_from objective0 waypoint8)
	(visible_from objective0 waypoint11)
	(visible_from objective0 waypoint12)
	(visible_from objective0 waypoint13)
	(visible_from objective0 waypoint14)
	(visible_from objective0 waypoint15)
	(visible_from objective0 waypoint16)
	(visible_from objective0 waypoint17)
	(visible_from objective0 waypoint18)
	(visible_from objective0 waypoint20)
	(visible_from objective0 waypoint21)
	(visible_from objective0 waypoint22)
	(visible_from objective0 waypoint23)
	(visible_from objective1 waypoint0)
	(visible_from objective1 waypoint1)
	(visible_from objective1 waypoint3)
	(visible_from objective1 waypoint6)
	(visible_from objective1 waypoint10)
	(visible_from objective1 waypoint11)
	(visible_from objective1 waypoint12)
	(visible_from objective1 waypoint13)
	(visible_from objective1 waypoint17)
	(visible_from objective1 waypoint19)
	(visible_from objective1 waypoint21)
	(visible_from objective2 waypoint1)
	(visible_from objective2 waypoint2)
	(visible_from objective2 waypoint5)
	(visible_from objective2 waypoint6)
	(visible_from objective2 waypoint11)
	(visible_from objective2 waypoint12)
	(visible_from objective2 waypoint15)
	(visible_from objective2 waypoint16)
	(visible_from objective2 waypoint17)
	(visible_from objective2 waypoint19)
	(visible_from objective2 waypoint21)
	(visible_from objective2 waypoint24)
	(visible_from objective2 waypoint26)
)

(:goal (and
(communicated_soil_data waypoint7)
(communicated_rock_data waypoint7)
(communicated_image_data objective1 colour)
	)
)
)
