(define (problem roverprob1) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 - Waypoint
	camera0 camera1 camera2 camera3 camera4 - Camera
	objective0 objective1 objective2 - Objective
	)
(:init
	(visible waypoint0 waypoint8)
	(visible waypoint8 waypoint0)
	(visible waypoint0 waypoint33)
	(visible waypoint33 waypoint0)
	(visible waypoint1 waypoint5)
	(visible waypoint5 waypoint1)
	(visible waypoint1 waypoint18)
	(visible waypoint18 waypoint1)
	(visible waypoint1 waypoint26)
	(visible waypoint26 waypoint1)
	(visible waypoint2 waypoint0)
	(visible waypoint0 waypoint2)
	(visible waypoint2 waypoint7)
	(visible waypoint7 waypoint2)
	(visible waypoint2 waypoint22)
	(visible waypoint22 waypoint2)
	(visible waypoint2 waypoint34)
	(visible waypoint34 waypoint2)
	(visible waypoint3 waypoint23)
	(visible waypoint23 waypoint3)
	(visible waypoint4 waypoint3)
	(visible waypoint3 waypoint4)
	(visible waypoint4 waypoint12)
	(visible waypoint12 waypoint4)
	(visible waypoint4 waypoint13)
	(visible waypoint13 waypoint4)
	(visible waypoint4 waypoint24)
	(visible waypoint24 waypoint4)
	(visible waypoint4 waypoint28)
	(visible waypoint28 waypoint4)
	(visible waypoint5 waypoint2)
	(visible waypoint2 waypoint5)
	(visible waypoint5 waypoint9)
	(visible waypoint9 waypoint5)
	(visible waypoint5 waypoint14)
	(visible waypoint14 waypoint5)
	(visible waypoint5 waypoint21)
	(visible waypoint21 waypoint5)
	(visible waypoint5 waypoint26)
	(visible waypoint26 waypoint5)
	(visible waypoint5 waypoint29)
	(visible waypoint29 waypoint5)
	(visible waypoint5 waypoint31)
	(visible waypoint31 waypoint5)
	(visible waypoint6 waypoint7)
	(visible waypoint7 waypoint6)
	(visible waypoint6 waypoint8)
	(visible waypoint8 waypoint6)
	(visible waypoint6 waypoint9)
	(visible waypoint9 waypoint6)
	(visible waypoint6 waypoint15)
	(visible waypoint15 waypoint6)
	(visible waypoint6 waypoint23)
	(visible waypoint23 waypoint6)
	(visible waypoint6 waypoint24)
	(visible waypoint24 waypoint6)
	(visible waypoint6 waypoint32)
	(visible waypoint32 waypoint6)
	(visible waypoint8 waypoint32)
	(visible waypoint32 waypoint8)
	(visible waypoint8 waypoint34)
	(visible waypoint34 waypoint8)
	(visible waypoint9 waypoint19)
	(visible waypoint19 waypoint9)
	(visible waypoint9 waypoint31)
	(visible waypoint31 waypoint9)
	(visible waypoint10 waypoint8)
	(visible waypoint8 waypoint10)
	(visible waypoint10 waypoint12)
	(visible waypoint12 waypoint10)
	(visible waypoint10 waypoint19)
	(visible waypoint19 waypoint10)
	(visible waypoint10 waypoint26)
	(visible waypoint26 waypoint10)
	(visible waypoint10 waypoint27)
	(visible waypoint27 waypoint10)
	(visible waypoint10 waypoint32)
	(visible waypoint32 waypoint10)
	(visible waypoint10 waypoint35)
	(visible waypoint35 waypoint10)
	(visible waypoint11 waypoint3)
	(visible waypoint3 waypoint11)
	(visible waypoint11 waypoint6)
	(visible waypoint6 waypoint11)
	(visible waypoint11 waypoint8)
	(visible waypoint8 waypoint11)
	(visible waypoint11 waypoint33)
	(visible waypoint33 waypoint11)
	(visible waypoint12 waypoint6)
	(visible waypoint6 waypoint12)
	(visible waypoint12 waypoint19)
	(visible waypoint19 waypoint12)
	(visible waypoint12 waypoint21)
	(visible waypoint21 waypoint12)
	(visible waypoint12 waypoint24)
	(visible waypoint24 waypoint12)
	(visible waypoint12 waypoint27)
	(visible waypoint27 waypoint12)
	(visible waypoint12 waypoint30)
	(visible waypoint30 waypoint12)
	(visible waypoint13 waypoint10)
	(visible waypoint10 waypoint13)
	(visible waypoint13 waypoint18)
	(visible waypoint18 waypoint13)
	(visible waypoint13 waypoint27)
	(visible waypoint27 waypoint13)
	(visible waypoint14 waypoint23)
	(visible waypoint23 waypoint14)
	(visible waypoint14 waypoint25)
	(visible waypoint25 waypoint14)
	(visible waypoint14 waypoint29)
	(visible waypoint29 waypoint14)
	(visible waypoint14 waypoint32)
	(visible waypoint32 waypoint14)
	(visible waypoint15 waypoint0)
	(visible waypoint0 waypoint15)
	(visible waypoint15 waypoint31)
	(visible waypoint31 waypoint15)
	(visible waypoint15 waypoint33)
	(visible waypoint33 waypoint15)
	(visible waypoint16 waypoint2)
	(visible waypoint2 waypoint16)
	(visible waypoint16 waypoint8)
	(visible waypoint8 waypoint16)
	(visible waypoint16 waypoint21)
	(visible waypoint21 waypoint16)
	(visible waypoint16 waypoint29)
	(visible waypoint29 waypoint16)
	(visible waypoint16 waypoint30)
	(visible waypoint30 waypoint16)
	(visible waypoint17 waypoint4)
	(visible waypoint4 waypoint17)
	(visible waypoint17 waypoint5)
	(visible waypoint5 waypoint17)
	(visible waypoint17 waypoint7)
	(visible waypoint7 waypoint17)
	(visible waypoint17 waypoint10)
	(visible waypoint10 waypoint17)
	(visible waypoint17 waypoint12)
	(visible waypoint12 waypoint17)
	(visible waypoint17 waypoint20)
	(visible waypoint20 waypoint17)
	(visible waypoint17 waypoint22)
	(visible waypoint22 waypoint17)
	(visible waypoint17 waypoint27)
	(visible waypoint27 waypoint17)
	(visible waypoint17 waypoint35)
	(visible waypoint35 waypoint17)
	(visible waypoint18 waypoint2)
	(visible waypoint2 waypoint18)
	(visible waypoint18 waypoint3)
	(visible waypoint3 waypoint18)
	(visible waypoint18 waypoint7)
	(visible waypoint7 waypoint18)
	(visible waypoint18 waypoint24)
	(visible waypoint24 waypoint18)
	(visible waypoint18 waypoint27)
	(visible waypoint27 waypoint18)
	(visible waypoint18 waypoint30)
	(visible waypoint30 waypoint18)
	(visible waypoint18 waypoint34)
	(visible waypoint34 waypoint18)
	(visible waypoint19 waypoint1)
	(visible waypoint1 waypoint19)
	(visible waypoint19 waypoint3)
	(visible waypoint3 waypoint19)
	(visible waypoint19 waypoint27)
	(visible waypoint27 waypoint19)
	(visible waypoint20 waypoint14)
	(visible waypoint14 waypoint20)
	(visible waypoint20 waypoint16)
	(visible waypoint16 waypoint20)
	(visible waypoint20 waypoint21)
	(visible waypoint21 waypoint20)
	(visible waypoint20 waypoint27)
	(visible waypoint27 waypoint20)
	(visible waypoint20 waypoint31)
	(visible waypoint31 waypoint20)
	(visible waypoint21 waypoint6)
	(visible waypoint6 waypoint21)
	(visible waypoint21 waypoint8)
	(visible waypoint8 waypoint21)
	(visible waypoint21 waypoint9)
	(visible waypoint9 waypoint21)
	(visible waypoint21 waypoint17)
	(visible waypoint17 waypoint21)
	(visible waypoint21 waypoint22)
	(visible waypoint22 waypoint21)
	(visible waypoint22 waypoint1)
	(visible waypoint1 waypoint22)
	(visible waypoint22 waypoint8)
	(visible waypoint8 waypoint22)
	(visible waypoint22 waypoint10)
	(visible waypoint10 waypoint22)
	(visible waypoint22 waypoint18)
	(visible waypoint18 waypoint22)
	(visible waypoint22 waypoint25)
	(visible waypoint25 waypoint22)
	(visible waypoint23 waypoint8)
	(visible waypoint8 waypoint23)
	(visible waypoint23 waypoint9)
	(visible waypoint9 waypoint23)
	(visible waypoint23 waypoint10)
	(visible waypoint10 waypoint23)
	(visible waypoint23 waypoint12)
	(visible waypoint12 waypoint23)
	(visible waypoint23 waypoint15)
	(visible waypoint15 waypoint23)
	(visible waypoint23 waypoint27)
	(visible waypoint27 waypoint23)
	(visible waypoint23 waypoint30)
	(visible waypoint30 waypoint23)
	(visible waypoint23 waypoint34)
	(visible waypoint34 waypoint23)
	(visible waypoint24 waypoint3)
	(visible waypoint3 waypoint24)
	(visible waypoint24 waypoint5)
	(visible waypoint5 waypoint24)
	(visible waypoint24 waypoint13)
	(visible waypoint13 waypoint24)
	(visible waypoint24 waypoint17)
	(visible waypoint17 waypoint24)
	(visible waypoint24 waypoint22)
	(visible waypoint22 waypoint24)
	(visible waypoint24 waypoint32)
	(visible waypoint32 waypoint24)
	(visible waypoint25 waypoint4)
	(visible waypoint4 waypoint25)
	(visible waypoint25 waypoint6)
	(visible waypoint6 waypoint25)
	(visible waypoint25 waypoint11)
	(visible waypoint11 waypoint25)
	(visible waypoint26 waypoint7)
	(visible waypoint7 waypoint26)
	(visible waypoint26 waypoint11)
	(visible waypoint11 waypoint26)
	(visible waypoint26 waypoint13)
	(visible waypoint13 waypoint26)
	(visible waypoint26 waypoint22)
	(visible waypoint22 waypoint26)
	(visible waypoint27 waypoint25)
	(visible waypoint25 waypoint27)
	(visible waypoint28 waypoint11)
	(visible waypoint11 waypoint28)
	(visible waypoint28 waypoint19)
	(visible waypoint19 waypoint28)
	(visible waypoint28 waypoint26)
	(visible waypoint26 waypoint28)
	(visible waypoint29 waypoint8)
	(visible waypoint8 waypoint29)
	(visible waypoint29 waypoint11)
	(visible waypoint11 waypoint29)
	(visible waypoint29 waypoint33)
	(visible waypoint33 waypoint29)
	(visible waypoint30 waypoint14)
	(visible waypoint14 waypoint30)
	(visible waypoint30 waypoint26)
	(visible waypoint26 waypoint30)
	(visible waypoint30 waypoint29)
	(visible waypoint29 waypoint30)
	(visible waypoint31 waypoint2)
	(visible waypoint2 waypoint31)
	(visible waypoint31 waypoint7)
	(visible waypoint7 waypoint31)
	(visible waypoint31 waypoint17)
	(visible waypoint17 waypoint31)
	(visible waypoint31 waypoint22)
	(visible waypoint22 waypoint31)
	(visible waypoint31 waypoint29)
	(visible waypoint29 waypoint31)
	(visible waypoint32 waypoint2)
	(visible waypoint2 waypoint32)
	(visible waypoint32 waypoint4)
	(visible waypoint4 waypoint32)
	(visible waypoint32 waypoint7)
	(visible waypoint7 waypoint32)
	(visible waypoint32 waypoint12)
	(visible waypoint12 waypoint32)
	(visible waypoint32 waypoint22)
	(visible waypoint22 waypoint32)
	(visible waypoint32 waypoint29)
	(visible waypoint29 waypoint32)
	(visible waypoint32 waypoint30)
	(visible waypoint30 waypoint32)
	(visible waypoint32 waypoint31)
	(visible waypoint31 waypoint32)
	(visible waypoint32 waypoint35)
	(visible waypoint35 waypoint32)
	(visible waypoint33 waypoint16)
	(visible waypoint16 waypoint33)
	(visible waypoint33 waypoint24)
	(visible waypoint24 waypoint33)
	(visible waypoint33 waypoint25)
	(visible waypoint25 waypoint33)
	(visible waypoint33 waypoint32)
	(visible waypoint32 waypoint33)
	(visible waypoint34 waypoint21)
	(visible waypoint21 waypoint34)
	(visible waypoint34 waypoint32)
	(visible waypoint32 waypoint34)
	(visible waypoint34 waypoint33)
	(visible waypoint33 waypoint34)
	(visible waypoint35 waypoint0)
	(visible waypoint0 waypoint35)
	(visible waypoint35 waypoint1)
	(visible waypoint1 waypoint35)
	(visible waypoint35 waypoint7)
	(visible waypoint7 waypoint35)
	(visible waypoint35 waypoint26)
	(visible waypoint26 waypoint35)
	(visible waypoint35 waypoint33)
	(visible waypoint33 waypoint35)
	(at_rock_sample waypoint2)
	(at_rock_sample waypoint3)
	(at_rock_sample waypoint5)
	(at_soil_sample waypoint6)
	(at_soil_sample waypoint7)
	(at_rock_sample waypoint7)
	(at_soil_sample waypoint8)
	(at_rock_sample waypoint8)
	(at_rock_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_rock_sample waypoint12)
	(at_soil_sample waypoint15)
	(at_rock_sample waypoint16)
	(at_soil_sample waypoint18)
	(at_soil_sample waypoint19)
	(at_rock_sample waypoint19)
	(at_soil_sample waypoint23)
	(at_soil_sample waypoint24)
	(at_rock_sample waypoint24)
	(at_soil_sample waypoint28)
	(at_soil_sample waypoint30)
	(at_soil_sample waypoint31)
	(at_rock_sample waypoint31)
	(at_soil_sample waypoint32)
	(at_rock_sample waypoint32)
	(at_soil_sample waypoint33)
	(at_rock_sample waypoint33)
	(at_soil_sample waypoint34)
	(at_soil_sample waypoint35)
	(at_rock_sample waypoint35)
	(at_lander general waypoint15)
	(channel_free general)
	(at rover0 waypoint29)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint29 waypoint5)
	(can_traverse rover0 waypoint5 waypoint29)
	(can_traverse rover0 waypoint29 waypoint8)
	(can_traverse rover0 waypoint8 waypoint29)
	(can_traverse rover0 waypoint29 waypoint11)
	(can_traverse rover0 waypoint11 waypoint29)
	(can_traverse rover0 waypoint29 waypoint14)
	(can_traverse rover0 waypoint14 waypoint29)
	(can_traverse rover0 waypoint29 waypoint16)
	(can_traverse rover0 waypoint16 waypoint29)
	(can_traverse rover0 waypoint29 waypoint31)
	(can_traverse rover0 waypoint31 waypoint29)
	(can_traverse rover0 waypoint29 waypoint33)
	(can_traverse rover0 waypoint33 waypoint29)
	(can_traverse rover0 waypoint5 waypoint1)
	(can_traverse rover0 waypoint1 waypoint5)
	(can_traverse rover0 waypoint5 waypoint17)
	(can_traverse rover0 waypoint17 waypoint5)
	(can_traverse rover0 waypoint5 waypoint21)
	(can_traverse rover0 waypoint21 waypoint5)
	(can_traverse rover0 waypoint5 waypoint26)
	(can_traverse rover0 waypoint26 waypoint5)
	(can_traverse rover0 waypoint8 waypoint0)
	(can_traverse rover0 waypoint0 waypoint8)
	(can_traverse rover0 waypoint8 waypoint6)
	(can_traverse rover0 waypoint6 waypoint8)
	(can_traverse rover0 waypoint8 waypoint22)
	(can_traverse rover0 waypoint22 waypoint8)
	(can_traverse rover0 waypoint8 waypoint23)
	(can_traverse rover0 waypoint23 waypoint8)
	(can_traverse rover0 waypoint11 waypoint3)
	(can_traverse rover0 waypoint3 waypoint11)
	(can_traverse rover0 waypoint11 waypoint25)
	(can_traverse rover0 waypoint25 waypoint11)
	(can_traverse rover0 waypoint11 waypoint28)
	(can_traverse rover0 waypoint28 waypoint11)
	(can_traverse rover0 waypoint14 waypoint20)
	(can_traverse rover0 waypoint20 waypoint14)
	(can_traverse rover0 waypoint16 waypoint30)
	(can_traverse rover0 waypoint30 waypoint16)
	(can_traverse rover0 waypoint31 waypoint2)
	(can_traverse rover0 waypoint2 waypoint31)
	(can_traverse rover0 waypoint31 waypoint7)
	(can_traverse rover0 waypoint7 waypoint31)
	(can_traverse rover0 waypoint31 waypoint9)
	(can_traverse rover0 waypoint9 waypoint31)
	(can_traverse rover0 waypoint31 waypoint32)
	(can_traverse rover0 waypoint32 waypoint31)
	(can_traverse rover0 waypoint33 waypoint15)
	(can_traverse rover0 waypoint15 waypoint33)
	(can_traverse rover0 waypoint33 waypoint24)
	(can_traverse rover0 waypoint24 waypoint33)
	(can_traverse rover0 waypoint33 waypoint34)
	(can_traverse rover0 waypoint34 waypoint33)
	(can_traverse rover0 waypoint33 waypoint35)
	(can_traverse rover0 waypoint35 waypoint33)
	(can_traverse rover0 waypoint1 waypoint18)
	(can_traverse rover0 waypoint18 waypoint1)
	(can_traverse rover0 waypoint1 waypoint19)
	(can_traverse rover0 waypoint19 waypoint1)
	(can_traverse rover0 waypoint17 waypoint4)
	(can_traverse rover0 waypoint4 waypoint17)
	(can_traverse rover0 waypoint17 waypoint12)
	(can_traverse rover0 waypoint12 waypoint17)
	(can_traverse rover0 waypoint17 waypoint27)
	(can_traverse rover0 waypoint27 waypoint17)
	(can_traverse rover0 waypoint26 waypoint10)
	(can_traverse rover0 waypoint10 waypoint26)
	(can_traverse rover0 waypoint26 waypoint13)
	(can_traverse rover0 waypoint13 waypoint26)
	(at rover1 waypoint8)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint8 waypoint0)
	(can_traverse rover1 waypoint0 waypoint8)
	(can_traverse rover1 waypoint8 waypoint10)
	(can_traverse rover1 waypoint10 waypoint8)
	(can_traverse rover1 waypoint8 waypoint16)
	(can_traverse rover1 waypoint16 waypoint8)
	(can_traverse rover1 waypoint8 waypoint22)
	(can_traverse rover1 waypoint22 waypoint8)
	(can_traverse rover1 waypoint8 waypoint23)
	(can_traverse rover1 waypoint23 waypoint8)
	(can_traverse rover1 waypoint8 waypoint29)
	(can_traverse rover1 waypoint29 waypoint8)
	(can_traverse rover1 waypoint8 waypoint32)
	(can_traverse rover1 waypoint32 waypoint8)
	(can_traverse rover1 waypoint8 waypoint34)
	(can_traverse rover1 waypoint34 waypoint8)
	(can_traverse rover1 waypoint0 waypoint33)
	(can_traverse rover1 waypoint33 waypoint0)
	(can_traverse rover1 waypoint0 waypoint35)
	(can_traverse rover1 waypoint35 waypoint0)
	(can_traverse rover1 waypoint10 waypoint12)
	(can_traverse rover1 waypoint12 waypoint10)
	(can_traverse rover1 waypoint10 waypoint13)
	(can_traverse rover1 waypoint13 waypoint10)
	(can_traverse rover1 waypoint10 waypoint26)
	(can_traverse rover1 waypoint26 waypoint10)
	(can_traverse rover1 waypoint16 waypoint2)
	(can_traverse rover1 waypoint2 waypoint16)
	(can_traverse rover1 waypoint16 waypoint20)
	(can_traverse rover1 waypoint20 waypoint16)
	(can_traverse rover1 waypoint16 waypoint21)
	(can_traverse rover1 waypoint21 waypoint16)
	(can_traverse rover1 waypoint22 waypoint1)
	(can_traverse rover1 waypoint1 waypoint22)
	(can_traverse rover1 waypoint22 waypoint17)
	(can_traverse rover1 waypoint17 waypoint22)
	(can_traverse rover1 waypoint22 waypoint18)
	(can_traverse rover1 waypoint18 waypoint22)
	(can_traverse rover1 waypoint22 waypoint25)
	(can_traverse rover1 waypoint25 waypoint22)
	(can_traverse rover1 waypoint22 waypoint31)
	(can_traverse rover1 waypoint31 waypoint22)
	(can_traverse rover1 waypoint23 waypoint6)
	(can_traverse rover1 waypoint6 waypoint23)
	(can_traverse rover1 waypoint23 waypoint14)
	(can_traverse rover1 waypoint14 waypoint23)
	(can_traverse rover1 waypoint23 waypoint15)
	(can_traverse rover1 waypoint15 waypoint23)
	(can_traverse rover1 waypoint23 waypoint27)
	(can_traverse rover1 waypoint27 waypoint23)
	(can_traverse rover1 waypoint23 waypoint30)
	(can_traverse rover1 waypoint30 waypoint23)
	(can_traverse rover1 waypoint29 waypoint11)
	(can_traverse rover1 waypoint11 waypoint29)
	(can_traverse rover1 waypoint32 waypoint4)
	(can_traverse rover1 waypoint4 waypoint32)
	(can_traverse rover1 waypoint32 waypoint7)
	(can_traverse rover1 waypoint7 waypoint32)
	(can_traverse rover1 waypoint32 waypoint24)
	(can_traverse rover1 waypoint24 waypoint32)
	(can_traverse rover1 waypoint12 waypoint19)
	(can_traverse rover1 waypoint19 waypoint12)
	(can_traverse rover1 waypoint26 waypoint5)
	(can_traverse rover1 waypoint5 waypoint26)
	(can_traverse rover1 waypoint26 waypoint28)
	(can_traverse rover1 waypoint28 waypoint26)
	(at rover2 waypoint23)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint23 waypoint3)
	(can_traverse rover2 waypoint3 waypoint23)
	(can_traverse rover2 waypoint23 waypoint6)
	(can_traverse rover2 waypoint6 waypoint23)
	(can_traverse rover2 waypoint23 waypoint8)
	(can_traverse rover2 waypoint8 waypoint23)
	(can_traverse rover2 waypoint23 waypoint9)
	(can_traverse rover2 waypoint9 waypoint23)
	(can_traverse rover2 waypoint23 waypoint10)
	(can_traverse rover2 waypoint10 waypoint23)
	(can_traverse rover2 waypoint23 waypoint12)
	(can_traverse rover2 waypoint12 waypoint23)
	(can_traverse rover2 waypoint23 waypoint14)
	(can_traverse rover2 waypoint14 waypoint23)
	(can_traverse rover2 waypoint23 waypoint15)
	(can_traverse rover2 waypoint15 waypoint23)
	(can_traverse rover2 waypoint3 waypoint4)
	(can_traverse rover2 waypoint4 waypoint3)
	(can_traverse rover2 waypoint3 waypoint18)
	(can_traverse rover2 waypoint18 waypoint3)
	(can_traverse rover2 waypoint3 waypoint19)
	(can_traverse rover2 waypoint19 waypoint3)
	(can_traverse rover2 waypoint3 waypoint24)
	(can_traverse rover2 waypoint24 waypoint3)
	(can_traverse rover2 waypoint6 waypoint21)
	(can_traverse rover2 waypoint21 waypoint6)
	(can_traverse rover2 waypoint6 waypoint32)
	(can_traverse rover2 waypoint32 waypoint6)
	(can_traverse rover2 waypoint8 waypoint0)
	(can_traverse rover2 waypoint0 waypoint8)
	(can_traverse rover2 waypoint8 waypoint16)
	(can_traverse rover2 waypoint16 waypoint8)
	(can_traverse rover2 waypoint8 waypoint22)
	(can_traverse rover2 waypoint22 waypoint8)
	(can_traverse rover2 waypoint8 waypoint29)
	(can_traverse rover2 waypoint29 waypoint8)
	(can_traverse rover2 waypoint8 waypoint34)
	(can_traverse rover2 waypoint34 waypoint8)
	(can_traverse rover2 waypoint9 waypoint5)
	(can_traverse rover2 waypoint5 waypoint9)
	(can_traverse rover2 waypoint9 waypoint31)
	(can_traverse rover2 waypoint31 waypoint9)
	(can_traverse rover2 waypoint10 waypoint26)
	(can_traverse rover2 waypoint26 waypoint10)
	(can_traverse rover2 waypoint10 waypoint27)
	(can_traverse rover2 waypoint27 waypoint10)
	(can_traverse rover2 waypoint10 waypoint35)
	(can_traverse rover2 waypoint35 waypoint10)
	(can_traverse rover2 waypoint12 waypoint17)
	(can_traverse rover2 waypoint17 waypoint12)
	(can_traverse rover2 waypoint14 waypoint20)
	(can_traverse rover2 waypoint20 waypoint14)
	(can_traverse rover2 waypoint14 waypoint25)
	(can_traverse rover2 waypoint25 waypoint14)
	(can_traverse rover2 waypoint14 waypoint30)
	(can_traverse rover2 waypoint30 waypoint14)
	(can_traverse rover2 waypoint15 waypoint33)
	(can_traverse rover2 waypoint33 waypoint15)
	(can_traverse rover2 waypoint4 waypoint13)
	(can_traverse rover2 waypoint13 waypoint4)
	(can_traverse rover2 waypoint4 waypoint28)
	(can_traverse rover2 waypoint28 waypoint4)
	(can_traverse rover2 waypoint18 waypoint2)
	(can_traverse rover2 waypoint2 waypoint18)
	(can_traverse rover2 waypoint18 waypoint7)
	(can_traverse rover2 waypoint7 waypoint18)
	(can_traverse rover2 waypoint19 waypoint1)
	(can_traverse rover2 waypoint1 waypoint19)
	(can_traverse rover2 waypoint29 waypoint11)
	(can_traverse rover2 waypoint11 waypoint29)
	(at rover3 waypoint19)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(can_traverse rover3 waypoint19 waypoint1)
	(can_traverse rover3 waypoint1 waypoint19)
	(can_traverse rover3 waypoint19 waypoint3)
	(can_traverse rover3 waypoint3 waypoint19)
	(can_traverse rover3 waypoint19 waypoint9)
	(can_traverse rover3 waypoint9 waypoint19)
	(can_traverse rover3 waypoint19 waypoint10)
	(can_traverse rover3 waypoint10 waypoint19)
	(can_traverse rover3 waypoint19 waypoint12)
	(can_traverse rover3 waypoint12 waypoint19)
	(can_traverse rover3 waypoint19 waypoint27)
	(can_traverse rover3 waypoint27 waypoint19)
	(can_traverse rover3 waypoint19 waypoint28)
	(can_traverse rover3 waypoint28 waypoint19)
	(can_traverse rover3 waypoint1 waypoint5)
	(can_traverse rover3 waypoint5 waypoint1)
	(can_traverse rover3 waypoint1 waypoint18)
	(can_traverse rover3 waypoint18 waypoint1)
	(can_traverse rover3 waypoint1 waypoint22)
	(can_traverse rover3 waypoint22 waypoint1)
	(can_traverse rover3 waypoint1 waypoint26)
	(can_traverse rover3 waypoint26 waypoint1)
	(can_traverse rover3 waypoint3 waypoint4)
	(can_traverse rover3 waypoint4 waypoint3)
	(can_traverse rover3 waypoint3 waypoint11)
	(can_traverse rover3 waypoint11 waypoint3)
	(can_traverse rover3 waypoint3 waypoint24)
	(can_traverse rover3 waypoint24 waypoint3)
	(can_traverse rover3 waypoint9 waypoint6)
	(can_traverse rover3 waypoint6 waypoint9)
	(can_traverse rover3 waypoint9 waypoint21)
	(can_traverse rover3 waypoint21 waypoint9)
	(can_traverse rover3 waypoint9 waypoint23)
	(can_traverse rover3 waypoint23 waypoint9)
	(can_traverse rover3 waypoint9 waypoint31)
	(can_traverse rover3 waypoint31 waypoint9)
	(can_traverse rover3 waypoint10 waypoint8)
	(can_traverse rover3 waypoint8 waypoint10)
	(can_traverse rover3 waypoint10 waypoint13)
	(can_traverse rover3 waypoint13 waypoint10)
	(can_traverse rover3 waypoint10 waypoint17)
	(can_traverse rover3 waypoint17 waypoint10)
	(can_traverse rover3 waypoint10 waypoint32)
	(can_traverse rover3 waypoint32 waypoint10)
	(can_traverse rover3 waypoint12 waypoint30)
	(can_traverse rover3 waypoint30 waypoint12)
	(can_traverse rover3 waypoint27 waypoint25)
	(can_traverse rover3 waypoint25 waypoint27)
	(can_traverse rover3 waypoint5 waypoint2)
	(can_traverse rover3 waypoint2 waypoint5)
	(can_traverse rover3 waypoint5 waypoint14)
	(can_traverse rover3 waypoint14 waypoint5)
	(can_traverse rover3 waypoint5 waypoint29)
	(can_traverse rover3 waypoint29 waypoint5)
	(can_traverse rover3 waypoint18 waypoint34)
	(can_traverse rover3 waypoint34 waypoint18)
	(can_traverse rover3 waypoint26 waypoint7)
	(can_traverse rover3 waypoint7 waypoint26)
	(can_traverse rover3 waypoint11 waypoint33)
	(can_traverse rover3 waypoint33 waypoint11)
	(can_traverse rover3 waypoint6 waypoint15)
	(can_traverse rover3 waypoint15 waypoint6)
	(can_traverse rover3 waypoint21 waypoint16)
	(can_traverse rover3 waypoint16 waypoint21)
	(can_traverse rover3 waypoint21 waypoint20)
	(can_traverse rover3 waypoint20 waypoint21)
	(can_traverse rover3 waypoint17 waypoint35)
	(can_traverse rover3 waypoint35 waypoint17)
	(can_traverse rover3 waypoint33 waypoint0)
	(can_traverse rover3 waypoint0 waypoint33)
	(at rover4 waypoint0)
	(available rover4)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_soil_analysis rover4)
	(equipped_for_rock_analysis rover4)
	(can_traverse rover4 waypoint0 waypoint2)
	(can_traverse rover4 waypoint2 waypoint0)
	(can_traverse rover4 waypoint0 waypoint8)
	(can_traverse rover4 waypoint8 waypoint0)
	(can_traverse rover4 waypoint0 waypoint15)
	(can_traverse rover4 waypoint15 waypoint0)
	(can_traverse rover4 waypoint0 waypoint33)
	(can_traverse rover4 waypoint33 waypoint0)
	(can_traverse rover4 waypoint2 waypoint7)
	(can_traverse rover4 waypoint7 waypoint2)
	(can_traverse rover4 waypoint2 waypoint16)
	(can_traverse rover4 waypoint16 waypoint2)
	(can_traverse rover4 waypoint2 waypoint31)
	(can_traverse rover4 waypoint31 waypoint2)
	(can_traverse rover4 waypoint2 waypoint32)
	(can_traverse rover4 waypoint32 waypoint2)
	(can_traverse rover4 waypoint2 waypoint34)
	(can_traverse rover4 waypoint34 waypoint2)
	(can_traverse rover4 waypoint8 waypoint6)
	(can_traverse rover4 waypoint6 waypoint8)
	(can_traverse rover4 waypoint8 waypoint10)
	(can_traverse rover4 waypoint10 waypoint8)
	(can_traverse rover4 waypoint8 waypoint11)
	(can_traverse rover4 waypoint11 waypoint8)
	(can_traverse rover4 waypoint8 waypoint21)
	(can_traverse rover4 waypoint21 waypoint8)
	(can_traverse rover4 waypoint8 waypoint22)
	(can_traverse rover4 waypoint22 waypoint8)
	(can_traverse rover4 waypoint8 waypoint23)
	(can_traverse rover4 waypoint23 waypoint8)
	(can_traverse rover4 waypoint8 waypoint29)
	(can_traverse rover4 waypoint29 waypoint8)
	(can_traverse rover4 waypoint33 waypoint24)
	(can_traverse rover4 waypoint24 waypoint33)
	(can_traverse rover4 waypoint33 waypoint25)
	(can_traverse rover4 waypoint25 waypoint33)
	(can_traverse rover4 waypoint7 waypoint17)
	(can_traverse rover4 waypoint17 waypoint7)
	(can_traverse rover4 waypoint7 waypoint18)
	(can_traverse rover4 waypoint18 waypoint7)
	(can_traverse rover4 waypoint7 waypoint26)
	(can_traverse rover4 waypoint26 waypoint7)
	(can_traverse rover4 waypoint7 waypoint35)
	(can_traverse rover4 waypoint35 waypoint7)
	(can_traverse rover4 waypoint16 waypoint20)
	(can_traverse rover4 waypoint20 waypoint16)
	(can_traverse rover4 waypoint31 waypoint5)
	(can_traverse rover4 waypoint5 waypoint31)
	(can_traverse rover4 waypoint31 waypoint9)
	(can_traverse rover4 waypoint9 waypoint31)
	(can_traverse rover4 waypoint32 waypoint4)
	(can_traverse rover4 waypoint4 waypoint32)
	(can_traverse rover4 waypoint32 waypoint12)
	(can_traverse rover4 waypoint12 waypoint32)
	(can_traverse rover4 waypoint32 waypoint30)
	(can_traverse rover4 waypoint30 waypoint32)
	(can_traverse rover4 waypoint10 waypoint13)
	(can_traverse rover4 waypoint13 waypoint10)
	(can_traverse rover4 waypoint10 waypoint19)
	(can_traverse rover4 waypoint19 waypoint10)
	(can_traverse rover4 waypoint10 waypoint27)
	(can_traverse rover4 waypoint27 waypoint10)
	(can_traverse rover4 waypoint11 waypoint3)
	(can_traverse rover4 waypoint3 waypoint11)
	(can_traverse rover4 waypoint11 waypoint28)
	(can_traverse rover4 waypoint28 waypoint11)
	(can_traverse rover4 waypoint22 waypoint1)
	(can_traverse rover4 waypoint1 waypoint22)
	(can_traverse rover4 waypoint29 waypoint14)
	(can_traverse rover4 waypoint14 waypoint29)
	(at rover5 waypoint12)
	(available rover5)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_soil_analysis rover5)
	(can_traverse rover5 waypoint12 waypoint4)
	(can_traverse rover5 waypoint4 waypoint12)
	(can_traverse rover5 waypoint12 waypoint6)
	(can_traverse rover5 waypoint6 waypoint12)
	(can_traverse rover5 waypoint12 waypoint17)
	(can_traverse rover5 waypoint17 waypoint12)
	(can_traverse rover5 waypoint12 waypoint21)
	(can_traverse rover5 waypoint21 waypoint12)
	(can_traverse rover5 waypoint12 waypoint23)
	(can_traverse rover5 waypoint23 waypoint12)
	(can_traverse rover5 waypoint12 waypoint24)
	(can_traverse rover5 waypoint24 waypoint12)
	(can_traverse rover5 waypoint12 waypoint27)
	(can_traverse rover5 waypoint27 waypoint12)
	(can_traverse rover5 waypoint12 waypoint32)
	(can_traverse rover5 waypoint32 waypoint12)
	(can_traverse rover5 waypoint4 waypoint3)
	(can_traverse rover5 waypoint3 waypoint4)
	(can_traverse rover5 waypoint4 waypoint28)
	(can_traverse rover5 waypoint28 waypoint4)
	(can_traverse rover5 waypoint6 waypoint8)
	(can_traverse rover5 waypoint8 waypoint6)
	(can_traverse rover5 waypoint6 waypoint9)
	(can_traverse rover5 waypoint9 waypoint6)
	(can_traverse rover5 waypoint6 waypoint11)
	(can_traverse rover5 waypoint11 waypoint6)
	(can_traverse rover5 waypoint6 waypoint15)
	(can_traverse rover5 waypoint15 waypoint6)
	(can_traverse rover5 waypoint6 waypoint25)
	(can_traverse rover5 waypoint25 waypoint6)
	(can_traverse rover5 waypoint17 waypoint7)
	(can_traverse rover5 waypoint7 waypoint17)
	(can_traverse rover5 waypoint17 waypoint10)
	(can_traverse rover5 waypoint10 waypoint17)
	(can_traverse rover5 waypoint17 waypoint20)
	(can_traverse rover5 waypoint20 waypoint17)
	(can_traverse rover5 waypoint17 waypoint22)
	(can_traverse rover5 waypoint22 waypoint17)
	(can_traverse rover5 waypoint17 waypoint31)
	(can_traverse rover5 waypoint31 waypoint17)
	(can_traverse rover5 waypoint21 waypoint16)
	(can_traverse rover5 waypoint16 waypoint21)
	(can_traverse rover5 waypoint21 waypoint34)
	(can_traverse rover5 waypoint34 waypoint21)
	(can_traverse rover5 waypoint23 waypoint14)
	(can_traverse rover5 waypoint14 waypoint23)
	(can_traverse rover5 waypoint23 waypoint30)
	(can_traverse rover5 waypoint30 waypoint23)
	(can_traverse rover5 waypoint24 waypoint5)
	(can_traverse rover5 waypoint5 waypoint24)
	(can_traverse rover5 waypoint24 waypoint18)
	(can_traverse rover5 waypoint18 waypoint24)
	(can_traverse rover5 waypoint27 waypoint13)
	(can_traverse rover5 waypoint13 waypoint27)
	(can_traverse rover5 waypoint27 waypoint19)
	(can_traverse rover5 waypoint19 waypoint27)
	(can_traverse rover5 waypoint32 waypoint2)
	(can_traverse rover5 waypoint2 waypoint32)
	(can_traverse rover5 waypoint32 waypoint29)
	(can_traverse rover5 waypoint29 waypoint32)
	(can_traverse rover5 waypoint11 waypoint26)
	(can_traverse rover5 waypoint26 waypoint11)
	(can_traverse rover5 waypoint25 waypoint33)
	(can_traverse rover5 waypoint33 waypoint25)
	(at rover6 waypoint4)
	(available rover6)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_soil_analysis rover6)
	(equipped_for_rock_analysis rover6)
	(can_traverse rover6 waypoint4 waypoint3)
	(can_traverse rover6 waypoint3 waypoint4)
	(can_traverse rover6 waypoint4 waypoint12)
	(can_traverse rover6 waypoint12 waypoint4)
	(can_traverse rover6 waypoint4 waypoint17)
	(can_traverse rover6 waypoint17 waypoint4)
	(can_traverse rover6 waypoint4 waypoint24)
	(can_traverse rover6 waypoint24 waypoint4)
	(can_traverse rover6 waypoint4 waypoint25)
	(can_traverse rover6 waypoint25 waypoint4)
	(can_traverse rover6 waypoint3 waypoint11)
	(can_traverse rover6 waypoint11 waypoint3)
	(can_traverse rover6 waypoint3 waypoint18)
	(can_traverse rover6 waypoint18 waypoint3)
	(can_traverse rover6 waypoint12 waypoint6)
	(can_traverse rover6 waypoint6 waypoint12)
	(can_traverse rover6 waypoint12 waypoint10)
	(can_traverse rover6 waypoint10 waypoint12)
	(can_traverse rover6 waypoint12 waypoint19)
	(can_traverse rover6 waypoint19 waypoint12)
	(can_traverse rover6 waypoint12 waypoint21)
	(can_traverse rover6 waypoint21 waypoint12)
	(can_traverse rover6 waypoint12 waypoint23)
	(can_traverse rover6 waypoint23 waypoint12)
	(can_traverse rover6 waypoint12 waypoint30)
	(can_traverse rover6 waypoint30 waypoint12)
	(can_traverse rover6 waypoint17 waypoint5)
	(can_traverse rover6 waypoint5 waypoint17)
	(can_traverse rover6 waypoint17 waypoint7)
	(can_traverse rover6 waypoint7 waypoint17)
	(can_traverse rover6 waypoint17 waypoint20)
	(can_traverse rover6 waypoint20 waypoint17)
	(can_traverse rover6 waypoint17 waypoint22)
	(can_traverse rover6 waypoint22 waypoint17)
	(can_traverse rover6 waypoint17 waypoint27)
	(can_traverse rover6 waypoint27 waypoint17)
	(can_traverse rover6 waypoint17 waypoint31)
	(can_traverse rover6 waypoint31 waypoint17)
	(can_traverse rover6 waypoint24 waypoint13)
	(can_traverse rover6 waypoint13 waypoint24)
	(can_traverse rover6 waypoint24 waypoint32)
	(can_traverse rover6 waypoint32 waypoint24)
	(can_traverse rover6 waypoint24 waypoint33)
	(can_traverse rover6 waypoint33 waypoint24)
	(can_traverse rover6 waypoint25 waypoint14)
	(can_traverse rover6 waypoint14 waypoint25)
	(can_traverse rover6 waypoint11 waypoint8)
	(can_traverse rover6 waypoint8 waypoint11)
	(can_traverse rover6 waypoint11 waypoint26)
	(can_traverse rover6 waypoint26 waypoint11)
	(can_traverse rover6 waypoint11 waypoint28)
	(can_traverse rover6 waypoint28 waypoint11)
	(can_traverse rover6 waypoint18 waypoint1)
	(can_traverse rover6 waypoint1 waypoint18)
	(can_traverse rover6 waypoint18 waypoint34)
	(can_traverse rover6 waypoint34 waypoint18)
	(can_traverse rover6 waypoint21 waypoint16)
	(can_traverse rover6 waypoint16 waypoint21)
	(can_traverse rover6 waypoint23 waypoint15)
	(can_traverse rover6 waypoint15 waypoint23)
	(can_traverse rover6 waypoint30 waypoint29)
	(can_traverse rover6 waypoint29 waypoint30)
	(can_traverse rover6 waypoint5 waypoint9)
	(can_traverse rover6 waypoint9 waypoint5)
	(can_traverse rover6 waypoint7 waypoint2)
	(can_traverse rover6 waypoint2 waypoint7)
	(can_traverse rover6 waypoint32 waypoint35)
	(can_traverse rover6 waypoint35 waypoint32)
	(can_traverse rover6 waypoint8 waypoint0)
	(can_traverse rover6 waypoint0 waypoint8)
	(at rover7 waypoint17)
	(available rover7)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_soil_analysis rover7)
	(can_traverse rover7 waypoint17 waypoint4)
	(can_traverse rover7 waypoint4 waypoint17)
	(can_traverse rover7 waypoint17 waypoint5)
	(can_traverse rover7 waypoint5 waypoint17)
	(can_traverse rover7 waypoint17 waypoint12)
	(can_traverse rover7 waypoint12 waypoint17)
	(can_traverse rover7 waypoint17 waypoint20)
	(can_traverse rover7 waypoint20 waypoint17)
	(can_traverse rover7 waypoint17 waypoint22)
	(can_traverse rover7 waypoint22 waypoint17)
	(can_traverse rover7 waypoint17 waypoint24)
	(can_traverse rover7 waypoint24 waypoint17)
	(can_traverse rover7 waypoint17 waypoint31)
	(can_traverse rover7 waypoint31 waypoint17)
	(can_traverse rover7 waypoint17 waypoint35)
	(can_traverse rover7 waypoint35 waypoint17)
	(can_traverse rover7 waypoint4 waypoint3)
	(can_traverse rover7 waypoint3 waypoint4)
	(can_traverse rover7 waypoint4 waypoint13)
	(can_traverse rover7 waypoint13 waypoint4)
	(can_traverse rover7 waypoint4 waypoint25)
	(can_traverse rover7 waypoint25 waypoint4)
	(can_traverse rover7 waypoint4 waypoint28)
	(can_traverse rover7 waypoint28 waypoint4)
	(can_traverse rover7 waypoint5 waypoint1)
	(can_traverse rover7 waypoint1 waypoint5)
	(can_traverse rover7 waypoint5 waypoint2)
	(can_traverse rover7 waypoint2 waypoint5)
	(can_traverse rover7 waypoint5 waypoint14)
	(can_traverse rover7 waypoint14 waypoint5)
	(can_traverse rover7 waypoint5 waypoint26)
	(can_traverse rover7 waypoint26 waypoint5)
	(can_traverse rover7 waypoint12 waypoint6)
	(can_traverse rover7 waypoint6 waypoint12)
	(can_traverse rover7 waypoint12 waypoint10)
	(can_traverse rover7 waypoint10 waypoint12)
	(can_traverse rover7 waypoint12 waypoint19)
	(can_traverse rover7 waypoint19 waypoint12)
	(can_traverse rover7 waypoint12 waypoint21)
	(can_traverse rover7 waypoint21 waypoint12)
	(can_traverse rover7 waypoint12 waypoint23)
	(can_traverse rover7 waypoint23 waypoint12)
	(can_traverse rover7 waypoint12 waypoint27)
	(can_traverse rover7 waypoint27 waypoint12)
	(can_traverse rover7 waypoint12 waypoint30)
	(can_traverse rover7 waypoint30 waypoint12)
	(can_traverse rover7 waypoint22 waypoint18)
	(can_traverse rover7 waypoint18 waypoint22)
	(can_traverse rover7 waypoint22 waypoint32)
	(can_traverse rover7 waypoint32 waypoint22)
	(can_traverse rover7 waypoint24 waypoint33)
	(can_traverse rover7 waypoint33 waypoint24)
	(can_traverse rover7 waypoint31 waypoint7)
	(can_traverse rover7 waypoint7 waypoint31)
	(can_traverse rover7 waypoint31 waypoint9)
	(can_traverse rover7 waypoint9 waypoint31)
	(can_traverse rover7 waypoint31 waypoint15)
	(can_traverse rover7 waypoint15 waypoint31)
	(can_traverse rover7 waypoint31 waypoint29)
	(can_traverse rover7 waypoint29 waypoint31)
	(can_traverse rover7 waypoint35 waypoint0)
	(can_traverse rover7 waypoint0 waypoint35)
	(can_traverse rover7 waypoint3 waypoint11)
	(can_traverse rover7 waypoint11 waypoint3)
	(can_traverse rover7 waypoint10 waypoint8)
	(can_traverse rover7 waypoint8 waypoint10)
	(can_traverse rover7 waypoint21 waypoint34)
	(can_traverse rover7 waypoint34 waypoint21)
	(can_traverse rover7 waypoint30 waypoint16)
	(can_traverse rover7 waypoint16 waypoint30)
	(on_board camera0 rover3)
	(calibration_target camera0 objective1)
	(supports camera0 colour)
	(supports camera0 high_res)
	(supports camera0 low_res)
	(on_board camera1 rover3)
	(calibration_target camera1 objective0)
	(supports camera1 colour)
	(on_board camera2 rover0)
	(calibration_target camera2 objective0)
	(supports camera2 high_res)
	(supports camera2 low_res)
	(on_board camera3 rover1)
	(calibration_target camera3 objective2)
	(supports camera3 colour)
	(supports camera3 high_res)
	(on_board camera4 rover2)
	(calibration_target camera4 objective0)
	(supports camera4 colour)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint3)
	(visible_from objective0 waypoint5)
	(visible_from objective0 waypoint6)
	(visible_from objective0 waypoint8)
	(visible_from objective0 waypoint9)
	(visible_from objective0 waypoint11)
	(visible_from objective0 waypoint12)
	(visible_from objective0 waypoint15)
	(visible_from objective0 waypoint16)
	(visible_from objective0 waypoint17)
	(visible_from objective0 waypoint20)
	(visible_from objective0 waypoint21)
	(visible_from objective0 waypoint23)
	(visible_from objective0 waypoint24)
	(visible_from objective0 waypoint26)
	(visible_from objective0 waypoint27)
	(visible_from objective0 waypoint28)
	(visible_from objective0 waypoint29)
	(visible_from objective0 waypoint30)
	(visible_from objective0 waypoint33)
	(visible_from objective0 waypoint34)
	(visible_from objective0 waypoint35)
	(visible_from objective1 waypoint2)
	(visible_from objective1 waypoint4)
	(visible_from objective1 waypoint13)
	(visible_from objective1 waypoint23)
	(visible_from objective2 waypoint0)
	(visible_from objective2 waypoint1)
	(visible_from objective2 waypoint2)
	(visible_from objective2 waypoint3)
	(visible_from objective2 waypoint4)
	(visible_from objective2 waypoint5)
	(visible_from objective2 waypoint6)
	(visible_from objective2 waypoint7)
	(visible_from objective2 waypoint11)
	(visible_from objective2 waypoint14)
	(visible_from objective2 waypoint15)
	(visible_from objective2 waypoint16)
	(visible_from objective2 waypoint18)
	(visible_from objective2 waypoint19)
	(visible_from objective2 waypoint20)
	(visible_from objective2 waypoint23)
	(visible_from objective2 waypoint24)
	(visible_from objective2 waypoint27)
	(visible_from objective2 waypoint28)
	(visible_from objective2 waypoint31)
	(visible_from objective2 waypoint32)
	(visible_from objective2 waypoint33)
)

(:goal (and
(communicated_soil_data waypoint24)
(communicated_rock_data waypoint12)
(communicated_image_data objective0 colour)
	)
)
)
