(define (problem roverprob1) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 - Waypoint
	camera0 camera1 camera2 camera3 camera4 - Camera
	objective0 - Objective
	)
(:init
	(visible waypoint0 waypoint7)
	(visible waypoint7 waypoint0)
	(visible waypoint0 waypoint26)
	(visible waypoint26 waypoint0)
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint1)
	(visible waypoint1 waypoint4)
	(visible waypoint4 waypoint1)
	(visible waypoint1 waypoint21)
	(visible waypoint21 waypoint1)
	(visible waypoint2 waypoint3)
	(visible waypoint3 waypoint2)
	(visible waypoint2 waypoint5)
	(visible waypoint5 waypoint2)
	(visible waypoint2 waypoint18)
	(visible waypoint18 waypoint2)
	(visible waypoint2 waypoint27)
	(visible waypoint27 waypoint2)
	(visible waypoint3 waypoint10)
	(visible waypoint10 waypoint3)
	(visible waypoint3 waypoint23)
	(visible waypoint23 waypoint3)
	(visible waypoint4 waypoint11)
	(visible waypoint11 waypoint4)
	(visible waypoint4 waypoint17)
	(visible waypoint17 waypoint4)
	(visible waypoint4 waypoint21)
	(visible waypoint21 waypoint4)
	(visible waypoint4 waypoint24)
	(visible waypoint24 waypoint4)
	(visible waypoint4 waypoint25)
	(visible waypoint25 waypoint4)
	(visible waypoint4 waypoint26)
	(visible waypoint26 waypoint4)
	(visible waypoint5 waypoint6)
	(visible waypoint6 waypoint5)
	(visible waypoint5 waypoint8)
	(visible waypoint8 waypoint5)
	(visible waypoint5 waypoint12)
	(visible waypoint12 waypoint5)
	(visible waypoint5 waypoint19)
	(visible waypoint19 waypoint5)
	(visible waypoint6 waypoint25)
	(visible waypoint25 waypoint6)
	(visible waypoint7 waypoint15)
	(visible waypoint15 waypoint7)
	(visible waypoint7 waypoint25)
	(visible waypoint25 waypoint7)
	(visible waypoint8 waypoint6)
	(visible waypoint6 waypoint8)
	(visible waypoint8 waypoint10)
	(visible waypoint10 waypoint8)
	(visible waypoint8 waypoint15)
	(visible waypoint15 waypoint8)
	(visible waypoint8 waypoint16)
	(visible waypoint16 waypoint8)
	(visible waypoint8 waypoint21)
	(visible waypoint21 waypoint8)
	(visible waypoint8 waypoint22)
	(visible waypoint22 waypoint8)
	(visible waypoint8 waypoint28)
	(visible waypoint28 waypoint8)
	(visible waypoint9 waypoint5)
	(visible waypoint5 waypoint9)
	(visible waypoint9 waypoint6)
	(visible waypoint6 waypoint9)
	(visible waypoint9 waypoint22)
	(visible waypoint22 waypoint9)
	(visible waypoint10 waypoint5)
	(visible waypoint5 waypoint10)
	(visible waypoint10 waypoint14)
	(visible waypoint14 waypoint10)
	(visible waypoint10 waypoint16)
	(visible waypoint16 waypoint10)
	(visible waypoint10 waypoint17)
	(visible waypoint17 waypoint10)
	(visible waypoint10 waypoint19)
	(visible waypoint19 waypoint10)
	(visible waypoint10 waypoint22)
	(visible waypoint22 waypoint10)
	(visible waypoint11 waypoint23)
	(visible waypoint23 waypoint11)
	(visible waypoint11 waypoint25)
	(visible waypoint25 waypoint11)
	(visible waypoint12 waypoint0)
	(visible waypoint0 waypoint12)
	(visible waypoint12 waypoint6)
	(visible waypoint6 waypoint12)
	(visible waypoint12 waypoint20)
	(visible waypoint20 waypoint12)
	(visible waypoint12 waypoint25)
	(visible waypoint25 waypoint12)
	(visible waypoint12 waypoint26)
	(visible waypoint26 waypoint12)
	(visible waypoint12 waypoint27)
	(visible waypoint27 waypoint12)
	(visible waypoint13 waypoint1)
	(visible waypoint1 waypoint13)
	(visible waypoint13 waypoint6)
	(visible waypoint6 waypoint13)
	(visible waypoint13 waypoint8)
	(visible waypoint8 waypoint13)
	(visible waypoint13 waypoint17)
	(visible waypoint17 waypoint13)
	(visible waypoint13 waypoint18)
	(visible waypoint18 waypoint13)
	(visible waypoint13 waypoint23)
	(visible waypoint23 waypoint13)
	(visible waypoint14 waypoint19)
	(visible waypoint19 waypoint14)
	(visible waypoint14 waypoint22)
	(visible waypoint22 waypoint14)
	(visible waypoint14 waypoint24)
	(visible waypoint24 waypoint14)
	(visible waypoint14 waypoint28)
	(visible waypoint28 waypoint14)
	(visible waypoint15 waypoint1)
	(visible waypoint1 waypoint15)
	(visible waypoint15 waypoint2)
	(visible waypoint2 waypoint15)
	(visible waypoint15 waypoint21)
	(visible waypoint21 waypoint15)
	(visible waypoint15 waypoint22)
	(visible waypoint22 waypoint15)
	(visible waypoint16 waypoint7)
	(visible waypoint7 waypoint16)
	(visible waypoint16 waypoint12)
	(visible waypoint12 waypoint16)
	(visible waypoint16 waypoint13)
	(visible waypoint13 waypoint16)
	(visible waypoint16 waypoint17)
	(visible waypoint17 waypoint16)
	(visible waypoint16 waypoint21)
	(visible waypoint21 waypoint16)
	(visible waypoint16 waypoint25)
	(visible waypoint25 waypoint16)
	(visible waypoint17 waypoint5)
	(visible waypoint5 waypoint17)
	(visible waypoint17 waypoint8)
	(visible waypoint8 waypoint17)
	(visible waypoint17 waypoint18)
	(visible waypoint18 waypoint17)
	(visible waypoint18 waypoint1)
	(visible waypoint1 waypoint18)
	(visible waypoint18 waypoint6)
	(visible waypoint6 waypoint18)
	(visible waypoint18 waypoint7)
	(visible waypoint7 waypoint18)
	(visible waypoint18 waypoint10)
	(visible waypoint10 waypoint18)
	(visible waypoint18 waypoint12)
	(visible waypoint12 waypoint18)
	(visible waypoint18 waypoint15)
	(visible waypoint15 waypoint18)
	(visible waypoint18 waypoint20)
	(visible waypoint20 waypoint18)
	(visible waypoint18 waypoint22)
	(visible waypoint22 waypoint18)
	(visible waypoint19 waypoint2)
	(visible waypoint2 waypoint19)
	(visible waypoint19 waypoint4)
	(visible waypoint4 waypoint19)
	(visible waypoint19 waypoint8)
	(visible waypoint8 waypoint19)
	(visible waypoint19 waypoint11)
	(visible waypoint11 waypoint19)
	(visible waypoint19 waypoint18)
	(visible waypoint18 waypoint19)
	(visible waypoint19 waypoint24)
	(visible waypoint24 waypoint19)
	(visible waypoint19 waypoint26)
	(visible waypoint26 waypoint19)
	(visible waypoint19 waypoint28)
	(visible waypoint28 waypoint19)
	(visible waypoint20 waypoint3)
	(visible waypoint3 waypoint20)
	(visible waypoint20 waypoint5)
	(visible waypoint5 waypoint20)
	(visible waypoint20 waypoint9)
	(visible waypoint9 waypoint20)
	(visible waypoint21 waypoint5)
	(visible waypoint5 waypoint21)
	(visible waypoint21 waypoint9)
	(visible waypoint9 waypoint21)
	(visible waypoint21 waypoint10)
	(visible waypoint10 waypoint21)
	(visible waypoint21 waypoint18)
	(visible waypoint18 waypoint21)
	(visible waypoint22 waypoint20)
	(visible waypoint20 waypoint22)
	(visible waypoint22 waypoint23)
	(visible waypoint23 waypoint22)
	(visible waypoint23 waypoint9)
	(visible waypoint9 waypoint23)
	(visible waypoint23 waypoint21)
	(visible waypoint21 waypoint23)
	(visible waypoint23 waypoint26)
	(visible waypoint26 waypoint23)
	(visible waypoint24 waypoint6)
	(visible waypoint6 waypoint24)
	(visible waypoint24 waypoint9)
	(visible waypoint9 waypoint24)
	(visible waypoint24 waypoint11)
	(visible waypoint11 waypoint24)
	(visible waypoint25 waypoint2)
	(visible waypoint2 waypoint25)
	(visible waypoint25 waypoint3)
	(visible waypoint3 waypoint25)
	(visible waypoint25 waypoint10)
	(visible waypoint10 waypoint25)
	(visible waypoint25 waypoint24)
	(visible waypoint24 waypoint25)
	(visible waypoint26 waypoint5)
	(visible waypoint5 waypoint26)
	(visible waypoint26 waypoint20)
	(visible waypoint20 waypoint26)
	(visible waypoint26 waypoint24)
	(visible waypoint24 waypoint26)
	(visible waypoint26 waypoint28)
	(visible waypoint28 waypoint26)
	(visible waypoint27 waypoint13)
	(visible waypoint13 waypoint27)
	(visible waypoint27 waypoint17)
	(visible waypoint17 waypoint27)
	(visible waypoint27 waypoint26)
	(visible waypoint26 waypoint27)
	(visible waypoint28 waypoint0)
	(visible waypoint0 waypoint28)
	(visible waypoint28 waypoint1)
	(visible waypoint1 waypoint28)
	(visible waypoint28 waypoint5)
	(visible waypoint5 waypoint28)
	(visible waypoint28 waypoint6)
	(visible waypoint6 waypoint28)
	(visible waypoint28 waypoint21)
	(visible waypoint21 waypoint28)
	(visible waypoint28 waypoint27)
	(visible waypoint27 waypoint28)
	(at_soil_sample waypoint0)
	(at_soil_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_rock_sample waypoint4)
	(at_soil_sample waypoint5)
	(at_rock_sample waypoint5)
	(at_rock_sample waypoint6)
	(at_soil_sample waypoint9)
	(at_rock_sample waypoint13)
	(at_soil_sample waypoint14)
	(at_soil_sample waypoint15)
	(at_soil_sample waypoint17)
	(at_soil_sample waypoint21)
	(at_rock_sample waypoint21)
	(at_rock_sample waypoint22)
	(at_soil_sample waypoint23)
	(at_rock_sample waypoint24)
	(at_soil_sample waypoint25)
	(at_soil_sample waypoint27)
	(at_soil_sample waypoint28)
	(at_lander general waypoint19)
	(channel_free general)
	(at rover0 waypoint11)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint11 waypoint4)
	(can_traverse rover0 waypoint4 waypoint11)
	(can_traverse rover0 waypoint11 waypoint23)
	(can_traverse rover0 waypoint23 waypoint11)
	(can_traverse rover0 waypoint11 waypoint24)
	(can_traverse rover0 waypoint24 waypoint11)
	(can_traverse rover0 waypoint4 waypoint1)
	(can_traverse rover0 waypoint1 waypoint4)
	(can_traverse rover0 waypoint4 waypoint17)
	(can_traverse rover0 waypoint17 waypoint4)
	(can_traverse rover0 waypoint4 waypoint19)
	(can_traverse rover0 waypoint19 waypoint4)
	(can_traverse rover0 waypoint4 waypoint21)
	(can_traverse rover0 waypoint21 waypoint4)
	(can_traverse rover0 waypoint4 waypoint25)
	(can_traverse rover0 waypoint25 waypoint4)
	(can_traverse rover0 waypoint23 waypoint9)
	(can_traverse rover0 waypoint9 waypoint23)
	(can_traverse rover0 waypoint23 waypoint13)
	(can_traverse rover0 waypoint13 waypoint23)
	(can_traverse rover0 waypoint23 waypoint22)
	(can_traverse rover0 waypoint22 waypoint23)
	(can_traverse rover0 waypoint23 waypoint26)
	(can_traverse rover0 waypoint26 waypoint23)
	(can_traverse rover0 waypoint24 waypoint6)
	(can_traverse rover0 waypoint6 waypoint24)
	(can_traverse rover0 waypoint1 waypoint15)
	(can_traverse rover0 waypoint15 waypoint1)
	(can_traverse rover0 waypoint1 waypoint18)
	(can_traverse rover0 waypoint18 waypoint1)
	(can_traverse rover0 waypoint17 waypoint5)
	(can_traverse rover0 waypoint5 waypoint17)
	(can_traverse rover0 waypoint17 waypoint8)
	(can_traverse rover0 waypoint8 waypoint17)
	(can_traverse rover0 waypoint17 waypoint10)
	(can_traverse rover0 waypoint10 waypoint17)
	(can_traverse rover0 waypoint17 waypoint16)
	(can_traverse rover0 waypoint16 waypoint17)
	(can_traverse rover0 waypoint19 waypoint14)
	(can_traverse rover0 waypoint14 waypoint19)
	(can_traverse rover0 waypoint25 waypoint2)
	(can_traverse rover0 waypoint2 waypoint25)
	(can_traverse rover0 waypoint25 waypoint3)
	(can_traverse rover0 waypoint3 waypoint25)
	(can_traverse rover0 waypoint25 waypoint7)
	(can_traverse rover0 waypoint7 waypoint25)
	(can_traverse rover0 waypoint25 waypoint12)
	(can_traverse rover0 waypoint12 waypoint25)
	(can_traverse rover0 waypoint9 waypoint20)
	(can_traverse rover0 waypoint20 waypoint9)
	(can_traverse rover0 waypoint13 waypoint27)
	(can_traverse rover0 waypoint27 waypoint13)
	(can_traverse rover0 waypoint26 waypoint0)
	(can_traverse rover0 waypoint0 waypoint26)
	(can_traverse rover0 waypoint26 waypoint28)
	(can_traverse rover0 waypoint28 waypoint26)
	(at rover1 waypoint9)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_rock_analysis rover1)
	(can_traverse rover1 waypoint9 waypoint5)
	(can_traverse rover1 waypoint5 waypoint9)
	(can_traverse rover1 waypoint9 waypoint22)
	(can_traverse rover1 waypoint22 waypoint9)
	(can_traverse rover1 waypoint9 waypoint23)
	(can_traverse rover1 waypoint23 waypoint9)
	(can_traverse rover1 waypoint5 waypoint2)
	(can_traverse rover1 waypoint2 waypoint5)
	(can_traverse rover1 waypoint5 waypoint8)
	(can_traverse rover1 waypoint8 waypoint5)
	(can_traverse rover1 waypoint5 waypoint10)
	(can_traverse rover1 waypoint10 waypoint5)
	(can_traverse rover1 waypoint5 waypoint12)
	(can_traverse rover1 waypoint12 waypoint5)
	(can_traverse rover1 waypoint5 waypoint19)
	(can_traverse rover1 waypoint19 waypoint5)
	(can_traverse rover1 waypoint5 waypoint20)
	(can_traverse rover1 waypoint20 waypoint5)
	(can_traverse rover1 waypoint5 waypoint21)
	(can_traverse rover1 waypoint21 waypoint5)
	(can_traverse rover1 waypoint5 waypoint28)
	(can_traverse rover1 waypoint28 waypoint5)
	(can_traverse rover1 waypoint22 waypoint14)
	(can_traverse rover1 waypoint14 waypoint22)
	(can_traverse rover1 waypoint22 waypoint15)
	(can_traverse rover1 waypoint15 waypoint22)
	(can_traverse rover1 waypoint23 waypoint3)
	(can_traverse rover1 waypoint3 waypoint23)
	(can_traverse rover1 waypoint23 waypoint11)
	(can_traverse rover1 waypoint11 waypoint23)
	(can_traverse rover1 waypoint23 waypoint13)
	(can_traverse rover1 waypoint13 waypoint23)
	(can_traverse rover1 waypoint23 waypoint26)
	(can_traverse rover1 waypoint26 waypoint23)
	(can_traverse rover1 waypoint2 waypoint25)
	(can_traverse rover1 waypoint25 waypoint2)
	(can_traverse rover1 waypoint2 waypoint27)
	(can_traverse rover1 waypoint27 waypoint2)
	(can_traverse rover1 waypoint8 waypoint6)
	(can_traverse rover1 waypoint6 waypoint8)
	(can_traverse rover1 waypoint8 waypoint16)
	(can_traverse rover1 waypoint16 waypoint8)
	(can_traverse rover1 waypoint8 waypoint17)
	(can_traverse rover1 waypoint17 waypoint8)
	(can_traverse rover1 waypoint10 waypoint18)
	(can_traverse rover1 waypoint18 waypoint10)
	(can_traverse rover1 waypoint19 waypoint4)
	(can_traverse rover1 waypoint4 waypoint19)
	(can_traverse rover1 waypoint21 waypoint1)
	(can_traverse rover1 waypoint1 waypoint21)
	(can_traverse rover1 waypoint28 waypoint0)
	(can_traverse rover1 waypoint0 waypoint28)
	(can_traverse rover1 waypoint11 waypoint24)
	(can_traverse rover1 waypoint24 waypoint11)
	(can_traverse rover1 waypoint25 waypoint7)
	(can_traverse rover1 waypoint7 waypoint25)
	(at rover2 waypoint1)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_soil_analysis rover2)
	(can_traverse rover2 waypoint1 waypoint0)
	(can_traverse rover2 waypoint0 waypoint1)
	(can_traverse rover2 waypoint1 waypoint4)
	(can_traverse rover2 waypoint4 waypoint1)
	(can_traverse rover2 waypoint1 waypoint13)
	(can_traverse rover2 waypoint13 waypoint1)
	(can_traverse rover2 waypoint1 waypoint21)
	(can_traverse rover2 waypoint21 waypoint1)
	(can_traverse rover2 waypoint1 waypoint28)
	(can_traverse rover2 waypoint28 waypoint1)
	(can_traverse rover2 waypoint0 waypoint7)
	(can_traverse rover2 waypoint7 waypoint0)
	(can_traverse rover2 waypoint0 waypoint12)
	(can_traverse rover2 waypoint12 waypoint0)
	(can_traverse rover2 waypoint4 waypoint19)
	(can_traverse rover2 waypoint19 waypoint4)
	(can_traverse rover2 waypoint4 waypoint24)
	(can_traverse rover2 waypoint24 waypoint4)
	(can_traverse rover2 waypoint4 waypoint25)
	(can_traverse rover2 waypoint25 waypoint4)
	(can_traverse rover2 waypoint4 waypoint26)
	(can_traverse rover2 waypoint26 waypoint4)
	(can_traverse rover2 waypoint13 waypoint8)
	(can_traverse rover2 waypoint8 waypoint13)
	(can_traverse rover2 waypoint13 waypoint16)
	(can_traverse rover2 waypoint16 waypoint13)
	(can_traverse rover2 waypoint13 waypoint17)
	(can_traverse rover2 waypoint17 waypoint13)
	(can_traverse rover2 waypoint13 waypoint18)
	(can_traverse rover2 waypoint18 waypoint13)
	(can_traverse rover2 waypoint13 waypoint23)
	(can_traverse rover2 waypoint23 waypoint13)
	(can_traverse rover2 waypoint13 waypoint27)
	(can_traverse rover2 waypoint27 waypoint13)
	(can_traverse rover2 waypoint21 waypoint5)
	(can_traverse rover2 waypoint5 waypoint21)
	(can_traverse rover2 waypoint21 waypoint9)
	(can_traverse rover2 waypoint9 waypoint21)
	(can_traverse rover2 waypoint21 waypoint15)
	(can_traverse rover2 waypoint15 waypoint21)
	(can_traverse rover2 waypoint28 waypoint6)
	(can_traverse rover2 waypoint6 waypoint28)
	(can_traverse rover2 waypoint28 waypoint14)
	(can_traverse rover2 waypoint14 waypoint28)
	(can_traverse rover2 waypoint12 waypoint20)
	(can_traverse rover2 waypoint20 waypoint12)
	(can_traverse rover2 waypoint19 waypoint10)
	(can_traverse rover2 waypoint10 waypoint19)
	(can_traverse rover2 waypoint25 waypoint2)
	(can_traverse rover2 waypoint2 waypoint25)
	(can_traverse rover2 waypoint25 waypoint11)
	(can_traverse rover2 waypoint11 waypoint25)
	(can_traverse rover2 waypoint18 waypoint22)
	(can_traverse rover2 waypoint22 waypoint18)
	(can_traverse rover2 waypoint20 waypoint3)
	(can_traverse rover2 waypoint3 waypoint20)
	(at rover3 waypoint25)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_rock_analysis rover3)
	(can_traverse rover3 waypoint25 waypoint2)
	(can_traverse rover3 waypoint2 waypoint25)
	(can_traverse rover3 waypoint25 waypoint4)
	(can_traverse rover3 waypoint4 waypoint25)
	(can_traverse rover3 waypoint25 waypoint6)
	(can_traverse rover3 waypoint6 waypoint25)
	(can_traverse rover3 waypoint25 waypoint7)
	(can_traverse rover3 waypoint7 waypoint25)
	(can_traverse rover3 waypoint25 waypoint10)
	(can_traverse rover3 waypoint10 waypoint25)
	(can_traverse rover3 waypoint25 waypoint16)
	(can_traverse rover3 waypoint16 waypoint25)
	(can_traverse rover3 waypoint2 waypoint3)
	(can_traverse rover3 waypoint3 waypoint2)
	(can_traverse rover3 waypoint2 waypoint5)
	(can_traverse rover3 waypoint5 waypoint2)
	(can_traverse rover3 waypoint2 waypoint15)
	(can_traverse rover3 waypoint15 waypoint2)
	(can_traverse rover3 waypoint2 waypoint19)
	(can_traverse rover3 waypoint19 waypoint2)
	(can_traverse rover3 waypoint2 waypoint27)
	(can_traverse rover3 waypoint27 waypoint2)
	(can_traverse rover3 waypoint4 waypoint1)
	(can_traverse rover3 waypoint1 waypoint4)
	(can_traverse rover3 waypoint4 waypoint17)
	(can_traverse rover3 waypoint17 waypoint4)
	(can_traverse rover3 waypoint4 waypoint21)
	(can_traverse rover3 waypoint21 waypoint4)
	(can_traverse rover3 waypoint4 waypoint26)
	(can_traverse rover3 waypoint26 waypoint4)
	(can_traverse rover3 waypoint6 waypoint9)
	(can_traverse rover3 waypoint9 waypoint6)
	(can_traverse rover3 waypoint6 waypoint12)
	(can_traverse rover3 waypoint12 waypoint6)
	(can_traverse rover3 waypoint6 waypoint13)
	(can_traverse rover3 waypoint13 waypoint6)
	(can_traverse rover3 waypoint6 waypoint18)
	(can_traverse rover3 waypoint18 waypoint6)
	(can_traverse rover3 waypoint6 waypoint28)
	(can_traverse rover3 waypoint28 waypoint6)
	(can_traverse rover3 waypoint7 waypoint0)
	(can_traverse rover3 waypoint0 waypoint7)
	(can_traverse rover3 waypoint10 waypoint8)
	(can_traverse rover3 waypoint8 waypoint10)
	(can_traverse rover3 waypoint10 waypoint14)
	(can_traverse rover3 waypoint14 waypoint10)
	(can_traverse rover3 waypoint10 waypoint22)
	(can_traverse rover3 waypoint22 waypoint10)
	(can_traverse rover3 waypoint3 waypoint20)
	(can_traverse rover3 waypoint20 waypoint3)
	(can_traverse rover3 waypoint3 waypoint23)
	(can_traverse rover3 waypoint23 waypoint3)
	(can_traverse rover3 waypoint19 waypoint11)
	(can_traverse rover3 waypoint11 waypoint19)
	(can_traverse rover3 waypoint26 waypoint24)
	(can_traverse rover3 waypoint24 waypoint26)
	(at rover4 waypoint24)
	(available rover4)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_soil_analysis rover4)
	(equipped_for_rock_analysis rover4)
	(can_traverse rover4 waypoint24 waypoint4)
	(can_traverse rover4 waypoint4 waypoint24)
	(can_traverse rover4 waypoint24 waypoint6)
	(can_traverse rover4 waypoint6 waypoint24)
	(can_traverse rover4 waypoint24 waypoint9)
	(can_traverse rover4 waypoint9 waypoint24)
	(can_traverse rover4 waypoint24 waypoint11)
	(can_traverse rover4 waypoint11 waypoint24)
	(can_traverse rover4 waypoint24 waypoint14)
	(can_traverse rover4 waypoint14 waypoint24)
	(can_traverse rover4 waypoint4 waypoint1)
	(can_traverse rover4 waypoint1 waypoint4)
	(can_traverse rover4 waypoint4 waypoint19)
	(can_traverse rover4 waypoint19 waypoint4)
	(can_traverse rover4 waypoint4 waypoint21)
	(can_traverse rover4 waypoint21 waypoint4)
	(can_traverse rover4 waypoint4 waypoint25)
	(can_traverse rover4 waypoint25 waypoint4)
	(can_traverse rover4 waypoint6 waypoint8)
	(can_traverse rover4 waypoint8 waypoint6)
	(can_traverse rover4 waypoint6 waypoint13)
	(can_traverse rover4 waypoint13 waypoint6)
	(can_traverse rover4 waypoint6 waypoint18)
	(can_traverse rover4 waypoint18 waypoint6)
	(can_traverse rover4 waypoint9 waypoint5)
	(can_traverse rover4 waypoint5 waypoint9)
	(can_traverse rover4 waypoint9 waypoint20)
	(can_traverse rover4 waypoint20 waypoint9)
	(can_traverse rover4 waypoint9 waypoint22)
	(can_traverse rover4 waypoint22 waypoint9)
	(can_traverse rover4 waypoint9 waypoint23)
	(can_traverse rover4 waypoint23 waypoint9)
	(can_traverse rover4 waypoint14 waypoint10)
	(can_traverse rover4 waypoint10 waypoint14)
	(can_traverse rover4 waypoint14 waypoint28)
	(can_traverse rover4 waypoint28 waypoint14)
	(can_traverse rover4 waypoint19 waypoint2)
	(can_traverse rover4 waypoint2 waypoint19)
	(can_traverse rover4 waypoint19 waypoint26)
	(can_traverse rover4 waypoint26 waypoint19)
	(can_traverse rover4 waypoint21 waypoint15)
	(can_traverse rover4 waypoint15 waypoint21)
	(can_traverse rover4 waypoint21 waypoint16)
	(can_traverse rover4 waypoint16 waypoint21)
	(can_traverse rover4 waypoint25 waypoint7)
	(can_traverse rover4 waypoint7 waypoint25)
	(can_traverse rover4 waypoint25 waypoint12)
	(can_traverse rover4 waypoint12 waypoint25)
	(can_traverse rover4 waypoint8 waypoint17)
	(can_traverse rover4 waypoint17 waypoint8)
	(can_traverse rover4 waypoint13 waypoint27)
	(can_traverse rover4 waypoint27 waypoint13)
	(can_traverse rover4 waypoint20 waypoint3)
	(can_traverse rover4 waypoint3 waypoint20)
	(can_traverse rover4 waypoint28 waypoint0)
	(can_traverse rover4 waypoint0 waypoint28)
	(at rover5 waypoint6)
	(available rover5)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_imaging rover5)
	(can_traverse rover5 waypoint6 waypoint5)
	(can_traverse rover5 waypoint5 waypoint6)
	(can_traverse rover5 waypoint6 waypoint8)
	(can_traverse rover5 waypoint8 waypoint6)
	(can_traverse rover5 waypoint6 waypoint9)
	(can_traverse rover5 waypoint9 waypoint6)
	(can_traverse rover5 waypoint6 waypoint12)
	(can_traverse rover5 waypoint12 waypoint6)
	(can_traverse rover5 waypoint6 waypoint13)
	(can_traverse rover5 waypoint13 waypoint6)
	(can_traverse rover5 waypoint6 waypoint18)
	(can_traverse rover5 waypoint18 waypoint6)
	(can_traverse rover5 waypoint6 waypoint24)
	(can_traverse rover5 waypoint24 waypoint6)
	(can_traverse rover5 waypoint6 waypoint25)
	(can_traverse rover5 waypoint25 waypoint6)
	(can_traverse rover5 waypoint6 waypoint28)
	(can_traverse rover5 waypoint28 waypoint6)
	(can_traverse rover5 waypoint5 waypoint2)
	(can_traverse rover5 waypoint2 waypoint5)
	(can_traverse rover5 waypoint5 waypoint10)
	(can_traverse rover5 waypoint10 waypoint5)
	(can_traverse rover5 waypoint5 waypoint17)
	(can_traverse rover5 waypoint17 waypoint5)
	(can_traverse rover5 waypoint5 waypoint19)
	(can_traverse rover5 waypoint19 waypoint5)
	(can_traverse rover5 waypoint5 waypoint20)
	(can_traverse rover5 waypoint20 waypoint5)
	(can_traverse rover5 waypoint5 waypoint21)
	(can_traverse rover5 waypoint21 waypoint5)
	(can_traverse rover5 waypoint5 waypoint26)
	(can_traverse rover5 waypoint26 waypoint5)
	(can_traverse rover5 waypoint8 waypoint16)
	(can_traverse rover5 waypoint16 waypoint8)
	(can_traverse rover5 waypoint8 waypoint22)
	(can_traverse rover5 waypoint22 waypoint8)
	(can_traverse rover5 waypoint12 waypoint0)
	(can_traverse rover5 waypoint0 waypoint12)
	(can_traverse rover5 waypoint12 waypoint27)
	(can_traverse rover5 waypoint27 waypoint12)
	(can_traverse rover5 waypoint13 waypoint1)
	(can_traverse rover5 waypoint1 waypoint13)
	(can_traverse rover5 waypoint13 waypoint23)
	(can_traverse rover5 waypoint23 waypoint13)
	(can_traverse rover5 waypoint18 waypoint7)
	(can_traverse rover5 waypoint7 waypoint18)
	(can_traverse rover5 waypoint18 waypoint15)
	(can_traverse rover5 waypoint15 waypoint18)
	(can_traverse rover5 waypoint24 waypoint4)
	(can_traverse rover5 waypoint4 waypoint24)
	(can_traverse rover5 waypoint24 waypoint11)
	(can_traverse rover5 waypoint11 waypoint24)
	(can_traverse rover5 waypoint24 waypoint14)
	(can_traverse rover5 waypoint14 waypoint24)
	(can_traverse rover5 waypoint2 waypoint3)
	(can_traverse rover5 waypoint3 waypoint2)
	(at rover6 waypoint0)
	(available rover6)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_imaging rover6)
	(can_traverse rover6 waypoint0 waypoint1)
	(can_traverse rover6 waypoint1 waypoint0)
	(can_traverse rover6 waypoint0 waypoint12)
	(can_traverse rover6 waypoint12 waypoint0)
	(can_traverse rover6 waypoint0 waypoint26)
	(can_traverse rover6 waypoint26 waypoint0)
	(can_traverse rover6 waypoint1 waypoint4)
	(can_traverse rover6 waypoint4 waypoint1)
	(can_traverse rover6 waypoint1 waypoint13)
	(can_traverse rover6 waypoint13 waypoint1)
	(can_traverse rover6 waypoint1 waypoint15)
	(can_traverse rover6 waypoint15 waypoint1)
	(can_traverse rover6 waypoint1 waypoint18)
	(can_traverse rover6 waypoint18 waypoint1)
	(can_traverse rover6 waypoint1 waypoint28)
	(can_traverse rover6 waypoint28 waypoint1)
	(can_traverse rover6 waypoint12 waypoint6)
	(can_traverse rover6 waypoint6 waypoint12)
	(can_traverse rover6 waypoint12 waypoint20)
	(can_traverse rover6 waypoint20 waypoint12)
	(can_traverse rover6 waypoint12 waypoint25)
	(can_traverse rover6 waypoint25 waypoint12)
	(can_traverse rover6 waypoint12 waypoint27)
	(can_traverse rover6 waypoint27 waypoint12)
	(can_traverse rover6 waypoint26 waypoint5)
	(can_traverse rover6 waypoint5 waypoint26)
	(can_traverse rover6 waypoint26 waypoint19)
	(can_traverse rover6 waypoint19 waypoint26)
	(can_traverse rover6 waypoint26 waypoint23)
	(can_traverse rover6 waypoint23 waypoint26)
	(can_traverse rover6 waypoint26 waypoint24)
	(can_traverse rover6 waypoint24 waypoint26)
	(can_traverse rover6 waypoint4 waypoint21)
	(can_traverse rover6 waypoint21 waypoint4)
	(can_traverse rover6 waypoint13 waypoint8)
	(can_traverse rover6 waypoint8 waypoint13)
	(can_traverse rover6 waypoint15 waypoint2)
	(can_traverse rover6 waypoint2 waypoint15)
	(can_traverse rover6 waypoint15 waypoint7)
	(can_traverse rover6 waypoint7 waypoint15)
	(can_traverse rover6 waypoint15 waypoint22)
	(can_traverse rover6 waypoint22 waypoint15)
	(can_traverse rover6 waypoint18 waypoint10)
	(can_traverse rover6 waypoint10 waypoint18)
	(can_traverse rover6 waypoint18 waypoint17)
	(can_traverse rover6 waypoint17 waypoint18)
	(can_traverse rover6 waypoint28 waypoint14)
	(can_traverse rover6 waypoint14 waypoint28)
	(can_traverse rover6 waypoint6 waypoint9)
	(can_traverse rover6 waypoint9 waypoint6)
	(can_traverse rover6 waypoint20 waypoint3)
	(can_traverse rover6 waypoint3 waypoint20)
	(can_traverse rover6 waypoint25 waypoint11)
	(can_traverse rover6 waypoint11 waypoint25)
	(can_traverse rover6 waypoint25 waypoint16)
	(can_traverse rover6 waypoint16 waypoint25)
	(at rover7 waypoint9)
	(available rover7)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_rock_analysis rover7)
	(equipped_for_imaging rover7)
	(can_traverse rover7 waypoint9 waypoint5)
	(can_traverse rover7 waypoint5 waypoint9)
	(can_traverse rover7 waypoint9 waypoint6)
	(can_traverse rover7 waypoint6 waypoint9)
	(can_traverse rover7 waypoint9 waypoint20)
	(can_traverse rover7 waypoint20 waypoint9)
	(can_traverse rover7 waypoint9 waypoint21)
	(can_traverse rover7 waypoint21 waypoint9)
	(can_traverse rover7 waypoint9 waypoint23)
	(can_traverse rover7 waypoint23 waypoint9)
	(can_traverse rover7 waypoint9 waypoint24)
	(can_traverse rover7 waypoint24 waypoint9)
	(can_traverse rover7 waypoint5 waypoint2)
	(can_traverse rover7 waypoint2 waypoint5)
	(can_traverse rover7 waypoint5 waypoint8)
	(can_traverse rover7 waypoint8 waypoint5)
	(can_traverse rover7 waypoint5 waypoint12)
	(can_traverse rover7 waypoint12 waypoint5)
	(can_traverse rover7 waypoint5 waypoint17)
	(can_traverse rover7 waypoint17 waypoint5)
	(can_traverse rover7 waypoint5 waypoint19)
	(can_traverse rover7 waypoint19 waypoint5)
	(can_traverse rover7 waypoint5 waypoint26)
	(can_traverse rover7 waypoint26 waypoint5)
	(can_traverse rover7 waypoint5 waypoint28)
	(can_traverse rover7 waypoint28 waypoint5)
	(can_traverse rover7 waypoint6 waypoint13)
	(can_traverse rover7 waypoint13 waypoint6)
	(can_traverse rover7 waypoint6 waypoint18)
	(can_traverse rover7 waypoint18 waypoint6)
	(can_traverse rover7 waypoint20 waypoint3)
	(can_traverse rover7 waypoint3 waypoint20)
	(can_traverse rover7 waypoint20 waypoint22)
	(can_traverse rover7 waypoint22 waypoint20)
	(can_traverse rover7 waypoint21 waypoint1)
	(can_traverse rover7 waypoint1 waypoint21)
	(can_traverse rover7 waypoint21 waypoint4)
	(can_traverse rover7 waypoint4 waypoint21)
	(can_traverse rover7 waypoint21 waypoint15)
	(can_traverse rover7 waypoint15 waypoint21)
	(can_traverse rover7 waypoint21 waypoint16)
	(can_traverse rover7 waypoint16 waypoint21)
	(can_traverse rover7 waypoint24 waypoint11)
	(can_traverse rover7 waypoint11 waypoint24)
	(can_traverse rover7 waypoint24 waypoint25)
	(can_traverse rover7 waypoint25 waypoint24)
	(can_traverse rover7 waypoint2 waypoint27)
	(can_traverse rover7 waypoint27 waypoint2)
	(can_traverse rover7 waypoint8 waypoint10)
	(can_traverse rover7 waypoint10 waypoint8)
	(can_traverse rover7 waypoint12 waypoint0)
	(can_traverse rover7 waypoint0 waypoint12)
	(can_traverse rover7 waypoint28 waypoint14)
	(can_traverse rover7 waypoint14 waypoint28)
	(can_traverse rover7 waypoint18 waypoint7)
	(can_traverse rover7 waypoint7 waypoint18)
	(on_board camera0 rover0)
	(calibration_target camera0 objective0)
	(supports camera0 colour)
	(supports camera0 low_res)
	(on_board camera1 rover7)
	(calibration_target camera1 objective0)
	(supports camera1 colour)
	(supports camera1 high_res)
	(on_board camera2 rover7)
	(calibration_target camera2 objective0)
	(supports camera2 colour)
	(on_board camera3 rover5)
	(calibration_target camera3 objective0)
	(supports camera3 low_res)
	(on_board camera4 rover6)
	(calibration_target camera4 objective0)
	(supports camera4 high_res)
	(visible_from objective0 waypoint3)
	(visible_from objective0 waypoint4)
	(visible_from objective0 waypoint5)
	(visible_from objective0 waypoint7)
	(visible_from objective0 waypoint8)
	(visible_from objective0 waypoint10)
	(visible_from objective0 waypoint13)
	(visible_from objective0 waypoint18)
	(visible_from objective0 waypoint20)
	(visible_from objective0 waypoint21)
	(visible_from objective0 waypoint25)
	(visible_from objective0 waypoint26)
	(visible_from objective0 waypoint27)
	(visible_from objective0 waypoint28)
)

(:goal (and
(communicated_soil_data waypoint0)
(communicated_rock_data waypoint21)
(communicated_image_data objective0 low_res)
	)
)
)
