(define (problem roverprob1) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 - Waypoint
	camera0 camera1 camera2 camera3 - Camera
	objective0 objective1 objective2 - Objective
	)
(:init
	(visible waypoint0 waypoint9)
	(visible waypoint9 waypoint0)
	(visible waypoint0 waypoint37)
	(visible waypoint37 waypoint0)
	(visible waypoint1 waypoint30)
	(visible waypoint30 waypoint1)
	(visible waypoint2 waypoint0)
	(visible waypoint0 waypoint2)
	(visible waypoint2 waypoint6)
	(visible waypoint6 waypoint2)
	(visible waypoint2 waypoint8)
	(visible waypoint8 waypoint2)
	(visible waypoint2 waypoint21)
	(visible waypoint21 waypoint2)
	(visible waypoint2 waypoint38)
	(visible waypoint38 waypoint2)
	(visible waypoint3 waypoint5)
	(visible waypoint5 waypoint3)
	(visible waypoint3 waypoint25)
	(visible waypoint25 waypoint3)
	(visible waypoint3 waypoint38)
	(visible waypoint38 waypoint3)
	(visible waypoint4 waypoint14)
	(visible waypoint14 waypoint4)
	(visible waypoint4 waypoint15)
	(visible waypoint15 waypoint4)
	(visible waypoint4 waypoint24)
	(visible waypoint24 waypoint4)
	(visible waypoint4 waypoint26)
	(visible waypoint26 waypoint4)
	(visible waypoint5 waypoint4)
	(visible waypoint4 waypoint5)
	(visible waypoint5 waypoint14)
	(visible waypoint14 waypoint5)
	(visible waypoint5 waypoint24)
	(visible waypoint24 waypoint5)
	(visible waypoint5 waypoint32)
	(visible waypoint32 waypoint5)
	(visible waypoint6 waypoint11)
	(visible waypoint11 waypoint6)
	(visible waypoint6 waypoint16)
	(visible waypoint16 waypoint6)
	(visible waypoint6 waypoint30)
	(visible waypoint30 waypoint6)
	(visible waypoint6 waypoint34)
	(visible waypoint34 waypoint6)
	(visible waypoint6 waypoint36)
	(visible waypoint36 waypoint6)
	(visible waypoint6 waypoint37)
	(visible waypoint37 waypoint6)
	(visible waypoint7 waypoint9)
	(visible waypoint9 waypoint7)
	(visible waypoint7 waypoint11)
	(visible waypoint11 waypoint7)
	(visible waypoint7 waypoint17)
	(visible waypoint17 waypoint7)
	(visible waypoint7 waypoint27)
	(visible waypoint27 waypoint7)
	(visible waypoint7 waypoint28)
	(visible waypoint28 waypoint7)
	(visible waypoint9 waypoint26)
	(visible waypoint26 waypoint9)
	(visible waypoint9 waypoint36)
	(visible waypoint36 waypoint9)
	(visible waypoint9 waypoint39)
	(visible waypoint39 waypoint9)
	(visible waypoint10 waypoint13)
	(visible waypoint13 waypoint10)
	(visible waypoint10 waypoint22)
	(visible waypoint22 waypoint10)
	(visible waypoint10 waypoint35)
	(visible waypoint35 waypoint10)
	(visible waypoint11 waypoint14)
	(visible waypoint14 waypoint11)
	(visible waypoint11 waypoint22)
	(visible waypoint22 waypoint11)
	(visible waypoint11 waypoint30)
	(visible waypoint30 waypoint11)
	(visible waypoint11 waypoint31)
	(visible waypoint31 waypoint11)
	(visible waypoint12 waypoint4)
	(visible waypoint4 waypoint12)
	(visible waypoint12 waypoint9)
	(visible waypoint9 waypoint12)
	(visible waypoint12 waypoint26)
	(visible waypoint26 waypoint12)
	(visible waypoint12 waypoint36)
	(visible waypoint36 waypoint12)
	(visible waypoint12 waypoint37)
	(visible waypoint37 waypoint12)
	(visible waypoint12 waypoint40)
	(visible waypoint40 waypoint12)
	(visible waypoint13 waypoint3)
	(visible waypoint3 waypoint13)
	(visible waypoint13 waypoint7)
	(visible waypoint7 waypoint13)
	(visible waypoint13 waypoint9)
	(visible waypoint9 waypoint13)
	(visible waypoint13 waypoint31)
	(visible waypoint31 waypoint13)
	(visible waypoint13 waypoint34)
	(visible waypoint34 waypoint13)
	(visible waypoint13 waypoint38)
	(visible waypoint38 waypoint13)
	(visible waypoint14 waypoint7)
	(visible waypoint7 waypoint14)
	(visible waypoint14 waypoint21)
	(visible waypoint21 waypoint14)
	(visible waypoint14 waypoint22)
	(visible waypoint22 waypoint14)
	(visible waypoint14 waypoint24)
	(visible waypoint24 waypoint14)
	(visible waypoint14 waypoint28)
	(visible waypoint28 waypoint14)
	(visible waypoint15 waypoint31)
	(visible waypoint31 waypoint15)
	(visible waypoint16 waypoint0)
	(visible waypoint0 waypoint16)
	(visible waypoint16 waypoint27)
	(visible waypoint27 waypoint16)
	(visible waypoint16 waypoint28)
	(visible waypoint28 waypoint16)
	(visible waypoint16 waypoint33)
	(visible waypoint33 waypoint16)
	(visible waypoint16 waypoint36)
	(visible waypoint36 waypoint16)
	(visible waypoint17 waypoint0)
	(visible waypoint0 waypoint17)
	(visible waypoint17 waypoint38)
	(visible waypoint38 waypoint17)
	(visible waypoint18 waypoint2)
	(visible waypoint2 waypoint18)
	(visible waypoint18 waypoint9)
	(visible waypoint9 waypoint18)
	(visible waypoint18 waypoint32)
	(visible waypoint32 waypoint18)
	(visible waypoint18 waypoint33)
	(visible waypoint33 waypoint18)
	(visible waypoint18 waypoint36)
	(visible waypoint36 waypoint18)
	(visible waypoint18 waypoint37)
	(visible waypoint37 waypoint18)
	(visible waypoint19 waypoint6)
	(visible waypoint6 waypoint19)
	(visible waypoint19 waypoint8)
	(visible waypoint8 waypoint19)
	(visible waypoint19 waypoint12)
	(visible waypoint12 waypoint19)
	(visible waypoint19 waypoint24)
	(visible waypoint24 waypoint19)
	(visible waypoint19 waypoint25)
	(visible waypoint25 waypoint19)
	(visible waypoint19 waypoint34)
	(visible waypoint34 waypoint19)
	(visible waypoint20 waypoint4)
	(visible waypoint4 waypoint20)
	(visible waypoint20 waypoint11)
	(visible waypoint11 waypoint20)
	(visible waypoint20 waypoint13)
	(visible waypoint13 waypoint20)
	(visible waypoint20 waypoint23)
	(visible waypoint23 waypoint20)
	(visible waypoint20 waypoint31)
	(visible waypoint31 waypoint20)
	(visible waypoint20 waypoint39)
	(visible waypoint39 waypoint20)
	(visible waypoint21 waypoint1)
	(visible waypoint1 waypoint21)
	(visible waypoint21 waypoint3)
	(visible waypoint3 waypoint21)
	(visible waypoint21 waypoint8)
	(visible waypoint8 waypoint21)
	(visible waypoint21 waypoint27)
	(visible waypoint27 waypoint21)
	(visible waypoint21 waypoint31)
	(visible waypoint31 waypoint21)
	(visible waypoint21 waypoint34)
	(visible waypoint34 waypoint21)
	(visible waypoint22 waypoint17)
	(visible waypoint17 waypoint22)
	(visible waypoint23 waypoint10)
	(visible waypoint10 waypoint23)
	(visible waypoint23 waypoint18)
	(visible waypoint18 waypoint23)
	(visible waypoint23 waypoint21)
	(visible waypoint21 waypoint23)
	(visible waypoint23 waypoint24)
	(visible waypoint24 waypoint23)
	(visible waypoint23 waypoint30)
	(visible waypoint30 waypoint23)
	(visible waypoint23 waypoint35)
	(visible waypoint35 waypoint23)
	(visible waypoint24 waypoint7)
	(visible waypoint7 waypoint24)
	(visible waypoint24 waypoint10)
	(visible waypoint10 waypoint24)
	(visible waypoint24 waypoint20)
	(visible waypoint20 waypoint24)
	(visible waypoint24 waypoint25)
	(visible waypoint25 waypoint24)
	(visible waypoint25 waypoint1)
	(visible waypoint1 waypoint25)
	(visible waypoint25 waypoint9)
	(visible waypoint9 waypoint25)
	(visible waypoint25 waypoint11)
	(visible waypoint11 waypoint25)
	(visible waypoint25 waypoint12)
	(visible waypoint12 waypoint25)
	(visible waypoint26 waypoint10)
	(visible waypoint10 waypoint26)
	(visible waypoint26 waypoint14)
	(visible waypoint14 waypoint26)
	(visible waypoint26 waypoint17)
	(visible waypoint17 waypoint26)
	(visible waypoint26 waypoint21)
	(visible waypoint21 waypoint26)
	(visible waypoint26 waypoint29)
	(visible waypoint29 waypoint26)
	(visible waypoint26 waypoint31)
	(visible waypoint31 waypoint26)
	(visible waypoint26 waypoint35)
	(visible waypoint35 waypoint26)
	(visible waypoint26 waypoint39)
	(visible waypoint39 waypoint26)
	(visible waypoint27 waypoint11)
	(visible waypoint11 waypoint27)
	(visible waypoint27 waypoint19)
	(visible waypoint19 waypoint27)
	(visible waypoint27 waypoint20)
	(visible waypoint20 waypoint27)
	(visible waypoint27 waypoint26)
	(visible waypoint26 waypoint27)
	(visible waypoint27 waypoint31)
	(visible waypoint31 waypoint27)
	(visible waypoint28 waypoint3)
	(visible waypoint3 waypoint28)
	(visible waypoint28 waypoint4)
	(visible waypoint4 waypoint28)
	(visible waypoint28 waypoint6)
	(visible waypoint6 waypoint28)
	(visible waypoint28 waypoint12)
	(visible waypoint12 waypoint28)
	(visible waypoint28 waypoint15)
	(visible waypoint15 waypoint28)
	(visible waypoint28 waypoint18)
	(visible waypoint18 waypoint28)
	(visible waypoint28 waypoint37)
	(visible waypoint37 waypoint28)
	(visible waypoint29 waypoint4)
	(visible waypoint4 waypoint29)
	(visible waypoint29 waypoint5)
	(visible waypoint5 waypoint29)
	(visible waypoint29 waypoint7)
	(visible waypoint7 waypoint29)
	(visible waypoint29 waypoint13)
	(visible waypoint13 waypoint29)
	(visible waypoint30 waypoint8)
	(visible waypoint8 waypoint30)
	(visible waypoint30 waypoint15)
	(visible waypoint15 waypoint30)
	(visible waypoint30 waypoint25)
	(visible waypoint25 waypoint30)
	(visible waypoint31 waypoint28)
	(visible waypoint28 waypoint31)
	(visible waypoint32 waypoint12)
	(visible waypoint12 waypoint32)
	(visible waypoint32 waypoint22)
	(visible waypoint22 waypoint32)
	(visible waypoint32 waypoint30)
	(visible waypoint30 waypoint32)
	(visible waypoint32 waypoint31)
	(visible waypoint31 waypoint32)
	(visible waypoint33 waypoint5)
	(visible waypoint5 waypoint33)
	(visible waypoint33 waypoint13)
	(visible waypoint13 waypoint33)
	(visible waypoint33 waypoint37)
	(visible waypoint37 waypoint33)
	(visible waypoint34 waypoint9)
	(visible waypoint9 waypoint34)
	(visible waypoint34 waypoint16)
	(visible waypoint16 waypoint34)
	(visible waypoint34 waypoint29)
	(visible waypoint29 waypoint34)
	(visible waypoint34 waypoint33)
	(visible waypoint33 waypoint34)
	(visible waypoint34 waypoint37)
	(visible waypoint37 waypoint34)
	(visible waypoint35 waypoint2)
	(visible waypoint2 waypoint35)
	(visible waypoint35 waypoint3)
	(visible waypoint3 waypoint35)
	(visible waypoint35 waypoint8)
	(visible waypoint8 waypoint35)
	(visible waypoint35 waypoint20)
	(visible waypoint20 waypoint35)
	(visible waypoint35 waypoint29)
	(visible waypoint29 waypoint35)
	(visible waypoint35 waypoint34)
	(visible waypoint34 waypoint35)
	(visible waypoint36 waypoint3)
	(visible waypoint3 waypoint36)
	(visible waypoint36 waypoint5)
	(visible waypoint5 waypoint36)
	(visible waypoint36 waypoint14)
	(visible waypoint14 waypoint36)
	(visible waypoint36 waypoint25)
	(visible waypoint25 waypoint36)
	(visible waypoint36 waypoint34)
	(visible waypoint34 waypoint36)
	(visible waypoint37 waypoint8)
	(visible waypoint8 waypoint37)
	(visible waypoint37 waypoint25)
	(visible waypoint25 waypoint37)
	(visible waypoint37 waypoint35)
	(visible waypoint35 waypoint37)
	(visible waypoint37 waypoint40)
	(visible waypoint40 waypoint37)
	(visible waypoint38 waypoint18)
	(visible waypoint18 waypoint38)
	(visible waypoint38 waypoint29)
	(visible waypoint29 waypoint38)
	(visible waypoint38 waypoint37)
	(visible waypoint37 waypoint38)
	(visible waypoint39 waypoint24)
	(visible waypoint24 waypoint39)
	(visible waypoint39 waypoint37)
	(visible waypoint37 waypoint39)
	(visible waypoint40 waypoint0)
	(visible waypoint0 waypoint40)
	(visible waypoint40 waypoint2)
	(visible waypoint2 waypoint40)
	(visible waypoint40 waypoint8)
	(visible waypoint8 waypoint40)
	(visible waypoint40 waypoint13)
	(visible waypoint13 waypoint40)
	(visible waypoint40 waypoint29)
	(visible waypoint29 waypoint40)
	(visible waypoint40 waypoint30)
	(visible waypoint30 waypoint40)
	(visible waypoint40 waypoint38)
	(visible waypoint38 waypoint40)
	(at_rock_sample waypoint0)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_soil_sample waypoint4)
	(at_rock_sample waypoint4)
	(at_soil_sample waypoint5)
	(at_rock_sample waypoint5)
	(at_soil_sample waypoint7)
	(at_soil_sample waypoint9)
	(at_rock_sample waypoint9)
	(at_soil_sample waypoint10)
	(at_soil_sample waypoint13)
	(at_rock_sample waypoint13)
	(at_rock_sample waypoint14)
	(at_soil_sample waypoint15)
	(at_rock_sample waypoint15)
	(at_rock_sample waypoint16)
	(at_soil_sample waypoint17)
	(at_rock_sample waypoint17)
	(at_rock_sample waypoint18)
	(at_soil_sample waypoint19)
	(at_rock_sample waypoint19)
	(at_soil_sample waypoint20)
	(at_rock_sample waypoint21)
	(at_soil_sample waypoint22)
	(at_soil_sample waypoint25)
	(at_soil_sample waypoint27)
	(at_soil_sample waypoint28)
	(at_rock_sample waypoint28)
	(at_soil_sample waypoint29)
	(at_rock_sample waypoint29)
	(at_rock_sample waypoint30)
	(at_rock_sample waypoint31)
	(at_rock_sample waypoint32)
	(at_soil_sample waypoint33)
	(at_rock_sample waypoint33)
	(at_rock_sample waypoint34)
	(at_soil_sample waypoint35)
	(at_rock_sample waypoint36)
	(at_soil_sample waypoint37)
	(at_rock_sample waypoint40)
	(at_lander general waypoint21)
	(channel_free general)
	(at rover0 waypoint25)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint25 waypoint1)
	(can_traverse rover0 waypoint1 waypoint25)
	(can_traverse rover0 waypoint25 waypoint9)
	(can_traverse rover0 waypoint9 waypoint25)
	(can_traverse rover0 waypoint25 waypoint12)
	(can_traverse rover0 waypoint12 waypoint25)
	(can_traverse rover0 waypoint25 waypoint24)
	(can_traverse rover0 waypoint24 waypoint25)
	(can_traverse rover0 waypoint25 waypoint36)
	(can_traverse rover0 waypoint36 waypoint25)
	(can_traverse rover0 waypoint25 waypoint37)
	(can_traverse rover0 waypoint37 waypoint25)
	(can_traverse rover0 waypoint1 waypoint21)
	(can_traverse rover0 waypoint21 waypoint1)
	(can_traverse rover0 waypoint1 waypoint30)
	(can_traverse rover0 waypoint30 waypoint1)
	(can_traverse rover0 waypoint9 waypoint0)
	(can_traverse rover0 waypoint0 waypoint9)
	(can_traverse rover0 waypoint9 waypoint18)
	(can_traverse rover0 waypoint18 waypoint9)
	(can_traverse rover0 waypoint9 waypoint26)
	(can_traverse rover0 waypoint26 waypoint9)
	(can_traverse rover0 waypoint9 waypoint34)
	(can_traverse rover0 waypoint34 waypoint9)
	(can_traverse rover0 waypoint9 waypoint39)
	(can_traverse rover0 waypoint39 waypoint9)
	(can_traverse rover0 waypoint12 waypoint28)
	(can_traverse rover0 waypoint28 waypoint12)
	(can_traverse rover0 waypoint12 waypoint40)
	(can_traverse rover0 waypoint40 waypoint12)
	(can_traverse rover0 waypoint24 waypoint4)
	(can_traverse rover0 waypoint4 waypoint24)
	(can_traverse rover0 waypoint24 waypoint5)
	(can_traverse rover0 waypoint5 waypoint24)
	(can_traverse rover0 waypoint24 waypoint10)
	(can_traverse rover0 waypoint10 waypoint24)
	(can_traverse rover0 waypoint24 waypoint14)
	(can_traverse rover0 waypoint14 waypoint24)
	(can_traverse rover0 waypoint24 waypoint19)
	(can_traverse rover0 waypoint19 waypoint24)
	(can_traverse rover0 waypoint24 waypoint23)
	(can_traverse rover0 waypoint23 waypoint24)
	(can_traverse rover0 waypoint36 waypoint3)
	(can_traverse rover0 waypoint3 waypoint36)
	(can_traverse rover0 waypoint36 waypoint16)
	(can_traverse rover0 waypoint16 waypoint36)
	(can_traverse rover0 waypoint37 waypoint8)
	(can_traverse rover0 waypoint8 waypoint37)
	(can_traverse rover0 waypoint37 waypoint33)
	(can_traverse rover0 waypoint33 waypoint37)
	(can_traverse rover0 waypoint37 waypoint35)
	(can_traverse rover0 waypoint35 waypoint37)
	(can_traverse rover0 waypoint37 waypoint38)
	(can_traverse rover0 waypoint38 waypoint37)
	(can_traverse rover0 waypoint21 waypoint27)
	(can_traverse rover0 waypoint27 waypoint21)
	(can_traverse rover0 waypoint21 waypoint31)
	(can_traverse rover0 waypoint31 waypoint21)
	(can_traverse rover0 waypoint30 waypoint6)
	(can_traverse rover0 waypoint6 waypoint30)
	(can_traverse rover0 waypoint30 waypoint11)
	(can_traverse rover0 waypoint11 waypoint30)
	(can_traverse rover0 waypoint30 waypoint15)
	(can_traverse rover0 waypoint15 waypoint30)
	(can_traverse rover0 waypoint30 waypoint32)
	(can_traverse rover0 waypoint32 waypoint30)
	(can_traverse rover0 waypoint0 waypoint2)
	(can_traverse rover0 waypoint2 waypoint0)
	(can_traverse rover0 waypoint0 waypoint17)
	(can_traverse rover0 waypoint17 waypoint0)
	(can_traverse rover0 waypoint34 waypoint13)
	(can_traverse rover0 waypoint13 waypoint34)
	(can_traverse rover0 waypoint34 waypoint29)
	(can_traverse rover0 waypoint29 waypoint34)
	(can_traverse rover0 waypoint39 waypoint20)
	(can_traverse rover0 waypoint20 waypoint39)
	(can_traverse rover0 waypoint28 waypoint7)
	(can_traverse rover0 waypoint7 waypoint28)
	(can_traverse rover0 waypoint10 waypoint22)
	(can_traverse rover0 waypoint22 waypoint10)
	(at rover1 waypoint16)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_rock_analysis rover1)
	(can_traverse rover1 waypoint16 waypoint0)
	(can_traverse rover1 waypoint0 waypoint16)
	(can_traverse rover1 waypoint16 waypoint33)
	(can_traverse rover1 waypoint33 waypoint16)
	(can_traverse rover1 waypoint16 waypoint36)
	(can_traverse rover1 waypoint36 waypoint16)
	(can_traverse rover1 waypoint0 waypoint2)
	(can_traverse rover1 waypoint2 waypoint0)
	(can_traverse rover1 waypoint0 waypoint9)
	(can_traverse rover1 waypoint9 waypoint0)
	(can_traverse rover1 waypoint0 waypoint40)
	(can_traverse rover1 waypoint40 waypoint0)
	(can_traverse rover1 waypoint33 waypoint13)
	(can_traverse rover1 waypoint13 waypoint33)
	(can_traverse rover1 waypoint33 waypoint18)
	(can_traverse rover1 waypoint18 waypoint33)
	(can_traverse rover1 waypoint33 waypoint37)
	(can_traverse rover1 waypoint37 waypoint33)
	(can_traverse rover1 waypoint36 waypoint3)
	(can_traverse rover1 waypoint3 waypoint36)
	(can_traverse rover1 waypoint36 waypoint5)
	(can_traverse rover1 waypoint5 waypoint36)
	(can_traverse rover1 waypoint36 waypoint6)
	(can_traverse rover1 waypoint6 waypoint36)
	(can_traverse rover1 waypoint36 waypoint12)
	(can_traverse rover1 waypoint12 waypoint36)
	(can_traverse rover1 waypoint36 waypoint14)
	(can_traverse rover1 waypoint14 waypoint36)
	(can_traverse rover1 waypoint2 waypoint8)
	(can_traverse rover1 waypoint8 waypoint2)
	(can_traverse rover1 waypoint2 waypoint21)
	(can_traverse rover1 waypoint21 waypoint2)
	(can_traverse rover1 waypoint2 waypoint35)
	(can_traverse rover1 waypoint35 waypoint2)
	(can_traverse rover1 waypoint2 waypoint38)
	(can_traverse rover1 waypoint38 waypoint2)
	(can_traverse rover1 waypoint9 waypoint25)
	(can_traverse rover1 waypoint25 waypoint9)
	(can_traverse rover1 waypoint9 waypoint26)
	(can_traverse rover1 waypoint26 waypoint9)
	(can_traverse rover1 waypoint9 waypoint34)
	(can_traverse rover1 waypoint34 waypoint9)
	(can_traverse rover1 waypoint9 waypoint39)
	(can_traverse rover1 waypoint39 waypoint9)
	(can_traverse rover1 waypoint40 waypoint29)
	(can_traverse rover1 waypoint29 waypoint40)
	(can_traverse rover1 waypoint40 waypoint30)
	(can_traverse rover1 waypoint30 waypoint40)
	(can_traverse rover1 waypoint13 waypoint10)
	(can_traverse rover1 waypoint10 waypoint13)
	(can_traverse rover1 waypoint13 waypoint20)
	(can_traverse rover1 waypoint20 waypoint13)
	(can_traverse rover1 waypoint13 waypoint31)
	(can_traverse rover1 waypoint31 waypoint13)
	(can_traverse rover1 waypoint18 waypoint23)
	(can_traverse rover1 waypoint23 waypoint18)
	(can_traverse rover1 waypoint18 waypoint28)
	(can_traverse rover1 waypoint28 waypoint18)
	(can_traverse rover1 waypoint18 waypoint32)
	(can_traverse rover1 waypoint32 waypoint18)
	(can_traverse rover1 waypoint5 waypoint4)
	(can_traverse rover1 waypoint4 waypoint5)
	(can_traverse rover1 waypoint5 waypoint24)
	(can_traverse rover1 waypoint24 waypoint5)
	(can_traverse rover1 waypoint6 waypoint11)
	(can_traverse rover1 waypoint11 waypoint6)
	(can_traverse rover1 waypoint6 waypoint19)
	(can_traverse rover1 waypoint19 waypoint6)
	(can_traverse rover1 waypoint14 waypoint7)
	(can_traverse rover1 waypoint7 waypoint14)
	(can_traverse rover1 waypoint14 waypoint22)
	(can_traverse rover1 waypoint22 waypoint14)
	(can_traverse rover1 waypoint21 waypoint1)
	(can_traverse rover1 waypoint1 waypoint21)
	(can_traverse rover1 waypoint21 waypoint27)
	(can_traverse rover1 waypoint27 waypoint21)
	(can_traverse rover1 waypoint38 waypoint17)
	(can_traverse rover1 waypoint17 waypoint38)
	(can_traverse rover1 waypoint30 waypoint15)
	(can_traverse rover1 waypoint15 waypoint30)
	(at rover2 waypoint31)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint31 waypoint11)
	(can_traverse rover2 waypoint11 waypoint31)
	(can_traverse rover2 waypoint31 waypoint13)
	(can_traverse rover2 waypoint13 waypoint31)
	(can_traverse rover2 waypoint31 waypoint20)
	(can_traverse rover2 waypoint20 waypoint31)
	(can_traverse rover2 waypoint31 waypoint21)
	(can_traverse rover2 waypoint21 waypoint31)
	(can_traverse rover2 waypoint31 waypoint26)
	(can_traverse rover2 waypoint26 waypoint31)
	(can_traverse rover2 waypoint31 waypoint27)
	(can_traverse rover2 waypoint27 waypoint31)
	(can_traverse rover2 waypoint31 waypoint28)
	(can_traverse rover2 waypoint28 waypoint31)
	(can_traverse rover2 waypoint31 waypoint32)
	(can_traverse rover2 waypoint32 waypoint31)
	(can_traverse rover2 waypoint11 waypoint6)
	(can_traverse rover2 waypoint6 waypoint11)
	(can_traverse rover2 waypoint11 waypoint7)
	(can_traverse rover2 waypoint7 waypoint11)
	(can_traverse rover2 waypoint11 waypoint14)
	(can_traverse rover2 waypoint14 waypoint11)
	(can_traverse rover2 waypoint11 waypoint25)
	(can_traverse rover2 waypoint25 waypoint11)
	(can_traverse rover2 waypoint13 waypoint3)
	(can_traverse rover2 waypoint3 waypoint13)
	(can_traverse rover2 waypoint13 waypoint9)
	(can_traverse rover2 waypoint9 waypoint13)
	(can_traverse rover2 waypoint13 waypoint10)
	(can_traverse rover2 waypoint10 waypoint13)
	(can_traverse rover2 waypoint13 waypoint29)
	(can_traverse rover2 waypoint29 waypoint13)
	(can_traverse rover2 waypoint13 waypoint34)
	(can_traverse rover2 waypoint34 waypoint13)
	(can_traverse rover2 waypoint13 waypoint38)
	(can_traverse rover2 waypoint38 waypoint13)
	(can_traverse rover2 waypoint20 waypoint4)
	(can_traverse rover2 waypoint4 waypoint20)
	(can_traverse rover2 waypoint20 waypoint23)
	(can_traverse rover2 waypoint23 waypoint20)
	(can_traverse rover2 waypoint20 waypoint24)
	(can_traverse rover2 waypoint24 waypoint20)
	(can_traverse rover2 waypoint20 waypoint35)
	(can_traverse rover2 waypoint35 waypoint20)
	(can_traverse rover2 waypoint21 waypoint1)
	(can_traverse rover2 waypoint1 waypoint21)
	(can_traverse rover2 waypoint21 waypoint8)
	(can_traverse rover2 waypoint8 waypoint21)
	(can_traverse rover2 waypoint26 waypoint17)
	(can_traverse rover2 waypoint17 waypoint26)
	(can_traverse rover2 waypoint26 waypoint39)
	(can_traverse rover2 waypoint39 waypoint26)
	(can_traverse rover2 waypoint27 waypoint16)
	(can_traverse rover2 waypoint16 waypoint27)
	(can_traverse rover2 waypoint27 waypoint19)
	(can_traverse rover2 waypoint19 waypoint27)
	(can_traverse rover2 waypoint28 waypoint12)
	(can_traverse rover2 waypoint12 waypoint28)
	(can_traverse rover2 waypoint28 waypoint15)
	(can_traverse rover2 waypoint15 waypoint28)
	(can_traverse rover2 waypoint28 waypoint18)
	(can_traverse rover2 waypoint18 waypoint28)
	(can_traverse rover2 waypoint32 waypoint22)
	(can_traverse rover2 waypoint22 waypoint32)
	(can_traverse rover2 waypoint32 waypoint30)
	(can_traverse rover2 waypoint30 waypoint32)
	(can_traverse rover2 waypoint6 waypoint37)
	(can_traverse rover2 waypoint37 waypoint6)
	(can_traverse rover2 waypoint14 waypoint5)
	(can_traverse rover2 waypoint5 waypoint14)
	(can_traverse rover2 waypoint14 waypoint36)
	(can_traverse rover2 waypoint36 waypoint14)
	(can_traverse rover2 waypoint9 waypoint0)
	(can_traverse rover2 waypoint0 waypoint9)
	(can_traverse rover2 waypoint29 waypoint40)
	(can_traverse rover2 waypoint40 waypoint29)
	(can_traverse rover2 waypoint34 waypoint33)
	(can_traverse rover2 waypoint33 waypoint34)
	(can_traverse rover2 waypoint38 waypoint2)
	(can_traverse rover2 waypoint2 waypoint38)
	(at rover3 waypoint38)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_rock_analysis rover3)
	(can_traverse rover3 waypoint38 waypoint2)
	(can_traverse rover3 waypoint2 waypoint38)
	(can_traverse rover3 waypoint38 waypoint13)
	(can_traverse rover3 waypoint13 waypoint38)
	(can_traverse rover3 waypoint38 waypoint17)
	(can_traverse rover3 waypoint17 waypoint38)
	(can_traverse rover3 waypoint38 waypoint18)
	(can_traverse rover3 waypoint18 waypoint38)
	(can_traverse rover3 waypoint38 waypoint29)
	(can_traverse rover3 waypoint29 waypoint38)
	(can_traverse rover3 waypoint38 waypoint37)
	(can_traverse rover3 waypoint37 waypoint38)
	(can_traverse rover3 waypoint2 waypoint0)
	(can_traverse rover3 waypoint0 waypoint2)
	(can_traverse rover3 waypoint2 waypoint6)
	(can_traverse rover3 waypoint6 waypoint2)
	(can_traverse rover3 waypoint2 waypoint8)
	(can_traverse rover3 waypoint8 waypoint2)
	(can_traverse rover3 waypoint2 waypoint21)
	(can_traverse rover3 waypoint21 waypoint2)
	(can_traverse rover3 waypoint2 waypoint40)
	(can_traverse rover3 waypoint40 waypoint2)
	(can_traverse rover3 waypoint13 waypoint3)
	(can_traverse rover3 waypoint3 waypoint13)
	(can_traverse rover3 waypoint13 waypoint7)
	(can_traverse rover3 waypoint7 waypoint13)
	(can_traverse rover3 waypoint13 waypoint9)
	(can_traverse rover3 waypoint9 waypoint13)
	(can_traverse rover3 waypoint13 waypoint10)
	(can_traverse rover3 waypoint10 waypoint13)
	(can_traverse rover3 waypoint13 waypoint20)
	(can_traverse rover3 waypoint20 waypoint13)
	(can_traverse rover3 waypoint13 waypoint31)
	(can_traverse rover3 waypoint31 waypoint13)
	(can_traverse rover3 waypoint13 waypoint34)
	(can_traverse rover3 waypoint34 waypoint13)
	(can_traverse rover3 waypoint17 waypoint22)
	(can_traverse rover3 waypoint22 waypoint17)
	(can_traverse rover3 waypoint17 waypoint26)
	(can_traverse rover3 waypoint26 waypoint17)
	(can_traverse rover3 waypoint18 waypoint23)
	(can_traverse rover3 waypoint23 waypoint18)
	(can_traverse rover3 waypoint18 waypoint32)
	(can_traverse rover3 waypoint32 waypoint18)
	(can_traverse rover3 waypoint18 waypoint33)
	(can_traverse rover3 waypoint33 waypoint18)
	(can_traverse rover3 waypoint29 waypoint4)
	(can_traverse rover3 waypoint4 waypoint29)
	(can_traverse rover3 waypoint29 waypoint35)
	(can_traverse rover3 waypoint35 waypoint29)
	(can_traverse rover3 waypoint37 waypoint12)
	(can_traverse rover3 waypoint12 waypoint37)
	(can_traverse rover3 waypoint37 waypoint25)
	(can_traverse rover3 waypoint25 waypoint37)
	(can_traverse rover3 waypoint37 waypoint28)
	(can_traverse rover3 waypoint28 waypoint37)
	(can_traverse rover3 waypoint0 waypoint16)
	(can_traverse rover3 waypoint16 waypoint0)
	(can_traverse rover3 waypoint6 waypoint11)
	(can_traverse rover3 waypoint11 waypoint6)
	(can_traverse rover3 waypoint6 waypoint36)
	(can_traverse rover3 waypoint36 waypoint6)
	(can_traverse rover3 waypoint8 waypoint30)
	(can_traverse rover3 waypoint30 waypoint8)
	(can_traverse rover3 waypoint21 waypoint1)
	(can_traverse rover3 waypoint1 waypoint21)
	(can_traverse rover3 waypoint21 waypoint14)
	(can_traverse rover3 waypoint14 waypoint21)
	(can_traverse rover3 waypoint21 waypoint27)
	(can_traverse rover3 waypoint27 waypoint21)
	(can_traverse rover3 waypoint3 waypoint5)
	(can_traverse rover3 waypoint5 waypoint3)
	(can_traverse rover3 waypoint9 waypoint39)
	(can_traverse rover3 waypoint39 waypoint9)
	(can_traverse rover3 waypoint10 waypoint24)
	(can_traverse rover3 waypoint24 waypoint10)
	(can_traverse rover3 waypoint31 waypoint15)
	(can_traverse rover3 waypoint15 waypoint31)
	(can_traverse rover3 waypoint34 waypoint19)
	(can_traverse rover3 waypoint19 waypoint34)
	(at rover4 waypoint39)
	(available rover4)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_soil_analysis rover4)
	(equipped_for_imaging rover4)
	(can_traverse rover4 waypoint39 waypoint9)
	(can_traverse rover4 waypoint9 waypoint39)
	(can_traverse rover4 waypoint39 waypoint20)
	(can_traverse rover4 waypoint20 waypoint39)
	(can_traverse rover4 waypoint39 waypoint24)
	(can_traverse rover4 waypoint24 waypoint39)
	(can_traverse rover4 waypoint39 waypoint26)
	(can_traverse rover4 waypoint26 waypoint39)
	(can_traverse rover4 waypoint9 waypoint0)
	(can_traverse rover4 waypoint0 waypoint9)
	(can_traverse rover4 waypoint9 waypoint12)
	(can_traverse rover4 waypoint12 waypoint9)
	(can_traverse rover4 waypoint9 waypoint13)
	(can_traverse rover4 waypoint13 waypoint9)
	(can_traverse rover4 waypoint9 waypoint18)
	(can_traverse rover4 waypoint18 waypoint9)
	(can_traverse rover4 waypoint9 waypoint25)
	(can_traverse rover4 waypoint25 waypoint9)
	(can_traverse rover4 waypoint20 waypoint23)
	(can_traverse rover4 waypoint23 waypoint20)
	(can_traverse rover4 waypoint24 waypoint4)
	(can_traverse rover4 waypoint4 waypoint24)
	(can_traverse rover4 waypoint24 waypoint14)
	(can_traverse rover4 waypoint14 waypoint24)
	(can_traverse rover4 waypoint24 waypoint19)
	(can_traverse rover4 waypoint19 waypoint24)
	(can_traverse rover4 waypoint26 waypoint10)
	(can_traverse rover4 waypoint10 waypoint26)
	(can_traverse rover4 waypoint26 waypoint21)
	(can_traverse rover4 waypoint21 waypoint26)
	(can_traverse rover4 waypoint26 waypoint29)
	(can_traverse rover4 waypoint29 waypoint26)
	(can_traverse rover4 waypoint26 waypoint31)
	(can_traverse rover4 waypoint31 waypoint26)
	(can_traverse rover4 waypoint26 waypoint35)
	(can_traverse rover4 waypoint35 waypoint26)
	(can_traverse rover4 waypoint0 waypoint17)
	(can_traverse rover4 waypoint17 waypoint0)
	(can_traverse rover4 waypoint0 waypoint37)
	(can_traverse rover4 waypoint37 waypoint0)
	(can_traverse rover4 waypoint12 waypoint32)
	(can_traverse rover4 waypoint32 waypoint12)
	(can_traverse rover4 waypoint12 waypoint36)
	(can_traverse rover4 waypoint36 waypoint12)
	(can_traverse rover4 waypoint12 waypoint40)
	(can_traverse rover4 waypoint40 waypoint12)
	(can_traverse rover4 waypoint13 waypoint3)
	(can_traverse rover4 waypoint3 waypoint13)
	(can_traverse rover4 waypoint13 waypoint7)
	(can_traverse rover4 waypoint7 waypoint13)
	(can_traverse rover4 waypoint13 waypoint34)
	(can_traverse rover4 waypoint34 waypoint13)
	(can_traverse rover4 waypoint18 waypoint2)
	(can_traverse rover4 waypoint2 waypoint18)
	(can_traverse rover4 waypoint18 waypoint28)
	(can_traverse rover4 waypoint28 waypoint18)
	(can_traverse rover4 waypoint18 waypoint33)
	(can_traverse rover4 waypoint33 waypoint18)
	(can_traverse rover4 waypoint18 waypoint38)
	(can_traverse rover4 waypoint38 waypoint18)
	(can_traverse rover4 waypoint25 waypoint1)
	(can_traverse rover4 waypoint1 waypoint25)
	(can_traverse rover4 waypoint25 waypoint11)
	(can_traverse rover4 waypoint11 waypoint25)
	(can_traverse rover4 waypoint23 waypoint30)
	(can_traverse rover4 waypoint30 waypoint23)
	(can_traverse rover4 waypoint4 waypoint5)
	(can_traverse rover4 waypoint5 waypoint4)
	(can_traverse rover4 waypoint4 waypoint15)
	(can_traverse rover4 waypoint15 waypoint4)
	(can_traverse rover4 waypoint14 waypoint22)
	(can_traverse rover4 waypoint22 waypoint14)
	(can_traverse rover4 waypoint19 waypoint6)
	(can_traverse rover4 waypoint6 waypoint19)
	(can_traverse rover4 waypoint19 waypoint8)
	(can_traverse rover4 waypoint8 waypoint19)
	(can_traverse rover4 waypoint19 waypoint27)
	(can_traverse rover4 waypoint27 waypoint19)
	(can_traverse rover4 waypoint34 waypoint16)
	(can_traverse rover4 waypoint16 waypoint34)
	(at rover5 waypoint7)
	(available rover5)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_soil_analysis rover5)
	(equipped_for_rock_analysis rover5)
	(equipped_for_imaging rover5)
	(can_traverse rover5 waypoint7 waypoint9)
	(can_traverse rover5 waypoint9 waypoint7)
	(can_traverse rover5 waypoint7 waypoint14)
	(can_traverse rover5 waypoint14 waypoint7)
	(can_traverse rover5 waypoint7 waypoint24)
	(can_traverse rover5 waypoint24 waypoint7)
	(can_traverse rover5 waypoint7 waypoint27)
	(can_traverse rover5 waypoint27 waypoint7)
	(can_traverse rover5 waypoint7 waypoint29)
	(can_traverse rover5 waypoint29 waypoint7)
	(can_traverse rover5 waypoint9 waypoint0)
	(can_traverse rover5 waypoint0 waypoint9)
	(can_traverse rover5 waypoint9 waypoint13)
	(can_traverse rover5 waypoint13 waypoint9)
	(can_traverse rover5 waypoint9 waypoint25)
	(can_traverse rover5 waypoint25 waypoint9)
	(can_traverse rover5 waypoint9 waypoint26)
	(can_traverse rover5 waypoint26 waypoint9)
	(can_traverse rover5 waypoint9 waypoint34)
	(can_traverse rover5 waypoint34 waypoint9)
	(can_traverse rover5 waypoint9 waypoint36)
	(can_traverse rover5 waypoint36 waypoint9)
	(can_traverse rover5 waypoint9 waypoint39)
	(can_traverse rover5 waypoint39 waypoint9)
	(can_traverse rover5 waypoint14 waypoint4)
	(can_traverse rover5 waypoint4 waypoint14)
	(can_traverse rover5 waypoint14 waypoint5)
	(can_traverse rover5 waypoint5 waypoint14)
	(can_traverse rover5 waypoint14 waypoint22)
	(can_traverse rover5 waypoint22 waypoint14)
	(can_traverse rover5 waypoint14 waypoint28)
	(can_traverse rover5 waypoint28 waypoint14)
	(can_traverse rover5 waypoint24 waypoint19)
	(can_traverse rover5 waypoint19 waypoint24)
	(can_traverse rover5 waypoint24 waypoint20)
	(can_traverse rover5 waypoint20 waypoint24)
	(can_traverse rover5 waypoint27 waypoint11)
	(can_traverse rover5 waypoint11 waypoint27)
	(can_traverse rover5 waypoint27 waypoint16)
	(can_traverse rover5 waypoint16 waypoint27)
	(can_traverse rover5 waypoint27 waypoint21)
	(can_traverse rover5 waypoint21 waypoint27)
	(can_traverse rover5 waypoint27 waypoint31)
	(can_traverse rover5 waypoint31 waypoint27)
	(can_traverse rover5 waypoint29 waypoint35)
	(can_traverse rover5 waypoint35 waypoint29)
	(can_traverse rover5 waypoint29 waypoint38)
	(can_traverse rover5 waypoint38 waypoint29)
	(can_traverse rover5 waypoint0 waypoint2)
	(can_traverse rover5 waypoint2 waypoint0)
	(can_traverse rover5 waypoint0 waypoint17)
	(can_traverse rover5 waypoint17 waypoint0)
	(can_traverse rover5 waypoint0 waypoint40)
	(can_traverse rover5 waypoint40 waypoint0)
	(can_traverse rover5 waypoint13 waypoint10)
	(can_traverse rover5 waypoint10 waypoint13)
	(can_traverse rover5 waypoint25 waypoint1)
	(can_traverse rover5 waypoint1 waypoint25)
	(can_traverse rover5 waypoint25 waypoint3)
	(can_traverse rover5 waypoint3 waypoint25)
	(can_traverse rover5 waypoint25 waypoint12)
	(can_traverse rover5 waypoint12 waypoint25)
	(can_traverse rover5 waypoint25 waypoint30)
	(can_traverse rover5 waypoint30 waypoint25)
	(can_traverse rover5 waypoint25 waypoint37)
	(can_traverse rover5 waypoint37 waypoint25)
	(can_traverse rover5 waypoint34 waypoint6)
	(can_traverse rover5 waypoint6 waypoint34)
	(can_traverse rover5 waypoint34 waypoint33)
	(can_traverse rover5 waypoint33 waypoint34)
	(can_traverse rover5 waypoint22 waypoint32)
	(can_traverse rover5 waypoint32 waypoint22)
	(can_traverse rover5 waypoint28 waypoint15)
	(can_traverse rover5 waypoint15 waypoint28)
	(can_traverse rover5 waypoint28 waypoint18)
	(can_traverse rover5 waypoint18 waypoint28)
	(on_board camera0 rover4)
	(calibration_target camera0 objective1)
	(supports camera0 colour)
	(on_board camera1 rover2)
	(calibration_target camera1 objective2)
	(supports camera1 colour)
	(supports camera1 low_res)
	(on_board camera2 rover0)
	(calibration_target camera2 objective0)
	(supports camera2 colour)
	(supports camera2 high_res)
	(supports camera2 low_res)
	(on_board camera3 rover5)
	(calibration_target camera3 objective1)
	(supports camera3 colour)
	(supports camera3 low_res)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint1)
	(visible_from objective0 waypoint3)
	(visible_from objective0 waypoint4)
	(visible_from objective0 waypoint6)
	(visible_from objective0 waypoint7)
	(visible_from objective0 waypoint9)
	(visible_from objective0 waypoint10)
	(visible_from objective0 waypoint11)
	(visible_from objective0 waypoint19)
	(visible_from objective0 waypoint20)
	(visible_from objective0 waypoint23)
	(visible_from objective0 waypoint25)
	(visible_from objective0 waypoint29)
	(visible_from objective0 waypoint30)
	(visible_from objective0 waypoint31)
	(visible_from objective0 waypoint32)
	(visible_from objective0 waypoint33)
	(visible_from objective0 waypoint35)
	(visible_from objective0 waypoint37)
	(visible_from objective0 waypoint38)
	(visible_from objective0 waypoint39)
	(visible_from objective1 waypoint1)
	(visible_from objective1 waypoint3)
	(visible_from objective1 waypoint4)
	(visible_from objective1 waypoint5)
	(visible_from objective1 waypoint7)
	(visible_from objective1 waypoint8)
	(visible_from objective1 waypoint11)
	(visible_from objective1 waypoint12)
	(visible_from objective1 waypoint13)
	(visible_from objective1 waypoint14)
	(visible_from objective1 waypoint15)
	(visible_from objective1 waypoint16)
	(visible_from objective1 waypoint17)
	(visible_from objective1 waypoint18)
	(visible_from objective1 waypoint21)
	(visible_from objective1 waypoint23)
	(visible_from objective1 waypoint24)
	(visible_from objective1 waypoint26)
	(visible_from objective1 waypoint27)
	(visible_from objective1 waypoint28)
	(visible_from objective1 waypoint30)
	(visible_from objective1 waypoint31)
	(visible_from objective1 waypoint34)
	(visible_from objective1 waypoint36)
	(visible_from objective1 waypoint38)
	(visible_from objective1 waypoint40)
	(visible_from objective2 waypoint0)
	(visible_from objective2 waypoint3)
	(visible_from objective2 waypoint5)
	(visible_from objective2 waypoint6)
	(visible_from objective2 waypoint12)
	(visible_from objective2 waypoint17)
	(visible_from objective2 waypoint18)
	(visible_from objective2 waypoint26)
)

(:goal (and
(communicated_soil_data waypoint15)
(communicated_rock_data waypoint34)
(communicated_image_data objective0 low_res)
	)
)
)
