(define (problem BW-8-10-34)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 - block)
    (:init
        (handempty)
        (on b1 b3)
        (on-table b2)
        (on-table b3)
        (on b4 b2)
        (on b5 b6)
        (on b6 b8)
        (on b7 b5)
        (on b8 b1)
        (clear b4)
        (clear b7)
    )
    (:goal
        (and
            (on b1 b7)
            (on-table b2)
            (on-table b3)
            (on b4 b3)
            (on b5 b8)
            (on b6 b4)
            (on-table b7)
            (on b8 b2)
        )
    )
)