(define (problem BW-9-10-10)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 - block)
    (:init
        (handempty)
        (on b1 b8)
        (on b2 b1)
        (on b3 b5)
        (on-table b4)
        (on b5 b9)
        (on-table b6)
        (on b7 b6)
        (on-table b8)
        (on b9 b2)
        (clear b3)
        (clear b4)
        (clear b7)
    )
    (:goal
        (and
            (on-table b1)
            (on b2 b8)
            (on b3 b5)
            (on-table b4)
            (on b5 b9)
            (on b6 b7)
            (on-table b7)
            (on b8 b4)
            (on-table b9)
        )
    )
)