(define (problem BW-10-10-23)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
    (:init
        (handempty)
        (on b1 b3)
        (on b2 b6)
        (on b3 b8)
        (on-table b4)
        (on b5 b1)
        (on b6 b4)
        (on b7 b10)
        (on-table b8)
        (on-table b9)
        (on b10 b9)
        (clear b2)
        (clear b5)
        (clear b7)
    )
    (:goal
        (and
            (on b1 b9)
            (on b2 b8)
            (on b3 b10)
            (on-table b4)
            (on b5 b2)
            (on b6 b5)
            (on b7 b3)
            (on-table b8)
            (on-table b9)
            (on b10 b6)
        )
    )
)