(define (problem BW-7-10-4)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 - block)
    (:init
        (handempty)
        (on b1 b4)
        (on-table b2)
        (on b3 b1)
        (on b4 b6)
        (on b5 b2)
        (on b6 b7)
        (on b7 b5)
        (clear b3)
    )
    (:goal
        (and
            (on-table b1)
            (on b2 b3)
            (on b3 b1)
            (on b4 b2)
            (on-table b5)
            (on b6 b7)
            (on b7 b4)
        )
    )
)