(define (problem BW-9-10-98)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b8)
        (on-table b3)
        (on b4 b3)
        (on b5 b7)
        (on b6 b2)
        (on-table b7)
        (on b8 b5)
        (on b9 b1)
        (clear b4)
        (clear b6)
        (clear b9)
    )
    (:goal
        (and
            (on-table b1)
            (on b2 b1)
            (on-table b3)
            (on b4 b5)
            (on-table b5)
            (on b6 b9)
            (on b7 b2)
            (on b8 b4)
            (on b9 b7)
        )
    )
)