(define (problem BW-8-10-4)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 - block)
    (:init
        (handempty)
        (on b1 b6)
        (on b2 b7)
        (on b3 b1)
        (on-table b4)
        (on-table b5)
        (on-table b6)
        (on b7 b5)
        (on b8 b3)
        (clear b2)
        (clear b4)
        (clear b8)
    )
    (:goal
        (and
            (on b1 b6)
            (on b2 b4)
            (on-table b3)
            (on b4 b1)
            (on-table b5)
            (on b6 b8)
            (on b7 b2)
            (on b8 b5)
        )
    )
)