(define (problem BW-10-10-99)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b1)
        (on-table b3)
        (on b4 b8)
        (on b5 b3)
        (on b6 b7)
        (on b7 b5)
        (on b8 b10)
        (on b9 b6)
        (on-table b10)
        (clear b2)
        (clear b4)
        (clear b9)
    )
    (:goal
        (and
            (on-table b1)
            (on-table b2)
            (on-table b3)
            (on-table b4)
            (on b5 b2)
            (on b6 b4)
            (on b7 b5)
            (on b8 b3)
            (on b9 b7)
            (on-table b10)
        )
    )
)