(define (problem BW-7-10-28)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 - block)
    (:init
        (handempty)
        (on b1 b6)
        (on-table b2)
        (on b3 b1)
        (on b4 b7)
        (on b5 b2)
        (on b6 b4)
        (on b7 b5)
        (clear b3)
    )
    (:goal
        (and
            (on-table b1)
            (on-table b2)
            (on b3 b1)
            (on-table b4)
            (on b5 b4)
            (on-table b6)
            (on b7 b5)
        )
    )
)