(define (problem BW-7-10-69)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 - block)
    (:init
        (handempty)
        (on b1 b5)
        (on b2 b1)
        (on b3 b2)
        (on b4 b3)
        (on-table b5)
        (on b6 b7)
        (on-table b7)
        (clear b4)
        (clear b6)
    )
    (:goal
        (and
            (on b1 b7)
            (on-table b2)
            (on b3 b6)
            (on b4 b5)
            (on-table b5)
            (on b6 b1)
            (on b7 b2)
        )
    )
)