(define (problem BW-8-10-64)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 - block)
    (:init
        (handempty)
        (on b1 b6)
        (on b2 b8)
        (on b3 b2)
        (on b4 b7)
        (on b5 b3)
        (on b6 b4)
        (on-table b7)
        (on-table b8)
        (clear b1)
        (clear b5)
    )
    (:goal
        (and
            (on b1 b6)
            (on-table b2)
            (on b3 b4)
            (on b4 b7)
            (on b5 b1)
            (on b6 b3)
            (on b7 b2)
            (on b8 b5)
        )
    )
)