(define (problem BW-7-10-48)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 - block)
    (:init
        (handempty)
        (on b1 b5)
        (on b2 b7)
        (on b3 b2)
        (on b4 b6)
        (on-table b5)
        (on-table b6)
        (on b7 b4)
        (clear b1)
        (clear b3)
    )
    (:goal
        (and
            (on b1 b4)
            (on b2 b5)
            (on b3 b2)
            (on b4 b7)
            (on b5 b6)
            (on-table b6)
            (on-table b7)
        )
    )
)