(define (problem BW-9-10-44)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 - block)
    (:init
        (handempty)
        (on b1 b5)
        (on-table b2)
        (on-table b3)
        (on b4 b7)
        (on-table b5)
        (on b6 b3)
        (on b7 b8)
        (on-table b8)
        (on b9 b2)
        (clear b1)
        (clear b4)
        (clear b6)
        (clear b9)
    )
    (:goal
        (and
            (on b1 b4)
            (on b2 b3)
            (on b3 b7)
            (on b4 b9)
            (on b5 b6)
            (on-table b6)
            (on b7 b8)
            (on-table b8)
            (on-table b9)
        )
    )
)