(define (problem BW-11-10-44)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on b1 b2)
        (on-table b2)
        (on b3 b6)
        (on b4 b7)
        (on b5 b9)
        (on b6 b8)
        (on-table b7)
        (on-table b8)
        (on b9 b4)
        (on-table b10)
        (on b11 b5)
        (clear b1)
        (clear b3)
        (clear b10)
        (clear b11)
    )
    (:goal
        (and
            (on b1 b5)
            (on b2 b8)
            (on b3 b11)
            (on-table b4)
            (on-table b5)
            (on b6 b1)
            (on-table b7)
            (on b8 b10)
            (on b9 b3)
            (on-table b10)
            (on b11 b4)
        )
    )
)