(define (problem BW-9-10-43)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 - block)
    (:init
        (handempty)
        (on-table b1)
        (on-table b2)
        (on b3 b2)
        (on b4 b1)
        (on b5 b3)
        (on b6 b7)
        (on b7 b5)
        (on-table b8)
        (on-table b9)
        (clear b4)
        (clear b6)
        (clear b8)
        (clear b9)
    )
    (:goal
        (and
            (on b1 b4)
            (on b2 b8)
            (on b3 b9)
            (on b4 b5)
            (on b5 b7)
            (on b6 b2)
            (on-table b7)
            (on b8 b1)
            (on-table b9)
        )
    )
)