(define (problem BW-10-10-14)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
    (:init
        (handempty)
        (on b1 b3)
        (on b2 b8)
        (on b3 b2)
        (on b4 b1)
        (on b5 b6)
        (on-table b6)
        (on b7 b9)
        (on-table b8)
        (on-table b9)
        (on b10 b4)
        (clear b5)
        (clear b7)
        (clear b10)
    )
    (:goal
        (and
            (on b1 b2)
            (on b2 b6)
            (on b3 b4)
            (on b4 b7)
            (on b5 b10)
            (on b6 b9)
            (on-table b7)
            (on-table b8)
            (on-table b9)
            (on b10 b8)
        )
    )
)