(define (problem BW-8-10-28)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 - block)
    (:init
        (handempty)
        (on b1 b3)
        (on b2 b6)
        (on b3 b8)
        (on-table b4)
        (on b5 b1)
        (on b6 b4)
        (on-table b7)
        (on-table b8)
        (clear b2)
        (clear b5)
        (clear b7)
    )
    (:goal
        (and
            (on b1 b7)
            (on b2 b8)
            (on b3 b1)
            (on b4 b3)
            (on b5 b2)
            (on-table b6)
            (on b7 b6)
            (on b8 b4)
        )
    )
)