(define (problem BW-11-10-21)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on b1 b8)
        (on b2 b7)
        (on b3 b9)
        (on-table b4)
        (on b5 b2)
        (on b6 b11)
        (on b7 b10)
        (on-table b8)
        (on b9 b5)
        (on b10 b4)
        (on b11 b3)
        (clear b1)
        (clear b6)
    )
    (:goal
        (and
            (on b1 b4)
            (on b2 b11)
            (on b3 b8)
            (on b4 b9)
            (on-table b5)
            (on-table b6)
            (on b7 b2)
            (on b8 b7)
            (on b9 b10)
            (on-table b10)
            (on-table b11)
        )
    )
)