(define (problem BW-15-10-60)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 b14 b15 - block)
    (:init
        (handempty)
        (on b1 b15)
        (on b2 b4)
        (on b3 b2)
        (on-table b4)
        (on b5 b1)
        (on-table b6)
        (on b7 b9)
        (on-table b8)
        (on b9 b8)
        (on b10 b3)
        (on b11 b6)
        (on-table b12)
        (on-table b13)
        (on-table b14)
        (on-table b15)
        (clear b5)
        (clear b7)
        (clear b10)
        (clear b11)
        (clear b12)
        (clear b13)
        (clear b14)
    )
    (:goal
        (and
            (on b1 b9)
            (on b2 b12)
            (on b3 b11)
            (on b4 b2)
            (on-table b5)
            (on b6 b13)
            (on-table b7)
            (on-table b8)
            (on b9 b7)
            (on b10 b4)
            (on b11 b6)
            (on-table b12)
            (on-table b13)
            (on-table b14)
            (on b15 b10)
        )
    )
)