(define (problem BW-11-10-33)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on-table b1)
        (on-table b2)
        (on b3 b10)
        (on b4 b11)
        (on b5 b9)
        (on-table b6)
        (on b7 b4)
        (on-table b8)
        (on-table b9)
        (on b10 b7)
        (on b11 b6)
        (clear b1)
        (clear b2)
        (clear b3)
        (clear b5)
        (clear b8)
    )
    (:goal
        (and
            (on-table b1)
            (on b2 b9)
            (on-table b3)
            (on b4 b3)
            (on b5 b8)
            (on b6 b1)
            (on b7 b5)
            (on b8 b11)
            (on-table b9)
            (on b10 b7)
            (on b11 b4)
        )
    )
)