(define (problem BW-11-10-100)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b6)
        (on-table b3)
        (on-table b4)
        (on b5 b2)
        (on b6 b11)
        (on b7 b3)
        (on b8 b7)
        (on b9 b4)
        (on b10 b9)
        (on b11 b10)
        (clear b1)
        (clear b5)
        (clear b8)
    )
    (:goal
        (and
            (on b1 b9)
            (on b2 b1)
            (on b3 b10)
            (on-table b4)
            (on b5 b8)
            (on-table b6)
            (on b7 b5)
            (on-table b8)
            (on b9 b6)
            (on-table b10)
            (on-table b11)
        )
    )
)