(define (problem BW-11-10-84)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on-table b1)
        (on-table b2)
        (on b3 b2)
        (on b4 b11)
        (on-table b5)
        (on b6 b1)
        (on b7 b9)
        (on b8 b10)
        (on-table b9)
        (on-table b10)
        (on-table b11)
        (clear b3)
        (clear b4)
        (clear b5)
        (clear b6)
        (clear b7)
        (clear b8)
    )
    (:goal
        (and
            (on b1 b8)
            (on-table b2)
            (on b3 b7)
            (on-table b4)
            (on b5 b3)
            (on b6 b4)
            (on b7 b6)
            (on b8 b2)
            (on b9 b5)
            (on b10 b11)
            (on-table b11)
        )
    )
)