(define (problem BW-12-10-79)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 - block)
    (:init
        (handempty)
        (on b1 b5)
        (on b2 b3)
        (on b3 b1)
        (on b4 b11)
        (on b5 b10)
        (on b6 b4)
        (on-table b7)
        (on b8 b2)
        (on b9 b12)
        (on-table b10)
        (on-table b11)
        (on b12 b7)
        (clear b6)
        (clear b8)
        (clear b9)
    )
    (:goal
        (and
            (on-table b1)
            (on b2 b6)
            (on b3 b7)
            (on b4 b10)
            (on-table b5)
            (on b6 b8)
            (on b7 b4)
            (on-table b8)
            (on b9 b3)
            (on b10 b12)
            (on b11 b1)
            (on-table b12)
        )
    )
)