(define (problem BW-8-10-90)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 - block)
    (:init
        (handempty)
        (on b1 b3)
        (on-table b2)
        (on b3 b7)
        (on-table b4)
        (on b5 b4)
        (on b6 b8)
        (on-table b7)
        (on b8 b2)
        (clear b1)
        (clear b5)
        (clear b6)
    )
    (:goal
        (and
            (on b1 b3)
            (on-table b2)
            (on-table b3)
            (on-table b4)
            (on b5 b2)
            (on b6 b8)
            (on b7 b4)
            (on-table b8)
        )
    )
)