(define (problem BW-11-10-83)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b10)
        (on b3 b11)
        (on b4 b9)
        (on-table b5)
        (on b6 b4)
        (on-table b7)
        (on b8 b5)
        (on b9 b2)
        (on b10 b1)
        (on-table b11)
        (clear b3)
        (clear b6)
        (clear b7)
        (clear b8)
    )
    (:goal
        (and
            (on b1 b11)
            (on b2 b1)
            (on-table b3)
            (on b4 b10)
            (on-table b5)
            (on-table b6)
            (on b7 b4)
            (on b8 b9)
            (on-table b9)
            (on b10 b2)
            (on-table b11)
        )
    )
)