(define (problem BW-11-10-93)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b8)
        (on b3 b10)
        (on b4 b3)
        (on-table b5)
        (on b6 b9)
        (on b7 b5)
        (on b8 b4)
        (on b9 b2)
        (on b10 b11)
        (on b11 b1)
        (clear b6)
        (clear b7)
    )
    (:goal
        (and
            (on b1 b7)
            (on b2 b8)
            (on b3 b2)
            (on b4 b6)
            (on-table b5)
            (on-table b6)
            (on b7 b3)
            (on-table b8)
            (on b9 b11)
            (on b10 b4)
            (on b11 b1)
        )
    )
)