(define (problem BW-5-10-15)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 - block)
    (:init
        (handempty)
        (on b1 b4)
        (on b2 b3)
        (on b3 b5)
        (on b4 b2)
        (on-table b5)
        (clear b1)
    )
    (:goal
        (and
            (on-table b1)
            (on b2 b1)
            (on b3 b4)
            (on-table b4)
            (on-table b5)
        )
    )
)