(define (problem BW-12-10-30)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 - block)
    (:init
        (handempty)
        (on b1 b10)
        (on b2 b8)
        (on b3 b9)
        (on b4 b12)
        (on b5 b11)
        (on-table b6)
        (on b7 b4)
        (on b8 b5)
        (on b9 b7)
        (on b10 b2)
        (on-table b11)
        (on-table b12)
        (clear b1)
        (clear b3)
        (clear b6)
    )
    (:goal
        (and
            (on b1 b5)
            (on-table b2)
            (on-table b3)
            (on b4 b7)
            (on-table b5)
            (on b6 b4)
            (on b7 b10)
            (on b8 b2)
            (on b9 b6)
            (on b10 b11)
            (on-table b11)
            (on-table b12)
        )
    )
)