(define (problem BW-11-10-45)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b7)
        (on b3 b1)
        (on b4 b2)
        (on b5 b6)
        (on b6 b11)
        (on-table b7)
        (on b8 b10)
        (on b9 b5)
        (on b10 b3)
        (on-table b11)
        (clear b4)
        (clear b8)
        (clear b9)
    )
    (:goal
        (and
            (on-table b1)
            (on b2 b3)
            (on-table b3)
            (on b4 b2)
            (on-table b5)
            (on b6 b5)
            (on-table b7)
            (on b8 b4)
            (on b9 b7)
            (on b10 b11)
            (on b11 b9)
        )
    )
)