(define (problem BW-9-10-57)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 - block)
    (:init
        (handempty)
        (on b1 b7)
        (on b2 b4)
        (on b3 b8)
        (on-table b4)
        (on b5 b1)
        (on b6 b2)
        (on b7 b3)
        (on b8 b6)
        (on b9 b5)
        (clear b9)
    )
    (:goal
        (and
            (on b1 b9)
            (on b2 b3)
            (on b3 b4)
            (on-table b4)
            (on-table b5)
            (on b6 b2)
            (on-table b7)
            (on b8 b5)
            (on b9 b7)
        )
    )
)