(define (problem BW-10-10-11)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
    (:init
        (handempty)
        (on b1 b7)
        (on-table b2)
        (on b3 b2)
        (on b4 b3)
        (on b5 b1)
        (on-table b6)
        (on-table b7)
        (on b8 b6)
        (on b9 b10)
        (on b10 b5)
        (clear b4)
        (clear b8)
        (clear b9)
    )
    (:goal
        (and
            (on b1 b3)
            (on-table b2)
            (on b3 b5)
            (on b4 b6)
            (on b5 b8)
            (on b6 b7)
            (on b7 b10)
            (on-table b8)
            (on b9 b2)
            (on b10 b9)
        )
    )
)