(define (problem BW-11-10-51)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on b1 b11)
        (on b2 b1)
        (on b3 b5)
        (on-table b4)
        (on b5 b6)
        (on b6 b2)
        (on-table b7)
        (on b8 b3)
        (on-table b9)
        (on-table b10)
        (on b11 b10)
        (clear b4)
        (clear b7)
        (clear b8)
        (clear b9)
    )
    (:goal
        (and
            (on b1 b4)
            (on b2 b1)
            (on b3 b5)
            (on b4 b6)
            (on b5 b10)
            (on-table b6)
            (on b7 b11)
            (on-table b8)
            (on-table b9)
            (on b10 b7)
            (on b11 b8)
        )
    )
)