(define (problem BW-9-10-66)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 - block)
    (:init
        (handempty)
        (on b1 b6)
        (on-table b2)
        (on-table b3)
        (on b4 b9)
        (on b5 b8)
        (on-table b6)
        (on b7 b4)
        (on b8 b1)
        (on b9 b5)
        (clear b2)
        (clear b3)
        (clear b7)
    )
    (:goal
        (and
            (on b1 b4)
            (on-table b2)
            (on b3 b5)
            (on b4 b2)
            (on b5 b7)
            (on-table b6)
            (on-table b7)
            (on b8 b9)
            (on-table b9)
        )
    )
)