(define (problem BW-12-10-19)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 - block)
    (:init
        (handempty)
        (on b1 b11)
        (on b2 b5)
        (on-table b3)
        (on b4 b12)
        (on b5 b9)
        (on b6 b7)
        (on b7 b1)
        (on-table b8)
        (on b9 b3)
        (on b10 b4)
        (on b11 b8)
        (on b12 b2)
        (clear b6)
        (clear b10)
    )
    (:goal
        (and
            (on b1 b12)
            (on b2 b7)
            (on b3 b8)
            (on-table b4)
            (on-table b5)
            (on b6 b1)
            (on b7 b6)
            (on b8 b9)
            (on-table b9)
            (on b10 b3)
            (on-table b11)
            (on b12 b10)
        )
    )
)