(define (problem BW-10-10-91)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
    (:init
        (handempty)
        (on b1 b3)
        (on b2 b9)
        (on b3 b7)
        (on-table b4)
        (on b5 b2)
        (on b6 b4)
        (on b7 b10)
        (on b8 b1)
        (on b9 b8)
        (on-table b10)
        (clear b5)
        (clear b6)
    )
    (:goal
        (and
            (on-table b1)
            (on b2 b7)
            (on b3 b4)
            (on b4 b9)
            (on b5 b1)
            (on-table b6)
            (on-table b7)
            (on b8 b5)
            (on b9 b2)
            (on-table b10)
        )
    )
)