(define (problem BW-6-10-94)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 - block)
    (:init
        (handempty)
        (on b1 b6)
        (on b2 b1)
        (on b3 b2)
        (on b4 b5)
        (on b5 b3)
        (on-table b6)
        (clear b4)
    )
    (:goal
        (and
            (on-table b1)
            (on b2 b4)
            (on-table b3)
            (on b4 b6)
            (on b5 b3)
            (on b6 b5)
        )
    )
)