(define (problem BW-11-10-75)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on b1 b2)
        (on-table b2)
        (on b3 b8)
        (on-table b4)
        (on b5 b1)
        (on-table b6)
        (on b7 b11)
        (on b8 b7)
        (on b9 b4)
        (on b10 b9)
        (on b11 b10)
        (clear b3)
        (clear b5)
        (clear b6)
    )
    (:goal
        (and
            (on b1 b9)
            (on b2 b11)
            (on b3 b10)
            (on-table b4)
            (on-table b5)
            (on b6 b7)
            (on b7 b1)
            (on b8 b2)
            (on b9 b5)
            (on b10 b8)
            (on-table b11)
        )
    )
)