(define (problem BW-7-10-58)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 - block)
    (:init
        (handempty)
        (on b1 b4)
        (on b2 b3)
        (on b3 b6)
        (on b4 b5)
        (on-table b5)
        (on b6 b7)
        (on-table b7)
        (clear b1)
        (clear b2)
    )
    (:goal
        (and
            (on-table b1)
            (on-table b2)
            (on-table b3)
            (on b4 b1)
            (on b5 b4)
            (on b6 b7)
            (on-table b7)
        )
    )
)