(define (problem BW-11-10-88)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b5)
        (on-table b3)
        (on b4 b6)
        (on b5 b11)
        (on b6 b7)
        (on-table b7)
        (on b8 b3)
        (on b9 b2)
        (on-table b10)
        (on b11 b4)
        (clear b1)
        (clear b8)
        (clear b9)
        (clear b10)
    )
    (:goal
        (and
            (on-table b1)
            (on b2 b3)
            (on b3 b1)
            (on-table b4)
            (on b5 b6)
            (on b6 b10)
            (on b7 b11)
            (on-table b8)
            (on-table b9)
            (on-table b10)
            (on b11 b4)
        )
    )
)