(define (problem BW-9-10-58)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b4)
        (on b3 b5)
        (on b4 b6)
        (on b5 b1)
        (on-table b6)
        (on b7 b9)
        (on-table b8)
        (on b9 b3)
        (clear b2)
        (clear b7)
        (clear b8)
    )
    (:goal
        (and
            (on b1 b7)
            (on-table b2)
            (on b3 b2)
            (on b4 b1)
            (on-table b5)
            (on b6 b9)
            (on-table b7)
            (on b8 b5)
            (on b9 b4)
        )
    )
)