(define (problem BW-10-10-8)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
    (:init
        (handempty)
        (on b1 b9)
        (on b2 b3)
        (on b3 b1)
        (on b4 b8)
        (on-table b5)
        (on b6 b7)
        (on b7 b2)
        (on b8 b10)
        (on b9 b4)
        (on-table b10)
        (clear b5)
        (clear b6)
    )
    (:goal
        (and
            (on b1 b7)
            (on b2 b4)
            (on b3 b5)
            (on b4 b3)
            (on b5 b1)
            (on b6 b9)
            (on-table b7)
            (on b8 b2)
            (on-table b9)
            (on-table b10)
        )
    )
)