(define (problem BW-12-10-14)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 - block)
    (:init
        (handempty)
        (on b1 b7)
        (on b2 b6)
        (on b3 b8)
        (on b4 b1)
        (on b5 b9)
        (on-table b6)
        (on b7 b11)
        (on-table b8)
        (on b9 b12)
        (on-table b10)
        (on-table b11)
        (on-table b12)
        (clear b2)
        (clear b3)
        (clear b4)
        (clear b5)
        (clear b10)
    )
    (:goal
        (and
            (on b1 b6)
            (on b2 b4)
            (on b3 b9)
            (on b4 b8)
            (on-table b5)
            (on-table b6)
            (on b7 b3)
            (on b8 b10)
            (on b9 b1)
            (on b10 b7)
            (on b11 b12)
            (on b12 b5)
        )
    )
)