(define (problem BW-11-10-94)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on b1 b10)
        (on b2 b4)
        (on-table b3)
        (on b4 b5)
        (on-table b5)
        (on b6 b1)
        (on-table b7)
        (on b8 b11)
        (on b9 b8)
        (on b10 b2)
        (on b11 b3)
        (clear b6)
        (clear b7)
        (clear b9)
    )
    (:goal
        (and
            (on b1 b7)
            (on b2 b9)
            (on b3 b1)
            (on b4 b6)
            (on-table b5)
            (on b6 b11)
            (on-table b7)
            (on b8 b10)
            (on b9 b3)
            (on-table b10)
            (on b11 b2)
        )
    )
)