(define (problem BW-14-10-33)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 b14 - block)
    (:init
        (handempty)
        (on b1 b10)
        (on b2 b3)
        (on b3 b4)
        (on b4 b9)
        (on b5 b1)
        (on-table b6)
        (on-table b7)
        (on-table b8)
        (on b9 b5)
        (on-table b10)
        (on-table b11)
        (on b12 b13)
        (on-table b13)
        (on b14 b2)
        (clear b6)
        (clear b7)
        (clear b8)
        (clear b11)
        (clear b12)
        (clear b14)
    )
    (:goal
        (and
            (on b1 b12)
            (on-table b2)
            (on b3 b1)
            (on b4 b9)
            (on b5 b3)
            (on-table b6)
            (on b7 b11)
            (on-table b8)
            (on-table b9)
            (on-table b10)
            (on b11 b8)
            (on b12 b10)
            (on b13 b14)
            (on b14 b6)
        )
    )
)