(define (problem BW-11-10-81)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on b1 b2)
        (on b2 b7)
        (on b3 b6)
        (on-table b4)
        (on b5 b9)
        (on b6 b4)
        (on b7 b11)
        (on b8 b10)
        (on-table b9)
        (on b10 b3)
        (on-table b11)
        (clear b1)
        (clear b5)
        (clear b8)
    )
    (:goal
        (and
            (on b1 b2)
            (on b2 b10)
            (on-table b3)
            (on b4 b7)
            (on b5 b1)
            (on-table b6)
            (on b7 b6)
            (on-table b8)
            (on-table b9)
            (on b10 b8)
            (on b11 b3)
        )
    )
)