(define (problem BW-11-10-31)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on b1 b9)
        (on b2 b3)
        (on-table b3)
        (on b4 b10)
        (on b5 b6)
        (on b6 b11)
        (on b7 b2)
        (on b8 b1)
        (on-table b9)
        (on b10 b8)
        (on-table b11)
        (clear b4)
        (clear b5)
        (clear b7)
    )
    (:goal
        (and
            (on b1 b7)
            (on b2 b9)
            (on b3 b1)
            (on b4 b5)
            (on-table b5)
            (on-table b6)
            (on b7 b10)
            (on b8 b11)
            (on b9 b6)
            (on b10 b8)
            (on b11 b2)
        )
    )
)