(define (problem BW-11-10-29)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on-table b1)
        (on-table b2)
        (on-table b3)
        (on b4 b2)
        (on b5 b10)
        (on b6 b3)
        (on b7 b9)
        (on b8 b5)
        (on b9 b11)
        (on-table b10)
        (on b11 b4)
        (clear b1)
        (clear b6)
        (clear b7)
        (clear b8)
    )
    (:goal
        (and
            (on b1 b6)
            (on-table b2)
            (on b3 b10)
            (on b4 b11)
            (on b5 b3)
            (on b6 b2)
            (on b7 b9)
            (on b8 b7)
            (on b9 b4)
            (on-table b10)
            (on-table b11)
        )
    )
)