(define (problem BW-12-10-71)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 - block)
    (:init
        (handempty)
        (on b1 b5)
        (on b2 b1)
        (on b3 b8)
        (on-table b4)
        (on b5 b11)
        (on b6 b7)
        (on-table b7)
        (on b8 b2)
        (on b9 b12)
        (on b10 b3)
        (on b11 b9)
        (on b12 b6)
        (clear b4)
        (clear b10)
    )
    (:goal
        (and
            (on-table b1)
            (on b2 b10)
            (on b3 b9)
            (on b4 b5)
            (on-table b5)
            (on b6 b12)
            (on b7 b1)
            (on b8 b4)
            (on b9 b8)
            (on b10 b3)
            (on-table b11)
            (on-table b12)
        )
    )
)