(define (problem BW-11-10-3)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on-table b1)
        (on-table b2)
        (on b3 b1)
        (on b4 b7)
        (on b5 b2)
        (on b6 b5)
        (on b7 b3)
        (on b8 b4)
        (on b9 b11)
        (on b10 b8)
        (on-table b11)
        (clear b6)
        (clear b9)
        (clear b10)
    )
    (:goal
        (and
            (on b1 b4)
            (on-table b2)
            (on-table b3)
            (on-table b4)
            (on b5 b7)
            (on-table b6)
            (on b7 b9)
            (on b8 b6)
            (on b9 b2)
            (on b10 b1)
            (on-table b11)
        )
    )
)