(define (problem BW-11-10-77)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b6)
        (on b3 b5)
        (on-table b4)
        (on-table b5)
        (on-table b6)
        (on b7 b9)
        (on b8 b3)
        (on b9 b10)
        (on b10 b1)
        (on b11 b2)
        (clear b4)
        (clear b7)
        (clear b8)
        (clear b11)
    )
    (:goal
        (and
            (on-table b1)
            (on-table b2)
            (on-table b3)
            (on b4 b8)
            (on b5 b4)
            (on b6 b5)
            (on-table b7)
            (on-table b8)
            (on b9 b1)
            (on b10 b6)
            (on b11 b9)
        )
    )
)