(define (problem BW-10-10-19)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b6)
        (on b3 b1)
        (on b4 b2)
        (on b5 b9)
        (on b6 b7)
        (on b7 b5)
        (on b8 b4)
        (on-table b9)
        (on b10 b8)
        (clear b3)
        (clear b10)
    )
    (:goal
        (and
            (on b1 b10)
            (on-table b2)
            (on-table b3)
            (on b4 b3)
            (on b5 b6)
            (on b6 b8)
            (on b7 b5)
            (on b8 b9)
            (on b9 b2)
            (on-table b10)
        )
    )
)