(define (problem BW-11-10-73)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on b1 b10)
        (on b2 b9)
        (on-table b3)
        (on-table b4)
        (on b5 b4)
        (on b6 b3)
        (on b7 b6)
        (on b8 b1)
        (on-table b9)
        (on b10 b7)
        (on-table b11)
        (clear b2)
        (clear b5)
        (clear b8)
        (clear b11)
    )
    (:goal
        (and
            (on-table b1)
            (on b2 b8)
            (on b3 b11)
            (on-table b4)
            (on b5 b7)
            (on b6 b9)
            (on b7 b3)
            (on b8 b5)
            (on-table b9)
            (on b10 b1)
            (on b11 b6)
        )
    )
)