(define (problem BW-12-10-61)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 - block)
    (:init
        (handempty)
        (on b1 b11)
        (on b2 b8)
        (on-table b3)
        (on b4 b3)
        (on b5 b10)
        (on b6 b7)
        (on-table b7)
        (on b8 b1)
        (on b9 b5)
        (on-table b10)
        (on b11 b9)
        (on b12 b4)
        (clear b2)
        (clear b6)
        (clear b12)
    )
    (:goal
        (and
            (on b1 b5)
            (on b2 b4)
            (on-table b3)
            (on b4 b9)
            (on b5 b10)
            (on b6 b7)
            (on-table b7)
            (on-table b8)
            (on b9 b8)
            (on b10 b12)
            (on b11 b2)
            (on b12 b3)
        )
    )
)