(define (problem BW-10-10-74)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
    (:init
        (handempty)
        (on b1 b6)
        (on b2 b8)
        (on b3 b1)
        (on-table b4)
        (on b5 b3)
        (on b6 b2)
        (on b7 b5)
        (on b8 b10)
        (on b9 b4)
        (on b10 b9)
        (clear b7)
    )
    (:goal
        (and
            (on b1 b7)
            (on b2 b9)
            (on b3 b1)
            (on b4 b10)
            (on b5 b6)
            (on b6 b4)
            (on b7 b8)
            (on b8 b2)
            (on-table b9)
            (on b10 b3)
        )
    )
)