(define (problem BW-9-10-69)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b4)
        (on b3 b8)
        (on b4 b3)
        (on b5 b1)
        (on b6 b5)
        (on b7 b2)
        (on b8 b6)
        (on-table b9)
        (clear b7)
        (clear b9)
    )
    (:goal
        (and
            (on b1 b3)
            (on b2 b7)
            (on b3 b5)
            (on-table b4)
            (on-table b5)
            (on-table b6)
            (on-table b7)
            (on-table b8)
            (on b9 b8)
        )
    )
)