(define (problem BW-11-10-43)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b8)
        (on b3 b7)
        (on-table b4)
        (on b5 b4)
        (on-table b6)
        (on b7 b10)
        (on-table b8)
        (on-table b9)
        (on b10 b2)
        (on b11 b1)
        (clear b3)
        (clear b5)
        (clear b6)
        (clear b9)
        (clear b11)
    )
    (:goal
        (and
            (on b1 b8)
            (on b2 b9)
            (on b3 b7)
            (on b4 b3)
            (on b5 b6)
            (on b6 b2)
            (on-table b7)
            (on b8 b4)
            (on-table b9)
            (on b10 b11)
            (on-table b11)
        )
    )
)