(define (problem BW-11-10-58)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on b1 b10)
        (on-table b2)
        (on b3 b8)
        (on b4 b5)
        (on b5 b11)
        (on-table b6)
        (on b7 b6)
        (on-table b8)
        (on b9 b3)
        (on b10 b2)
        (on b11 b9)
        (clear b1)
        (clear b4)
        (clear b7)
    )
    (:goal
        (and
            (on b1 b3)
            (on-table b2)
            (on b3 b5)
            (on b4 b2)
            (on b5 b7)
            (on b6 b10)
            (on b7 b11)
            (on b8 b4)
            (on-table b9)
            (on-table b10)
            (on b11 b8)
        )
    )
)