(define (problem BW-11-10-37)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on b1 b4)
        (on-table b2)
        (on b3 b1)
        (on-table b4)
        (on b5 b7)
        (on-table b6)
        (on b7 b3)
        (on b8 b6)
        (on b9 b2)
        (on b10 b5)
        (on b11 b9)
        (clear b8)
        (clear b10)
        (clear b11)
    )
    (:goal
        (and
            (on-table b1)
            (on-table b2)
            (on-table b3)
            (on b4 b7)
            (on b5 b1)
            (on b6 b3)
            (on b7 b10)
            (on b8 b9)
            (on b9 b4)
            (on b10 b2)
            (on b11 b6)
        )
    )
)