(define (problem BW-10-10-62)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b8)
        (on b3 b6)
        (on b4 b1)
        (on-table b5)
        (on-table b6)
        (on-table b7)
        (on b8 b4)
        (on-table b9)
        (on b10 b9)
        (clear b2)
        (clear b3)
        (clear b5)
        (clear b7)
        (clear b10)
    )
    (:goal
        (and
            (on b1 b4)
            (on b2 b7)
            (on b3 b9)
            (on b4 b2)
            (on-table b5)
            (on b6 b10)
            (on b7 b6)
            (on-table b8)
            (on b9 b1)
            (on b10 b8)
        )
    )
)