(define (problem BW-10-10-54)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
    (:init
        (handempty)
        (on b1 b9)
        (on b2 b5)
        (on b3 b6)
        (on b4 b10)
        (on b5 b3)
        (on b6 b4)
        (on-table b7)
        (on b8 b7)
        (on-table b9)
        (on-table b10)
        (clear b1)
        (clear b2)
        (clear b8)
    )
    (:goal
        (and
            (on-table b1)
            (on b2 b4)
            (on b3 b10)
            (on b4 b9)
            (on b5 b6)
            (on b6 b8)
            (on-table b7)
            (on-table b8)
            (on b9 b5)
            (on b10 b2)
        )
    )
)