(define (problem BW-11-10-54)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b6)
        (on b3 b5)
        (on b4 b7)
        (on b5 b9)
        (on b6 b3)
        (on b7 b11)
        (on b8 b2)
        (on b9 b10)
        (on-table b10)
        (on b11 b8)
        (clear b1)
        (clear b4)
    )
    (:goal
        (and
            (on b1 b7)
            (on b2 b5)
            (on-table b3)
            (on-table b4)
            (on b5 b1)
            (on-table b6)
            (on b7 b3)
            (on b8 b4)
            (on-table b9)
            (on b10 b11)
            (on b11 b2)
        )
    )
)