(define (problem BW-14-10-51)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 b14 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b6)
        (on-table b3)
        (on-table b4)
        (on b5 b9)
        (on-table b6)
        (on b7 b1)
        (on b8 b4)
        (on b9 b8)
        (on-table b10)
        (on b11 b14)
        (on b12 b11)
        (on-table b13)
        (on-table b14)
        (clear b2)
        (clear b3)
        (clear b5)
        (clear b7)
        (clear b10)
        (clear b12)
        (clear b13)
    )
    (:goal
        (and
            (on b1 b6)
            (on b2 b4)
            (on-table b3)
            (on-table b4)
            (on b5 b3)
            (on-table b6)
            (on b7 b12)
            (on b8 b10)
            (on b9 b2)
            (on b10 b5)
            (on b11 b1)
            (on-table b12)
            (on b13 b7)
            (on b14 b13)
        )
    )
)