(define (problem BW-12-10-33)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 - block)
    (:init
        (handempty)
        (on b1 b9)
        (on b2 b3)
        (on b3 b11)
        (on b4 b12)
        (on-table b5)
        (on-table b6)
        (on b7 b1)
        (on b8 b10)
        (on b9 b4)
        (on b10 b6)
        (on b11 b7)
        (on-table b12)
        (clear b2)
        (clear b5)
        (clear b8)
    )
    (:goal
        (and
            (on b1 b3)
            (on b2 b5)
            (on b3 b10)
            (on-table b4)
            (on b5 b7)
            (on-table b6)
            (on b7 b6)
            (on b8 b2)
            (on b9 b8)
            (on b10 b4)
            (on b11 b9)
            (on b12 b1)
        )
    )
)