(define (problem BW-10-10-58)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
    (:init
        (handempty)
        (on-table b1)
        (on b2 b3)
        (on b3 b10)
        (on b4 b7)
        (on b5 b1)
        (on b6 b2)
        (on b7 b8)
        (on-table b8)
        (on b9 b4)
        (on b10 b9)
        (clear b5)
        (clear b6)
    )
    (:goal
        (and
            (on b1 b3)
            (on-table b2)
            (on b3 b5)
            (on b4 b1)
            (on-table b5)
            (on-table b6)
            (on b7 b4)
            (on b8 b2)
            (on b9 b8)
            (on b10 b7)
        )
    )
)