(define (problem BW-10-10-43)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
    (:init
        (handempty)
        (on-table b1)
        (on-table b2)
        (on b3 b9)
        (on b4 b7)
        (on b5 b6)
        (on b6 b4)
        (on-table b7)
        (on-table b8)
        (on b9 b2)
        (on b10 b1)
        (clear b3)
        (clear b5)
        (clear b8)
        (clear b10)
    )
    (:goal
        (and
            (on b1 b4)
            (on-table b2)
            (on b3 b7)
            (on b4 b8)
            (on b5 b9)
            (on b6 b10)
            (on b7 b1)
            (on b8 b5)
            (on b9 b6)
            (on-table b10)
        )
    )
)