(define (problem BW-11-10-35)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - block)
    (:init
        (handempty)
        (on-table b1)
        (on-table b2)
        (on b3 b6)
        (on b4 b1)
        (on b5 b8)
        (on b6 b2)
        (on-table b7)
        (on-table b8)
        (on b9 b5)
        (on b10 b4)
        (on b11 b9)
        (clear b3)
        (clear b7)
        (clear b10)
        (clear b11)
    )
    (:goal
        (and
            (on b1 b5)
            (on b2 b4)
            (on b3 b7)
            (on b4 b9)
            (on-table b5)
            (on-table b6)
            (on b7 b8)
            (on b8 b1)
            (on b9 b11)
            (on b10 b3)
            (on b11 b10)
        )
    )
)