(define (problem BW-10-10-50)
    (:domain blocksworld)
    (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
    (:init
        (handempty)
        (on-table b1)
        (on-table b2)
        (on b3 b5)
        (on-table b4)
        (on b5 b6)
        (on b6 b9)
        (on b7 b8)
        (on-table b8)
        (on b9 b2)
        (on b10 b7)
        (clear b1)
        (clear b3)
        (clear b4)
        (clear b10)
    )
    (:goal
        (and
            (on-table b1)
            (on-table b2)
            (on b3 b2)
            (on b4 b9)
            (on b5 b10)
            (on-table b6)
            (on b7 b5)
            (on b8 b3)
            (on b9 b7)
            (on b10 b6)
        )
    )
)